### ISSUE TITLE
[FEATURE REQUEST] option to remove audio track in video download

### ISSUE THREAD

**Issue by quazar-omega** [deniscerri/ytdlnis#112]
**Is your feature request available in yt-dlp? Please describe.**
I'd like to be able to download videos without the audio track, yt-dlp allows you to do it with the format option:
```
$ yt-dlp -f bestvideo <url>
```

**Describe the solution you'd like**
Adding an "Audio Track" chip at the bottom in the video download dialog would make it easy to toggle it on or off

**Describe alternatives you've considered**
Creating a custom command, though, for something like this that is pretty generic, I think it could benefit from being a default option

**Additional context**
![1682522800552](https://user-images.githubusercontent.com/56311398/234624824-1d4cd0f8-5064-4702-9eec-2fea7f185053.png)

By the way, thanks for the excellent app!

**Comment by soymadip** [comment]
> **Is your feature request available in yt-dlp? Please describe.**
> I'd like to be able to download videos without the audio track, yt-dlp allows you to do it with the format option:
> ```
> $ yt-dlp -f bestvideo <url>
> ```
> 
> **Describe the solution you'd like**
> Adding an "Audio Track" chip at the bottom in the video download dialog would make it easy to toggle it on or off
> 
> **Describe alternatives you've considered**
> Creating a custom command, though, for something like this that is pretty generic, I think it could benefit from being a default option
> 
> **Additional context**
> ![1682522800552](https://user-images.githubusercontent.com/56311398/234624824-1d4cd0f8-5064-4702-9eec-2fea7f185053.png)
> 
> 
> By the way, thanks for the excellent app!

That will be cool, but as workaround you can go to custom command tab and use the command

**Comment by quazar-omega** [comment]
Yeah I know, I already mentioned that, it's actually great that the app allows doing it, in fact I'll rely on that in the meantime

**Comment by soymadip** [comment]
> Yeah I know, I already mentioned that, it's actually great that the app allows doing it, in fact I'll rely on that in the meantime

Oh, sorry i didn't read the last part

**Comment by deniscerri** [comment]
@quazar-omega good idea. The only issue im thinking about right now is in cases where the user selects a format that contains both audio and video. I wonder if yt-dlp allows you to remove the video from that kind of format

**Comment by quazar-omega** [comment]
> format that contains both audio and video. I wonder if yt-dlp allows you to remove the **video**

Did you mean audio?  
Anyway, I'm not sure, but now that you say that, it occurred to me that such a toggle could filter out the formats that have audio instead of getting the "best"

**Comment by deniscerri** [comment]
Actually the app gets the appropriate format based on your preference. By default the app chooses the "best" but if you choose lets say 720p, it will auto-select the best 720p format. 

As per your idea, its perfectly doable. Also Instead of having an "Audio Track" chip, we can have a "Remove Audio Track" chip since most people want audio lol.
The only problem is that the app uses two different ways of fetching formats, yt-dlp and Invidious if its youtube (its faster).
I don't know what version you are using, but the latest builds u can have an option to choose between them for youtube queries.

On yt-dlp formats i can tell which one don't have audio but invidious i can't.

**Comment by deniscerri** [comment]
Ill try something out nonetheless and get back at you. In cases where all formats have audio, ill disable the chip obviously.

**Comment by quazar-omega** [comment]
> Ill try something out nonetheless and get back at you

Ok, thank you for giving this a shot!

**Comment by deniscerri** [comment]
Feature has been implemented. I might post a build in the telegram channel tomorrow, if you'd like to test it out. 
I took the easy way out and didn't do any filtering. 
Choose any video format you want, either way with the chip turned on it will remove the audio if it has any.

**Comment by quazar-omega** [comment]
Wow, that was fast, I'm glad you were able to do it this way! I'll wait for the next github release as I have access to that

**Comment by quazar-omega** [comment]
Just tried it, worked like a breeze, thank you!! 💚

**Comment by deniscerri** [comment]
awesome
