### ISSUE TITLE
Default Video Format ID

### ISSUE THREAD

**Issue by matt873** [deniscerri/ytdlnis#113]
Can You add an option in settings for default Format ID as in PowerTube. It would make it easy to download videos in the same quality or codec instead of selecting the same every time when downloading.

![Screenshot_2023-04-26-22-28-25-142_ussr.razar.youtube_dl_1.jpg](https://user-images.githubusercontent.com/108935493/234696024-177439b7-3446-471a-b6a3-05cdcdea4c62.jpg)

![Screenshot_2023-04-26-22-28-35-768_ussr.razar.youtube_dl.jpg](https://user-images.githubusercontent.com/108935493/234696078-3f3eb9a9-daa8-451e-b5b2-c551d93a93ce.jpg)

![Screenshot_2023-04-27-01-20-58-224_ussr.razar.youtube_dl_1.jpg](https://user-images.githubusercontent.com/108935493/234696112-02c10942-e6cf-4c88-b390-921ebaa84fd4.jpg)

**Comment by deniscerri** [comment]
For now you can select "Video Quality" option in the settings and it will choose a format similar to it.
Meanwhile ill add this to my todo list.

Thanks for the suggestion

**Comment by deniscerri** [comment]
Feature has been implemented.

![image](https://user-images.githubusercontent.com/64997243/234940145-19b3adca-7aa9-4191-803e-3733b7efc3f4.png)
![image](https://user-images.githubusercontent.com/64997243/234940226-4e65193a-b30f-4f57-920f-62575a080f3d.png)

If you write down the format id, it will take precedence against "Video Quality". If it doesnt find a format with that id, then it will use the "Video Quality" preference
If the audio has formats it will check if it has the id you put aswell :)

If you want come to the telegram channel and ask for a build apk if you want to test it out
