### ISSUE TITLE
[BUG] Non-nullability check fails on TikTok videos

### ISSUE THREAD

**Issue by badp** [deniscerri/ytdlnis#114]
**Describe the bug**
Attempting to download TikTok videos through the app fails with ```Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter; parameter <this>```

**To Reproduce**
Attempt to download e.g. https://www.tiktok.com/@jeremythemanager/video/7223956433669246250

**Expected behavior**
the download panel opens letting you pick a download location and other settings.

**Screenshots / Video Recording**
—

**(please complete the following information):**
 - Android Version: 14 (UPB1.230309.014) (yes I know)
 - App Version: 1.6
 - Other Device Information: Pixel 7

**Additional context**
The same behaviour occurs on tiktok short links (vm.tiktok.com/xxxxxxxxxx)

**Comment by badp** [comment]
I should point out that downloading these videos succeeds from the "terminal" interface

**Comment by deniscerri** [comment]
Yes this bug is fixed in the latest builds. It was a problem with fetching metadata and showing it in the screen.

**Comment by deniscerri** [comment]
[1.6.1](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.1)
