### ISSUE TITLE
[FEATURE REQUEST] Instagram and Facebook private video download 

### ISSUE THREAD

**Issue by nilpatel9099sn** [deniscerri/ytdlnis#121]
**Is your feature request available in yt-dlp? Please describe.**
Ytdlp has feature that we can pass cookies,so if we want to download private video we need to pass cookies with command line option.

**Describe the solution you'd like**
For a better solution in Android ,we can use Android Web view to login Instagram or (other site like facebook) and get all cookies programmatically.

**Comment by deniscerri** [comment]
This is already implemented. Go to more section and press cookies. Login and press ok on the top. Good luck

**Comment by nilpatel9099sn** [comment]
I checked and working perfect, ❤️ very useful
