### ISSUE TITLE
[BUG] It is delivering MP3 file at 128Kbps.

### ISSUE THREAD

**Issue by CSantosVL** [deniscerri/ytdlnis#125]
You choose a song to download and choose the Opus 251 and the MP3 format, it will give you a 128Kbps MP3 in the final file. Even selecting the average 251Kbps Opus.

**Comment by deniscerri** [comment]
what link are you using

**Comment by CSantosVL** [comment]
> what link are you using

https://youtu.be/ and https://music.youtube.com/

In both options it keeps giving me a 128Kbps file, I only get a larger Kbps using the Command Template option.

![NO COMMAND TEMPLATE](https://user-images.githubusercontent.com/132719189/236605054-80120b06-646d-4e71-909c-9d8e0992166c.png)


![WITH COMMAND TEMPLATE](https://user-images.githubusercontent.com/132719189/236605230-e4c04b01-0358-48ca-8b41-c30d3d99ef0c.png)

**Comment by deniscerri** [comment]
gotcha

**Comment by deniscerri** [comment]
Issue had been fixed. I was experimenting with --remux-video for audio and that was the culprit. I reverted back to using -x --audio-format <container>
