### ISSUE TITLE
Can' Download

### ISSUE THREAD

**Issue by Charlie-Lala** [deniscerri/ytdlnis#128]
~ $ yt-dlp https://music.youtube.com/watch?v=wy709iNG6i8&feature=share

[youtube] Extracting URL: https://music.youtube.com/watch?v=wy709iNG6i8&feature=share
[youtube] wy709iNG6i8: Downloading webpage
[youtube] wy709iNG6i8: Downloading android player API JSON
[youtube] wy709iNG6i8: Downloading iframe API JS
[youtube] wy709iNG6i8: Downloading web player API JSON
[youtube] wy709iNG6i8: Downloading android music player API JSON
[youtube] wy709iNG6i8: Downloading web music client config
[youtube] wy709iNG6i8: Downloading web music player API JSONWARNING: [youtube] Unable to download webpage: IncompleteRead(271593 bytes read)
WARNING: [youtube] IncompleteRead(20 bytes read). Retrying (1/3)...
WARNING: [youtube] IncompleteRead(14564 bytes read). Retrying (2/3)...
WARNING: [youtube] IncompleteRead(0 bytes read). Retrying (3/3)...
WARNING: [youtube] Unable to download webpage: Remote end closed connection without response
WARNING: [youtube] IncompleteRead(32394 bytes read). Retrying (1/3)...
WARNING: [youtube] IncompleteRead(15428 bytes read). Retrying (2/3)...
WARNING: [youtube] IncompleteRead(32137 bytes read). Retrying (3/3)...
WARNING: [youtube] Unable to download API page: IncompleteRead(14196 bytes read) (caused by IncompleteRead(14196 bytes read)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] IncompleteRead(8 bytes read). Retrying (1/3)...
WARNING: [youtube] IncompleteRead(4 bytes read). Retrying (2/3)...
WARNING: [youtube] IncompleteRead(11397 bytes read). Retrying (3/3)...
WARNING: [youtube] Unable to download API page: IncompleteRead(15437 bytes read) (caused by IncompleteRead(15437 bytes read)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Unable to download webpage: IncompleteRead(37099 bytes read)
WARNING: [youtube] IncompleteRead(113714 bytes read). Retrying (1/3)...
WARNING: [youtube] IncompleteRead(97327 bytes read). Retrying (2/3)...
WARNING: [youtube] IncompleteRead(97335 bytes read). Retrying (3/3)...

WARNING: [youtube] Unable to download API page: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] wy709iNG6i8: Unable to download API page: IncompleteRead(97347 bytes read) (caused by IncompleteRead(97347 bytes read)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by deniscerri** [comment]
Just as the output says. Check if you are in the latest ytdlp. U can go to the settings and update it there.

**Comment by Charlie-Lala** [comment]
> Just as the output says. Check if you are in the latest ytdlp. U can go to the settings and update it there.

I did.
![Screenshot_2023-05-12-14-39-41-397_com deniscerri ytdl](https://github.com/deniscerri/ytdlnis/assets/122247009/4323023a-8056-4f9f-8469-3b9364989305)

**Comment by deniscerri** [comment]
Well, report this issue to yt-dlp repository 
![SmartSelect_20230512_101126_Chrome](https://github.com/deniscerri/ytdlnis/assets/64997243/5e3af80c-d401-4414-a2c9-3907710e57df)

**Comment by Charlie-Lala** [comment]
Thanks
