### ISSUE TITLE
[FEATURE REQUEST] Show process of each block when download with multi-part 

### ISSUE THREAD

**Issue by nilpatel9099sn** [deniscerri/ytdlnis#133]
**Is your feature request available in yt-dlp? Please describe.**

**Describe the solution you'd like**

1. when large file are downloading with aria2c option in small parallel chunks show each block progress like attached in screen shot .
this would be so nice .

2.Also add some flag or text if file is resumable or not while downloading .

![image](https://github.com/deniscerri/ytdlnis/assets/54953661/38d91b8c-4a87-411a-b423-0e11a5ba1a93)

**Comment by deniscerri** [comment]
Ytdl android doesnt support multiple progress callbacks, only one. So theres nothing i can do about this. Perhaps create this issue in [Their repo](https://github.com/yausername/youtubedl-android) 

As per point 2. All downloads are resumable cuz they are cached in the app
