### ISSUE TITLE
[BUG] Merge conflicts in Weblate

### ISSUE THREAD

**Issue by HardcodedCat** [deniscerri/ytdlnis#135]
**Describe the bug**
Unable to add translations to YT-DLnis weblate.

**Screenshots**
![Screenshot_20230517-120213](https://github.com/deniscerri/ytdlnis/assets/103902727/d142bb95-5e4a-4a80-b7e3-0980d733454a)
![Screenshot_20230517-120447](https://github.com/deniscerri/ytdlnis/assets/103902727/802c7d9d-5650-4294-8aad-02d297adb96a)
![Screenshot_20230517-120453_Vivaldi_Browser_Snapshot](https://github.com/deniscerri/ytdlnis/assets/103902727/01ccc02d-5f34-4352-b2f6-959aca0a5e0a)

**Comment by Qaz-7** [comment]
If the new pull request doesn't merge, the problem can't be solved.

**Comment by deniscerri** [comment]
fixed
