### ISSUE TITLE
https://github.com/JunkFood02/Seal/issues/661 (Mass download video)

### ISSUE THREAD

**Issue by Wjxfi** [deniscerri/ytdlnis#140]
look

https://github.com/JunkFood02/Seal/issues/661

**Comment by deniscerri** [comment]
Ytdlnis supports mass download

**Comment by deniscerri** [comment]
Drop the list of links to a txt file and then share the txt file to the app and you are good to go. If the recent update is not working, jump over to telegram and ill give you an apk with the hotfix. Been a while since i used that feature tbf @Wjxfi

**Comment by deniscerri** [comment]
Recommendations are not supposed to show. So ill fix that.

But u can do this. In thr settings go go downloads then concurrent downloads and choose how many downloads u want to download st the sametime.

Then in home screen long press a card and then press the rest and press the dowload button on the top. Good luck

**Comment by deniscerri** [comment]
Ill try to fix this bug in a few hrs. Ill drop you an apk on telegram. See ya
