### ISSUE TITLE
When I change the language not everything changes

### ISSUE THREAD

**Issue by Wjxfi** [deniscerri/ytdlnis#141]
![2d4e67de-5483-4165-91c3-aac6b795c90e.jpg](https://github.com/deniscerri/ytdlnis/assets/113500363/73124b77-922b-4824-980d-ffbbe12965e4)

**Comment by deniscerri** [comment]
@ me on telegram. I just made a build you can try out

**Comment by deniscerri** [comment]
this has been resolved
