### ISSUE TITLE
put the true number of megabytes/gigabytes instead of the question mark

### ISSUE THREAD

**Issue by Wjxfi** [deniscerri/ytdlnis#143]
![afcec5e6-2bbd-432c-b5c8-4a3a8f408bfa.jpg](https://github.com/deniscerri/ytdlnis/assets/113500363/9fc6f067-494b-4562-9021-0185a053b311)

**Comment by deniscerri** [comment]
Thats because the app doesnt have URI permissions. Try changing the download path in the settings and it will certainly show up after that

**Comment by deniscerri** [comment]
Just try changing the download path. U can choose the same path. 
That's how the app gains uri permission. U cant gain uri permission otherwise
