### ISSUE TITLE
When downloading, it takes too long to analyze the video information and display the download window.

### ISSUE THREAD

**Issue by root-kernelhacker** [deniscerri/ytdlnis#152]
When downloading, it takes too long to analyze the video information and display the download window.

If you compare it with the SEAL downloader that uses the same engine, you'll know, but it's frustrating because the delay that occurs when getting information to start downloading is too long.  Any solution?

The UI in the old power-dl format is too good.

**Comment by teddysulaimanGL** [comment]
Sir, this isn't a bug, this is just how long yt-dlp takes to fetch the data (except for YouTube which is uses other API) and this is far beyond the Dev's control. Well, you can tell the yt-dlp maintainers about this, who knows they can find the solution and fix this

**Comment by soymadip** [comment]
Seal 's waiting time longer than this app(because of it's workflow process)

You can use snaptube if you don't wanna wait as it uses it's own api hosted on snaptube's proprietary server

**Comment by deniscerri** [comment]
You are most using quick download mode and you have download logs turned on, correct? @root-kernelhacker

**Comment by root-kernelhacker** [comment]
> 

don"t use qucik download, log.(off)

**Comment by deniscerri** [comment]
Well if you dont want to wait for the app to analyze video information , you can turn on quick download.
It will immediately show the window. The app will update the information while its downloading

**Comment by deniscerri** [comment]
Let me know if that resolved the issue.

**Comment by root-kernelhacker** [comment]
First of all, after turning off all options such as thumbnails, art covers, and subtitles in the settings, the download setting window appears a little faster, but it is still slow.  Also, if you set fast download, the video information itself is not available, so it is meaningless.

**Comment by deniscerri** [comment]
The video information will get updated while its downloading, so u dont worry about that. If the title and author is empty, it wont be empty in the end.
