### ISSUE TITLE
[FEATURE REQUEST] KOR language

### ISSUE THREAD

**Issue by root-kernelhacker** [deniscerri/ytdlnis#155]
Korean translation is in progress.  Once 100% translation is complete, when will the patched version of the language files be available?  (Translation can be done today)

**Comment by deniscerri** [comment]
Already ahead of you. The language has been implemented in the app. When you are done you can @ me on telegram, ill drop you an apk

**Comment by deniscerri** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/64997243/9c622b29-5665-48b3-a216-05f14cd7d2ad)

**Comment by root-kernelhacker** [comment]
Does that mean Korean is already 100% translated?  Looking at the translation site, it is 2%, so it is still being translated.  We will give you feedback when we reach 100%.  I understood it to mean that you can receive a file with Korean language if you request it through Telegram.

**Comment by deniscerri** [comment]
No its not 100% translated yet. The translations are automatically passed onto me from weblate. I will never miss a translation, don't worry

**Comment by root-kernelhacker** [comment]
Korean translation has been completed. How do I get a APP that includes Korean?

**Comment by deniscerri** [comment]
Great job. Go to the telegram group and mention me

**Comment by root-kernelhacker** [comment]
I don't use telegram. I know that it is possible to distribute through a telegram link without installing telegram. I want an arm64-v8a only build.

**Comment by deniscerri** [comment]
alright give me a minute

**Comment by root-kernelhacker** [comment]
Thank you. I also translated the SEAL app into Korean by myself. I'm happy to translate YTDLins too.

**Comment by deniscerri** [comment]
https://t.me/ytdlnis/14273

**Comment by deniscerri** [comment]
If you cant join telegram, then i guess you'll have to wait for the official release

**Comment by root-kernelhacker** [comment]
Fixed some Korean translation errors. Hopefully the corrected translation will be applied in the official build. We are testing the translated APP by temporarily installing Telegram. thank you

**Comment by deniscerri** [comment]
yes the fixes will be applied, no problem

**Comment by root-kernelhacker** [comment]
One last request.  Please distribute the Korean version that has been finally translated through the telegram link as you did in the past.  In order to increase the accuracy as much as possible, I matched it according to the function and situation of the app, but I thought it was insufficient, so I want to check it.  thank you  (A lot of people around me use this app because of me ^^)
