### ISSUE TITLE
[BUG] remove '|' 

### ISSUE THREAD

**Issue by root-kernelhacker** [deniscerri/ytdlnis#159]
Like the attached image,
 '|' at the top right of the downloaded list  A shape line is displayed.
![1000042569](https://github.com/deniscerri/ytdlnis/assets/132817163/5aa53115-9d06-4085-8bce-b03bf4cbec0d)

**Comment by root-kernelhacker** [comment]
It seems to have been intentionally put in for distinction rather than a bug, but '|'  I think it would be better to put spaces rather than form.  For your reference, 

all Korean texts have been translated as flexibly and accurately as possible.  

Sorry, please build for ARM64-v8a with the final translated file once more and send it to Telegram.

**Comment by teddysulaimanGL** [comment]
That's supposed to be a divider for a grouping chips by site you're download video/audio from. If you only downloading only from one site (YouTube, for example), those chips won't be displayed

**Comment by teddysulaimanGL** [comment]
> Sorry, please build for ARM64-v8a with the final translated file once more and send it to Telegram.

He's currently at work, so he would be able to do than in a few hous

**Comment by root-kernelhacker** [comment]
I only download from YouTube, but the corresponding chip is displayed.  All right.  I understand that you are distinguishing by necessity.

**Comment by deniscerri** [comment]
its fixed

**Comment by root-kernelhacker** [comment]
One last request.  Please distribute the Korean version that has been finally translated through the telegram link as you did in the past.  In order to increase the accuracy as much as possible, I matched it according to the function and situation of the app, but I thought it was insufficient, so I want to check it.  thank you  (A lot of people around me use this app because of me ^^)

**Comment by teddysulaimanGL** [comment]
Here https://t.me/ytdlnis/14493?single

**Comment by teddysulaimanGL** [comment]
Please note that he can't always push the commit and send the APK as soon as you add/edit the translations, I hope you understand. Also it's easier for all of us if you join the group, so you don't have to open new issues everytime you want to tell issues to us
