### ISSUE TITLE
Auto Generated Captions & Custom  Subdirectory

### ISSUE THREAD

**Issue by matt873** [deniscerri/ytdlnis#163]
Though the app has everything one could imagine regards to functionality, and is much more feature-rich compared to Seal, these only two features missing could be very useful, especially the auto-generated captions feature.

![Screenshot_20230527-171514.png](https://github.com/deniscerri/ytdlnis/assets/108935493/a4f5b378-fca7-4098-8a35-007623f183bd)

![Screenshot_20230527-171041_1.png](https://github.com/deniscerri/ytdlnis/assets/108935493/5fcdbabf-580a-4542-b6e1-d9280678909b)

![Screenshot_20230527-171047.png](https://github.com/deniscerri/ytdlnis/assets/108935493/e26fec9b-9bba-4adf-9912-bc783707677f)

**Comment by deniscerri** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/64997243/8ea10d4c-aec6-4a6f-ad6c-29846a764124)
btw the app already supports auto subs, its part of the save subtitles switch

**Comment by matt873** [comment]
So toggling on "save subtitles" switch will auto generate subtitles.

**Comment by deniscerri** [comment]
yes i believe so. It will download normal and auto subs. If it doesnt, let me know

**Comment by matt873** [comment]
It's working perfectly!

**Comment by deniscerri** [comment]
Yes because every item is treated as a separate download. You can go crazy.
I am also working on putting filename template as a playlist option in the bottom so u can put everything in the same format. :)

**Comment by matt873** [comment]
So for saving a video into folder of it's channel name, what prefix would I have to put. I went through this page but could not quite figure out as I am an average user:
https://github.com/yt-dlp/yt-dlp#usage-and-options

**Comment by deniscerri** [comment]
%(extractor)s

**Comment by matt873** [comment]
Wouldn't it be easy to add an option for that in settings so that instead of editing the filename template every time, a set template in settings can be used which one might only need for saving videos into a folder of their channel name? I mean one might need it for only one purpose which is saving videos into the folder of their channel name.

**Comment by teddysulaimanGL** [comment]
> Wouldn't it be easy to add an option for that in settings so that instead of editing the filename template every time…

You have always been able to set the default custom filename, even audio and video custom filename are separated

**Comment by matt873** [comment]
Or I might be not understanding it right. The same can be done to the Filename template you have already given an option for in settings. This means adding a prefix to that will do the same.

**Comment by matt873** [comment]
> > Wouldn't it be easy to add an option for that in settings so that instead of editing the filename template every time…
> 
> You have always been able to set the default custom filename, even audio and video custom filename are separated

I got it now. I was writing the same in the previous comment but saw your comment after posting it. Thank you!
