### ISSUE TITLE
[BUG] auto create download folder, etc

### ISSUE THREAD

**Issue by root-kernelhacker** [deniscerri/ytdlnis#165]
Report a bug in the distribution with the Korean translation added.  

1. Even if the download path is set elsewhere, the YTDLnis folder is created in the download folder of the internal storage space, and audio, commamd, and video folders are created in subfolders.  Even if you change everything in the settings to download to a folder other than the YTDLnis folder, it will be automatically created.  

3. Even after the download completion notification appears, the download progress notification remains for 1 to several seconds and then disappears.  (This is a problem that does not occur in the official release) 

-  Perhaps, the release with the Korean translation applied is a release in which the code is being modified, so when the official release comes out, I report it thinking that the problems will be fixed.

**Comment by root-kernelhacker** [comment]
1. It was confirmed that the folder is created in the built-in storage, not when the YTDLnis app is run independently and downloaded by executing the link, but only when downloaded through YouTube Revenge.

2. Open the YTDLnis app.  When you are viewing the download status, the download progress notification in the top bar disappears quickly, but if you proceed with downloading from YouTube without running the app, the download progress notification disappears 1 to a few seconds after the download completion notification appears in the top bar.

**Comment by deniscerri** [comment]
There's no reason to create issues on dev builds. They are supposed to be buggy because I'm experimenting. Create an issue if it in the release version

**Comment by deniscerri** [comment]
Folder creation will be fixed
