### ISSUE TITLE
Changing download quality of Cancelled, Errored Video

### ISSUE THREAD

**Issue by matt873** [deniscerri/ytdlnis#166]
Changing download quality from cancelled and errored tabs should be possible. I think an action should be added to the video camera button, shown in the screenshot below, which will open the download card upon taping.
![Screenshot_20230601-171104_1.png](https://github.com/deniscerri/ytdlnis/assets/108935493/798305a9-aa68-466d-ab82-5440e57487a6)

**Comment by deniscerri** [comment]
U can do this. Long press the redownload button

**Comment by teddysulaimanGL** [comment]
Like he said, you already can do it. All I can say is before you open a new issue, please recheck or ask if it already exists or not

**Comment by matt873** [comment]
Ah! Any feature I imagine is already there but hidden somewhere and can be triggered by some gesture, long press etc. I think your app needs some comprehensive documentation on how to use it to its full potential on github.

**Comment by matt873** [comment]
> As he said, you already can do it. All I can say is before you open a new issue, please recheck or ask if it already exists or not

I am unable to use telegram and by the way who can realise at first sight that the redownload button can also be used for changing download quality?

**Comment by deniscerri** [comment]
> > As he said, you already can do it. All I can say is before you open a new issue, please recheck or ask if it already exists or not
> 
> I am unable to use telegram and by the way who can realise at first sight that the redownload button can also be used for changing download quality upon long press?

Quick tap of redownload does that.
Long press the user wants more from it. Lol
