### ISSUE TITLE
Menu layout

### ISSUE THREAD

**Issue by AntonDzutstsati** [deniscerri/ytdlnis#17]
Why is there blank space under menu buttons?

![Screenshot_20230107-092650.png](https://user-images.githubusercontent.com/74765004/211132814-372257f0-a90c-4e3e-9732-f0d468572384.png)

**Comment by deniscerri** [comment]
Yeah, weird. Tried to emulate your phone and only yours shows that space but not on my other 3 phones. The problem started when you updated to 1.4.6?

**Comment by deniscerri** [comment]
I think i fixed it now. Please wait for the next release. Thanks for letting me know of this problem :)

**Comment by deniscerri** [comment]
Check out 1.4.9

**Comment by deniscerri** [comment]
@AntonDzutstsati I have noticed you and alot of people creating issues in a russian forum.  Certainly i can answer them, if you can make an issue in github or relay them to me in telegram so i can fix them. I rarely visit that forum and i dont really know russian :)
