### ISSUE TITLE
[FEATURE REQUEST] let us choose audio quality for video download

### ISSUE THREAD

**Issue by aicynide** [deniscerri/ytdlnis#172]
**Is your feature request available in yt-dlp? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by teddysulaimanGL** [comment]
This is already possible. However, you need to install preview (or beta) version, which you can find on Telegram

**Comment by aicynide** [comment]
I mean for video download not audio download. There is video format only for video download not audio format

**Comment by aicynide** [comment]
@teddysulaimanGL

**Comment by teddysulaimanGL** [comment]
I know, I'm not talking about Audio download type. Give the preview APK a try, you can select custom audio stream for video there

**Comment by deniscerri** [comment]
Yes

**Comment by aicynide** [comment]
![Screenshot_20230605-192920_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/97217381/124bf6ff-ae88-4aeb-8b0f-5bbe225f1b31)
I can see video format only

**Comment by deniscerri** [comment]
Click thr format item and update formats. It will show audio formats too

**Comment by aicynide** [comment]
Thank You
