### ISSUE TITLE
Unable to Change Folder Directory

### ISSUE THREAD

**Issue by NitrogenH2O** [deniscerri/ytdlnis#176]
Just as the title says, I'm unable to change Audio, Video, and Custom Command Directory. Although, these may be factors to why it didn't work; regardless, I could still download without changing the directory, that's good.

• I'm using a Custom Rom (Android 12 with R Vendor)
• I have root privileges

Here is the log, via a link:
https://paste.crdroid.net/1pyAT8

**Comment by deniscerri** [comment]
Looks like android can't find the folder picker. It might be a custom ROM issue.

U could backup your settings. Go to your json file and manually put your path and then restore it

**Comment by NitrogenH2O** [comment]
> Looks like android can't find the folder picker. It might be a custom ROM issue.
> 
> U could backup your settings. Go to your json file and manually put your path and then restore it

![Screenshot_20230607-123417_QuickEdit+~2](https://github.com/deniscerri/ytdlnis/assets/120689352/0a4acaaf-8ec9-43df-a8b1-a1d562a66c60)

I believe this must be one of the 3 lines for the download directory (this could either be the Audio, Video, or Terminal Command). Now how should I change it? What do each symbols and numbers represent?

**Comment by deniscerri** [comment]
Just replace the whole thing with a conventional path like /storage/emulated.... It should work i believe

**Comment by NitrogenH2O** [comment]
> Just replace the whole thing with a conventional path like /storage/emulated.... It should work i believe

Worked flawlessly, now I'm able to change directories, thanks!
