### ISSUE TITLE
[BUG] KOR language Error

### ISSUE THREAD

**Issue by root-kernelhacker** [deniscerri/ytdlnis#187]
In version 1.8.2, the Korean I had translated was in a strange Korean language with many translation errors in version 1.8.3.  Should I edit and translate again?  Why is the Korean translation strangely changed?

**Comment by deniscerri** [comment]
Yes someone changed a bunch of languages. It must've been him. Please change them back

**Comment by root-kernelhacker** [comment]
The whole thing is messed up, but can't I reuse the language file from the previous version 1.8.2?

**Comment by deniscerri** [comment]
I'll handle this later

**Comment by root-kernelhacker** [comment]
All Korean translation errors have been corrected.  Please upload the 1.8.3 build with the corrected translation applied.  (Existing translations are abnormal with many serious errors)

**Comment by deniscerri** [comment]
Will send you an apk later or update the release

**Comment by deniscerri** [comment]
Get the apk here

https://devuploads.com/qq07l8eicd1d
https://devuploads.com/xvk4affifff3

**Comment by root-kernelhacker** [comment]
I finished it with a few more tweaks.  Please apply it in future builds.  thank you

**Comment by root-kernelhacker** [comment]
It seems that someone is maliciously changing the translation.  Even in the separately applied build, some modifications were made from my translation.  I translated and corrected it again, but I am concerned that I may ruin the translation again.

**Comment by deniscerri** [comment]
Trolls
