### ISSUE TITLE
Ability to choose the audio codec and audio container for the video download

### ISSUE THREAD

**Issue by dr3amr** [deniscerri/ytdlnis#192]
Currently there is no way to select the audio codec and audio container for a video download. Is this possible through a template command ? I have a specific combo of video and audio given by limitations in formats of car player (H264 + MP4A or MP3 in MP4 container). While selecting resolution and MPEG_4 in MP4 container audio is auto selected.

**Comment by deniscerri** [comment]
https://github.com/deniscerri/ytdlnis/assets/64997243/d8a8c6cc-f229-4276-ad3a-9467b86d7f0f

Refer to this example

**Comment by dr3amr** [comment]
Yeah :) sorry, not sure how I missed that. Was on last version. Long list I guess 👍 Great app by the way.
