### ISSUE TITLE
Settings => Processing => Preferred Format ID => video id + audio id

### ISSUE THREAD

**Issue by dr3amr** [deniscerri/ytdlnis#193]
Can bellow be added ?
Settings => Processing => Preferred Format ID => video id + audio id
Tried different combinations like "id1+id2", "id1/id2", "id1-id2" ... but I think it is coded to only process the video id in respective text box. Even only audio id is not taken into account, thus it is kinda clear now.

**Comment by deniscerri** [comment]
yes its only for video id if its a video type or audio id if its audio type.
How about this

I implement a 2nd preferred format id, for audio
the current one will be for video. Considering one fills in both i might auto-select a video and audio format according to them. What do you think?

**Comment by dr3amr** [comment]
I think the Preferred audio ID will be same as the video one: will auto-select something if nothing is added there, else select whatever user filled. 👍 
Sounds great, was not expecting you to respond this fast :)

**Comment by deniscerri** [comment]
Yes of course it will be a textbox like the usual preferred id.
The new textbox will be used to select the preferred format for audio-type downloads
in video type downloads, it will use video preferred id to get the main video format and the audio preferred id to select an audio format along with it

Now if the audio id is not found, then i wont add anything. So by default if no audio format is connected with the video format, the app will just get the best audio present like usual.

Also btw, if the app wont find an id for video formats it will fallback to preferred video quality (1080, 720, 480 etc etc) and get a similar format to that name.

Also also if that fails, it will select for you the best video format available.

 Might implement this tomorrow. Its not hard to do

**Comment by dr3amr** [comment]
Is it possible in any way to select a profile for the codec, such as for the mpeg4 between baseline and main ? I know, who is still using baseline :)) answer, my old 2015 car. I need to run also an ffmpeg over the videos downloaded to change the default main profile to baseline. But I think this is another ER :)

**Comment by deniscerri** [comment]
Its implemented
