### ISSUE TITLE
MPEG 4 video codec option of selecting profile between "baseline" and "main"

### ISSUE THREAD

**Issue by dr3amr** [deniscerri/ytdlnis#194]
Is it possible in any way to select a profile for the codec, such as for the mpeg4 between baseline and main ? I know, who is still using baseline :)) answer, my old 2015 car. I need to run also an ffmpeg over the videos downloaded to change the default main profile to baseline.

**Comment by deniscerri** [comment]
I think you are better off using a command template for such thing

**Comment by dr3amr** [comment]
Worked with command template using:
-f <mpeg4_video_codec_id>+<audio_codec_id> --ppa "ffmpeg -y -s -c:v libx264 -c:a copy -profile:v baseline" 
This would download the video, using specific video and audio codec, and reencode using ffmpeg changing the mpeg4 profile from default "main" to "baseline".
