### ISSUE TITLE
[BUG] Bugs and confirmation requests

### ISSUE THREAD

**Issue by root-kernelhacker** [deniscerri/ytdlnis#195]
bug.  
If you back up and restore after selecting only the setting items in the backup, the language changes to English.  

Checklist.  
When downloading with YTDLnis from YouTube, etc., before the download card came out, in the past, the card came out after "Please wait a moment".  The message doesn't appear now. Did you intentionally prevent it from appearing as the speed of opening the card improved?  Some of the devices I test are slow, so it takes a while before the download card comes out, so there are many times when I don't know how YTDLnis is running, so it can be much more useful to have a "Please wait" message useful.

**Comment by deniscerri** [comment]
Language restore is not easy to achieve so it might not work on some devices. U need to manually update it after the restore.

Yes the please wait card not showing is a bug. Will fix

**Comment by root-kernelhacker** [comment]
As for the language backup recovery issue, if you check the backup and restore it after the backup, there is no problem, but another problem occurs.  If you restore after backing up, there is a bug in which sound and vibration do not ring even though notifications are working well.

**Comment by root-kernelhacker** [comment]
I'm introducing YTDLnis to my community.  (People who are not satisfied with the existing SEAL, NEWPIPE, PowerTube, etc. are very satisfied with YTDLnis. We are talking about sponsorship so that the project will not be stopped, so we will inform you separately when it is decided ^^)

**Comment by deniscerri** [comment]
"Please wait " card not showing up, now is fixed

**Comment by deniscerri** [comment]
> I'm introducing YTDLnis to my community. (People who are not satisfied with the existing SEAL, NEWPIPE, PowerTube, etc. are very satisfied with YTDLnis. We are talking about sponsorship so that the project will not be stopped, so we will inform you separately when it is decided ^^)

You don't need to do that. I appreciate the gesture, but im doing this as a school project and will continue it if people might consider new features
