### ISSUE TITLE
Download Card Improvement

### ISSUE THREAD

**Issue by matt873** [deniscerri/ytdlnis#197]
The same file types should be grouped instead of randomly dispersed among one another. It would also be better to swap format id for format size for a more clear and more consistent comparison of sizes in the same column.
Although these are just design improvements for the download card and can be implemented by choice if you find it worth it.
Below is the screenshot from PowerTube for an idea of how it will look.
![Screenshot_20230622-192859](https://github.com/deniscerri/ytdlnis/assets/108935493/0fdb9ae6-a7c5-49fa-ae52-33f3cd4d9226)
![Screenshot_20230622-193212](https://github.com/deniscerri/ytdlnis/assets/108935493/af2aaff2-a332-462c-ba27-9f42a34aea52)

**Comment by deniscerri** [comment]
Powertube has them grouped but the filesizes are all over the place. In my app they are sorted by filesize. As for the othrr request, it can be done

**Comment by matt873** [comment]
Yes, they are sorted by file size but it would make the card more neat if WEBM and MPEG-4 formats are grouped into two separate groups both containing the formats in order, i.e., 1080, 720, 480, etc. Just my suggestion.

**Comment by deniscerri** [comment]
Will consider adding different preferences for format sorting
For now im thinking
- size
- id
- container type

**Comment by matt873** [comment]
> Will consider adding different preferences for format sorting For now I'm thinking
> 
> * size
> * id
> * container type

Sounds excellent. Formats arranged into their corresponding containers in ascending or descending order of resolution/size would be ideal. When implementing this, I want you to take a quick peek at the PowerTube download card to get a general sense of how it will work.

**Comment by deniscerri** [comment]
If you haven't noticed my format card is influenced by powertube. 
Yes the sorting by container will have the sub-groups sorted by filesize ofc

**Comment by deniscerri** [comment]
The feature is implemented. Its out on telegram

**Comment by matt873** [comment]
Swapping the position of format sizes with format ID would have been good. What do you think of it? Was it not implemented intentionally or you forgot?

**Comment by deniscerri** [comment]
Wdym swapping?

**Comment by matt873** [comment]
> Wdym swapping?

I think it will make video sizes in a single column on the right for easy comparison of sizes. It just feels easy on easy as is the case with Powertube. Also, format ID should naturally be with container type and video resolution which all is technical info about the video.

**Comment by deniscerri** [comment]
Oh you are right. Yes i had forgotten

**Comment by matt873** [comment]
Is it possible to get "file already downloaded" thing in download card?

**Comment by deniscerri** [comment]
Too many variables to check. The app already checks if u have the same download in the download queue tho
