### ISSUE TITLE
[KOR LANGUAGE FINAL FIX]

### ISSUE THREAD

**Issue by root-kernelhacker** [deniscerri/ytdlnis#198]
The Korean translation was completely 100% complete, including error checking.  (June 23, 2023) 

Someone keeps ruining the translation, but I did my best to normalize it.  

Even if it's cumbersome, please build with a revised translation only once.  (All you need is the arm64-v build)

please......

Thank you !

**Comment by deniscerri** [comment]
Will send you an apk later today

**Comment by root-kernelhacker** [comment]
Thank you ! Thank you so much !

**Comment by deniscerri** [comment]
https://devuploads.com/12obvm5601op
https://devuploads.com/eljtpljpjpxr

**Comment by deniscerri** [comment]
https://devuploads.com/5yqjwthb8mzd
https://devuploads.com/gf63kwkqxv95

**Comment by root-kernelhacker** [comment]
Translation worked perfectly.  thank you  It's a beta version, so I'll keep testing it.
