### ISSUE TITLE
[FEATURE REQUEST]: share action customization 

### ISSUE THREAD

**Issue by ThatOneCalculator** [deniscerri/ytdlnis#202]
The ability to do basic customization for share actions would be great -- ESPECIALLY the option to disable the "Terminal" option in the share action sheet. I find myself often clicking the "Terminal" option accidentally, since it has the same icon and often appears first in the list due to alphabetical order. I don't think many people use the Terminal option, especially not when they want to download something quickly.

**Comment by deniscerri** [comment]
will see if i can implement it

**Comment by deniscerri** [comment]
It has been implemented. Look forward to the latest release or get the beta on telegram
