### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by xyen8180** [deniscerri/ytdlnis#206]
**Is your feature request available in yt-dlp? Please describe.**
when i download react playlist since it's new i want to have see it exact order in playlist but when i download it it's just mixed up

**Describe the solution you'd like**
i want playlist index at the start of the filename.
example  1-tutorial_about_react.mp4
where 1 is number of index of video in playlist

**Comment by teddysulaimanGL** [comment]
> where 1 is number of index of video in playlist

Find "Filename template" preference and add "%(playlist_index)s-" at the beginning of it. And please label this issue as question as this isn't an actual issue

**Comment by deniscerri** [comment]
Normal filename template wont work unless he is using quick download.

**Comment by xyen8180** [comment]
i already tried %(playlist_index)s - %(title)s this one. not working i selected all the videos of playlist press download button i had option to save bunch of things like video or audio, quality and just beside quality there was edit icon for filename template i put this string there as well as setting in download section it's still not working

**Comment by deniscerri** [comment]
Yes. What u gotta do is enable quick download mode and then paste the link again in the app. It will open the normal download card. There use filename template. It will work
