### ISSUE TITLE
[BUG] Re-download and Folder permission 

### ISSUE THREAD

**Issue by jewelsonn** [deniscerri/ytdlnis#207]
**Describe the bug**
Every video I download in custom folder doesn't get saved after downloading. I have to Re-download it which causes it not to apply sponsor block or cut i have made. It just download whole video without the settings on redownload. Folder permission aren't applied.

**To Reproduce**
Save your videos in custom folder in the root of your internal memory of your phone. Apply settings before downloading and if and when it fails redownload it. 

**Expected behavior**
Download video in the custom folder with the settings applied. Expect to apply same setting on redownload or at least expect a prompt to apply last settings that were applied to it or not.

**Screenshots / Video Recording**
N/A

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.6.3-arm64-v8a
 - Other Device Information: Realme Narzo 20 Pro (RMX2161)

**Additional context**
Add End/Credits sponsor block option or name accordingly

**Comment by deniscerri** [comment]
wdym custom folder? You are adding an output command in custom command mode?

**Comment by deniscerri** [comment]
@jewelsonn A history item doesnt have full information about how its download event occurred. It only has general information. So you will have to redo your settings on redownload. When trying to redownload, long press the button and the download card will show up and u can do your thing there. Or you can swipe to the right of the card, same thing.

**Comment by jewelsonn** [comment]
> wdym custom folder? You are adding an output command in custom command mode?

Sorry for late reply, I was pretty busy few weeks, The custom folder is any new folder you create within your system and select that folder to save downloaded videos to. Like I created "Music And Videos" folder which is a custom/different folder than default folder. 

Item download setting history can easily be saved in localStorage or app storage just like you save the history of items downloaded to appear in the list for history.

**Comment by deniscerri** [comment]
Get the latest beta on telegram to fix the thing not getting downloaded 1.6.3.8

As per the 2nd part I'll note it down to save downloads info in history item
