### ISSUE TITLE
[BUG] Sharing link to app doesn't show flyout download window

### ISSUE THREAD

**Issue by some1onLSD** [deniscerri/ytdlnis#208]
**Describe the bug**
When you share a youtube link to the app so you can download it the download window doesn't appear.

**(please complete the following information):**
 - Android Version: 13
 - App Version: 1.6.3
 - Other Device Information: none

**Additional context**
I think adding permission to the app of "display over other apps" or "picture in picture" like mx player does may help fix the problem.

**Comment by deniscerri** [comment]
Can you install the latest beta on telegram? And see if it works. Thx

**Comment by some1onLSD** [comment]
Hello, just downloaded the v1.6.3.3 beta from telegram and it actually works now, but there is an issue when sharing link from youtube the video information shows up but when clicking download button on revanced (after choosing ytdlnis as the download app) it only shows please wait, and it stays like that without loading the video information or anything. 
Before in the v1.6.3 nothing showed up in both scenarios.

**Comment by teddysulaimanGL** [comment]
Most likely extraction failure. Try going to Settings -> Updating -> Install new version of yt-dlp

**Comment by teddysulaimanGL** [comment]
It would be nice if you provide any more details on Telegram group. So it would be easier for me to assist you

**Comment by some1onLSD** [comment]
hello, I'm using the latest version of yt-dlp, as I said before when sharing link or pasting the link in the app, the video information shows up and I can download the video. it's just when using the download option in revanced that doesn't work (I have selected YTDLnis as the download app in revanced settings). (I get a window pop up saying "please wait..."  and it stays like that)

**Comment by teddysulaimanGL** [comment]
Um, this is very tough to figure out. Can you send the screen recording of it? This way, we can see it better

**Comment by deniscerri** [comment]
Yes i need more context

**Comment by soymadip** [comment]
> Yes i need more context

Oh, @deniscerri lately it's happening to me too, when I am pressing download button from revanced extended, the overlay is appearing but even after 1 minute, download card is not popping up...

@some1onLSD are you saying this?

**Comment by some1onLSD** [comment]
Here is a link for the video: [Drive](https://drive.google.com/file/d/1EnJ7v4Zq9IL9YBmmdp3yNn_VeLXudU54/view?usp=drivesdk) 

I couldn't upload the video on github  I don't know why

**Comment by deniscerri** [comment]
This could very well be a revanced issue. Perhaps

Because rhe normal share sheet works ok. I suggest making an issue at them. I use rvx and i dont have this issue yet so i doubt there is anything wrong with the app because it worked before this latest patch

**Comment by JimZiii** [comment]
I noticed the same issue today but on my end it does load, it just takes forever, so try leaving it to see if it eventually pops up. It also only happens on some videos sometimes, so the videos that kept taking forever to load earlier now loads normally.

But yea, this is probably something for revanced to look at

**Comment by deniscerri** [comment]
@JimZiii perhaps the piped instance is overloaded. Try changing the piped instance in the app

**Comment by JimZiii** [comment]
Might have been it, because it's been working normally since the day after.
Just confused me that it only happened using the revanced download button, not when i clicked share and manually picked YTDLnis

**Comment by deniscerri** [comment]
Are you having any more issues with this?

**Comment by some1onLSD** [comment]
Hello, I think it was just a revanced issue, I no longer have issues with it. thanks a lot for your help
