### ISSUE TITLE
The "author" box doesn't work on odysee

### ISSUE THREAD

**Issue by JimZiii** [deniscerri/ytdlnis#212]
Not sure if it's a bug so i used a blank template.

On youtube you're able to use the `uploader` metadata tag in your filename or have it place the file in a folder named after the `uploader` tag. The app also puts the id from that tag (the channel name) in the "author" box in the download window, so you're always able to change it on the fly if it's empty or you just want it to say something else.

Problem is that none of this works on odysee. I know it's not able to find the `uploader` tag on odysee, so the "author" box always starts empty. But even if i type something in the "author" box, it always shows up as NA in the filename or folder i use the `uploader` tag for.

I'd get it if it only used the tag id in the filename, but on youtube whatever you change the "author" box to takes precedence over the original tag id. So why isn't this happening on odysee?

**Comment by teddysulaimanGL** [comment]
The solution is to not use `%(uploader)s` in your output (filename) template if you want to use custom author

**Comment by deniscerri** [comment]
If you have knowledge about a yt-dlp command that fixes it, please provide it

**Comment by teddysulaimanGL** [comment]
Uh… first of all, I need to know if you're using custom command or normal (GUI) Audio/Video download

**Comment by deniscerri** [comment]
If he is using author box it might be normal mode and the app already puts

--replace-in-metadata for uploader

**Comment by deniscerri** [comment]
@Fish25op so did you resolve it?

**Comment by deniscerri** [comment]
This appears to be an yt-dlp issue. They need to fix their extractor to support uploader metadata. The app tries to replace the uploader text to the one given but since there is no uploader, it doesnt do anything.

I can't just put the author name to the filename because of filename templates which are custom on different users. You will have to wait for yt-dlp to fix this.

**Comment by JimZiii** [comment]
Is this something they're aware of and working on?

I don't really know that much about ytdlp and implementing it in an android app, but wouldn't it be possible to use the `%(uploader|Unknown)s` line from this as a temporary workaround
---
6. Default: A literal default value can be specified for when the field is empty using a `|` separator. This overrides `--output-na-placeholder`. E.g. `%(uploader|Unknown)s`
---
I can't code but wouldn't it be possible to push the uploader metadata to the author box, like it currently is, but then take whatever text is in the author box when you click download and use that in `%(uploader|Unknown)s` where it says unknown.
Wouldn't that work, or am i way off

**Comment by deniscerri** [comment]
Yes your suggestion worked. It has been implemented
