### ISSUE TITLE
[BUG] Twitter is broken

### ISSUE THREAD

**Issue by nonetrix** [deniscerri/ytdlnis#213]
**Describe the bug**
Twitter downloads are broken, and as a result you cannot download Twitter videos

**To Reproduce**
1. Click share
2. Select Ytdlnis
3. Attempt to download

**Expected behavior**
The video downloads without any issues

**Screenshots / Video Recording**
![Screenshot_20230714-120910~2](https://github.com/deniscerri/ytdlnis/assets/45698918/7a2d0b49-94f4-4fad-9265-6a28069b30db)
![Screenshot_20230714-120934~2](https://github.com/deniscerri/ytdlnis/assets/45698918/9e6e383e-9f8f-4968-8580-97367fe2ce07)

**(please complete the following information):**
 - Android Version: CalyxOS 4.11.0 Android version 13 with the July 5, 2023 security update
 - App Version: 1.6.3
 - Other Device Information: Google Pixel 6a

**Additional context**
To resolve this, I think the only needed change is to update the yt-dlp version

**Comment by deniscerri** [comment]
Please provide the twitter link

**Comment by nonetrix** [comment]
I can't find the original video that I used, however this one also has the same issue. However, it appears to happen with any video anyway so anything should work
https://twitter.com/JP_GHIBLI/status/1679823054032060416?s=20

**Comment by deniscerri** [comment]
Please update yt-dlp in the settings. I cant reproduce this issue
![image](https://github.com/deniscerri/ytdlnis/assets/64997243/7c3e9642-e50f-4b68-9631-f32daacd8e76)

**Comment by nonetrix** [comment]
That fixed it, however the auto update despite being enabled never triggered for some reason despite it being over a month with this issue. Perhaps the auto update is broken? Maybe it would be cool to see it automatically check for a update when there is a error if auto update is enabled

**Comment by deniscerri** [comment]
auto update is only for app updates. It checks as soon as the app starts up
The reason the app doesnt update yt-dlp is because you might have an active download on or perhaps yt-dlp is updating and you happen to queue a download and it doesnt do anything. 

I will find a way to do it when its not intrusive. For the time being, just keep an eye on it when u have issues.

**Comment by nonetrix** [comment]
Maybe pin this as a example or something like it to avoid duplicate issues

**Comment by deniscerri** [comment]
Ill leave a note for people trying to create an issue
