### ISSUE TITLE
[FEATURE REQUEST] play downloaded videos within the app

### ISSUE THREAD

**Issue by Dabbit-Chan** [deniscerri/ytdlnis#216]
**Is your feature request available in yt-dlp? Please describe.**
No, it's not about yt-dlp

**Describe the solution you'd like**
I'd like to play downloaded videos or audio directly in the app, that way I don't have to switch to another app to watch it, which is too much of a hassle. Then, if possible, I hope to add the ability to play in the background, thank you.

**Describe alternatives you've considered**

**Additional context**

**Comment by deniscerri** [comment]
Well the reason i dont want to go into that rabbit hole is because people will then ask for improvements in the player, which the app will never reach the same level such as vlc or others. So its pointless. Just open vlc
