### ISSUE TITLE
[BUG] issue with changing download location in latest beta

### ISSUE THREAD

**Issue by JimZiii** [deniscerri/ytdlnis#218]
**Describe the bug**
This is only noticable when i use the filename template to place videos in a folder named after the author.
If i change download folder at all, even if i change it back, every single download will create a new folder named after the author instead of putting all of the files in a single folder named after the author like it did in 1.6.3.

After looking at the data in backup files i noticed that the pathing is different after changing it.

"/storage/emulated/0/Download/YTDLnis/Video"

Same location after change
"content://com.android.externalstorage.documents/tree/primary%3ADownload%2FYTDLnis%2FVideo"

Editing the backup file to the old pathing and restoring it works as a temporary workaround

**Comment by teddysulaimanGL** [comment]
Don't open an issue if you're using beta. Beta version is supposed to be unstable, after all

**Comment by JimZiii** [comment]
I know, but beta or not, a bug or issue cant get fixed unless its discovered and pointed out.
And I'm thinking it might be related to what he implemented in the last beta version, on my request.

**Comment by teddysulaimanGL** [comment]
He said it himself to not open an issue if you're using beta. Instead, point it out to the Telegram group

**Comment by JimZiii** [comment]
Ok my bad, I've missed that

**Comment by deniscerri** [comment]
So it makes a new folder like Author(1) instead of putting stuff in the Author folder?

**Comment by JimZiii** [comment]
Exactly. But on 1.6.3 the pathing is the same after changing download location but it still puts the files in the same folder, it's not until i update to the beta that it starts creating new folders.

Haven't tried the earlier beta versions so i can't say for sure it started in 1.6.3.8

**Comment by deniscerri** [comment]
This will be fixed. The reason for this change was due to custom filename templates with multiple subfolders not being created properly.

**Comment by deniscerri** [comment]
check today's beta
