### ISSUE TITLE
[BUG]Unable to Download:File Name Too Long

### ISSUE THREAD

**Issue by roflsunriz** [deniscerri/ytdlnis#219]
**Describe the bug**
The file name was too long so I couldn't download. Please make a function that make its name automatically shortner.

**To Reproduce**
For example, try download these links:
https://youtu.be/-FrO4Ws4a2A
https://youtu.be/OEzshXTQPiE
https://youtu.be/XB_Hi5MuShk

**Expected behavior**
Automatically cut title off and make it shorter and downloads

**Screenshots / Video Recording**
![Screenshot_20230721-103354](https://github.com/deniscerri/ytdlnis/assets/8847851/96d4d0c9-b08d-435f-938c-0b78c58c974d)
![Screenshot_20230721-103405](https://github.com/deniscerri/ytdlnis/assets/8847851/4b6ce0cd-1a23-4ad6-891a-51b4052d3634)

**(please complete the following information):**
 - Android Version: 13
 - App Version:1.6.3
 - Other Device Information:Google Pixel 6a

**Additional context**

**Comment by teddysulaimanGL** [comment]
It's not the app's bug/issue. Read this for the fix https://github.com/yt-dlp/yt-dlp/wiki/FAQ#file-name-too-long

**Comment by roflsunriz** [comment]
I have forgotten I could edit download title
