### ISSUE TITLE
Option to Not Blur NSFW Videos in Incognito

### ISSUE THREAD

**Issue by rjm831** [deniscerri/ytdlnis#222]
Title sums it up.  Don't know if this is possible using Incognito but thought I'd ask.  Just discovered the app and still experimenting with it, but its a fantastic development.  Thank you for the work!.
PS Referring to YouTube vid's.

**Comment by deniscerri** [comment]
wdym blur? The thumbnails on the result cards are blurred when you turn on incognito but in normal mode they arent? Pretty sure that doesn't happen. Let me know more details please

**Comment by rjm831** [comment]
Its not a problem, more of a pain, and was hoping to unblur the search results somehow so I  thought it would be an appropriate Feature Request.

**Comment by deniscerri** [comment]
Can you dm me some links i can test out on telegram? I think yt-dlp itself blurs them because the app doesn't tamper with thumbnail blur.
