### ISSUE TITLE
[FEATURE REQUEST] download now button for videos in queue

### ISSUE THREAD

**Issue by Wjxfi** [deniscerri/ytdlnis#227]
**Describe the solution you'd like**
Select a video in the queue. Click on the three dots on the top right. there please make a button "download now". Also, if you want, you can, when you click on a video in the queue near the remove button, add a download now button.

**Additional context**
Situation in which this is needed: downloading a large playlist. I found a cool video that I want to download and watch right now. Select it as "download now". That would be nice. Now I have to wait for the huge playlist to finish downloading, and only then proceed for this new video. feeling some resentment

**Comment by deniscerri** [comment]
Interesting idea. Noted

**Comment by deniscerri** [comment]
It has been implemented. You can highligh an item and if its not the first one, it will show the arrow up button at the top. Press it and it will put the download at the top of the queue. If the item is scheduled, it will clear the timer and start immediately. If not it will stay at the top of the queue waiting for the worker to grab it when its time.
