### ISSUE TITLE
Latest release contains non-free libraries

### ISSUE THREAD

**Issue by IzzySoft** [deniscerri/ytdlnis#231]
Looks like somehow GMS sneaked into your builds. Could you please check and get them out again? Meanwhile I'll have to apply the `NonFreeDep` anti-feature to your app until solved.

Fingers crossed it will be easy game for you!

**Comment by deniscerri** [comment]
I updated the current libraries to the newest version :/ 
Its not like i want to use GMS

**Comment by IzzySoft** [comment]
> Its not like i want to use GMS

I didn't think you would – hence the note that it **sneaked in** (i.e. "behind your back"). `gradle :app:dependencies` might help you find the culprit. I guess something needs some `exclude_group` or the like in `build.gradle` – but I'm no Android dev, so I cannot really tell what and how.

**Comment by deniscerri** [comment]
Will release a new build this weekend

**Comment by IzzySoft** [comment]
Be welcome to give me a ping when it's there so I can check ASAP. Thanks!

**Comment by deniscerri** [comment]
[Try the new release](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.5)

**Comment by IzzySoft** [comment]
Err…  APKs are > 40 MB, with the size limit in my repo being 30 MB per app… Well, looks like we've made an exception there as the previous version was as big as well. OK: my library scanner seems to be happy: looks clean now, so I've pulled the update in, thanks!
