### ISSUE TITLE
[FEATURE REQUEST] lyrics for audio

### ISSUE THREAD

**Issue by venkat2305** [deniscerri/ytdlnis#232]
Can you implement a feature that converts captions from videos into lyrics and embeds them into audio files during the downloading process? This functionality would be particularly beneficial for podcasts, as it would enable the incorporation of spoken content into the audio files for better accessibility and comprehension.

**Comment by deniscerri** [comment]
https://github.com/yt-dlp/yt-dlp/issues/5635

**Comment by venkat2305** [comment]
Is it not possible to do it within the app itself using ffmpeg or similar libraries?

**Comment by 0xKernelEclipse** [comment]
https://github.com/deniscerri/ytdlnis/issues/991
