### ISSUE TITLE
[FEATURE REQUEST] AV1 video option

### ISSUE THREAD

**Issue by ModiGrey** [deniscerri/ytdlnis#233]
**Is your feature request available in yt-dlp? Please describe.**
I noticed the lack of av1 codec option for resolutions lower than 1440p, while the option is available in yt-dlp for all resolutions.

**Describe the solution you'd like**
The availability of av1 as an option beside vp9 and avc1 as, according to my testing, it provided a slightly better quality than both avc1 and vp9 for a lower file size even for 1080p and lower resolutions.

**Describe alternatives you've considered**
I did consider, and I did achieve to download 1080p/av1 using the terminal option in the app by using the command ``--list-formats`` and choosing av1 option.

**Additional context**
N/A

**Comment by deniscerri** [comment]
If you prefer ytdlp formats. Go to updating settings and choose ytdlp. I'm assuming you were feeding the app a YouTube video and it would fetch from piped api

**Comment by ModiGrey** [comment]
This was indeed what happened. I don't know how I didn't notice the option to change format source in settings. My fault.
Anyway, thanks for responding.
