### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by oop7** [deniscerri/ytdlnis#234]
Add Material you

**Comment by deniscerri** [comment]
Go to general settings and change color accent to material you

**Comment by oop7** [comment]
I mean Themed icons 
For example:
![Screenshot_20230803-131445_Pixel_Launcher~2.png](https://github.com/deniscerri/ytdlnis/assets/110548351/a59bd350-2652-4df6-a0c4-f58f079b37fc)

**Comment by teddysulaimanGL** [comment]
What Android version you're in?

**Comment by oop7** [comment]
Android 12

**Comment by deniscerri** [comment]
Monochrome icons are for Android 13

**Comment by teddysulaimanGL** [comment]
Yeah, you're probably using icon pack

**Comment by oop7** [comment]
I'm not using icon pack 

All applications are the same except for YTDLnis

![Screenshot_20230803-133549_Pixel_Launcher.png](https://github.com/deniscerri/ytdlnis/assets/110548351/86e0a1a6-900b-4c23-b7da-256f45c15229)

**Comment by deniscerri** [comment]
How do you have monochrome icons?

**Comment by oop7** [comment]
enable this
![Screenshot_20230803-152235_Wallpaper_&_style.png](https://github.com/deniscerri/ytdlnis/assets/110548351/a29a31a2-5ce0-469f-aea9-beb2cb403350)

**Comment by deniscerri** [comment]
Closing this as it was fixed in the beta
