### ISSUE TITLE
[FEATURE REQUEST] Receive URL from Share Button to Start Download Videos

### ISSUE THREAD

**Issue by roflsunriz** [deniscerri/ytdlnis#235]
**Problem**
I'm frustrated with copy and paste urls for YTDLnis from other apps. I can search videos in YTDLnis itself but nah. Usually I'm using other apps to find videos.

___

**Solution**
It is great thing to start download videos from share menu/button and receive urls and hand over urls to YTDLnis. This feature can Simplify the download process and no need to copy and paste urls anymore.

___

**Alternatives**
Currently, none.

___

**Additional context**
For example, MX Player.
![Screenshot_20230805-121659](https://github.com/deniscerri/ytdlnis/assets/8847851/520e07d5-89f9-4436-bb7e-506490158ec9)
![Screenshot_20230805-121708](https://github.com/deniscerri/ytdlnis/assets/8847851/bb42a237-2887-4066-85f0-7e304b3b37f8)
![Screenshot_20230805-121651](https://github.com/deniscerri/ytdlnis/assets/8847851/2186d72b-57d2-4a7a-bbc2-96a85fe7542f)
Sorry this is japanese but from share menu YTDLnis should appear here and pass url to YTDLnis.
I can still download videos through ADM (Advanced Download Manager)'s share button.

**Comment by teddysulaimanGL** [comment]
What the… have you even checked first? It's already possible

**Comment by roflsunriz** [comment]
In Youtube app, YTDLnis will appear but in MX Player, no.

**Comment by teddysulaimanGL** [comment]
Then don't, what do you expect? It's because it's not sharing the link. Instead, it's sharing the file

**Comment by roflsunriz** [comment]
Then nothing I can expect from this issue?

**Comment by teddysulaimanGL** [comment]
MX Player share button behaviour is different than than YouTube's. It's just how it works

**Comment by roflsunriz** [comment]
uh, ok. whatever. 😭
