### ISSUE TITLE
[LANGUAGE UPDATE] 1.6.4 version KOR FIX !

### ISSUE THREAD

**Issue by root-kernelhacker** [deniscerri/ytdlnis#236]
The Korean translation of version 1.6.4 was not enough, so the translation was finally completed!.

**Comment by deniscerri** [comment]
The app is undergoing heavy changes so i wont be able to give you a quick build. I will tell you when i find the time

**Comment by deniscerri** [comment]
[Try the new release](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.5)
