### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by TeenagedLime3** [deniscerri/ytdlnis#238]
**Is your feature request available in yt-dlp? Please describe.**
Yes, using --extractor-args "youtube:player_client=default,ios" or --extractor-args "youtube:player_client=all"

**Describe the solution you'd like**
1080P Enhanced Bitrate format from YouTube (i think its normally format id 616). See images below for possible solution although i haven't really thought about how it could be implemented.

**Describe alternatives you've considered**
I'm currently using a custom command but it means i can't use the other options. Since it alters the formats available, using the add extra commands option doesn't work

**Additional context**
![Screenshot_2023-08-06-14-26-15-108_com.deniscerri.ytdl-edit.jpg](https://github.com/deniscerri/ytdlnis/assets/88453457/06a106b7-8eef-4a8d-9552-ae9f7052ef04)

![Screenshot_2023-08-06-14-27-06-546_com.deniscerri.ytdl-edit.jpg](https://github.com/deniscerri/ytdlnis/assets/88453457/514db01e-fc3a-4b56-8fb0-8d748fcced0b)

**Comment by deniscerri** [comment]
Just go to the settings, updating
 and switch yt-dlp format source and refresh the result item again. It should show up.
