### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by psmoros** [deniscerri/ytdlnis#239]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@blackbeard666) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by deniscerri** [comment]
Hi. I hadn't added a security file because im only working on the most current version and every version in the past is immediately outdated. 

You can create an issue in the repository so we can keep things clear for everyone. No need for private emails.

**Comment by deniscerri** [comment]
created
