### ISSUE TITLE
[FEATURE REQUEST] Keep edited title when switching between video/audio tabs

### ISSUE THREAD

**Issue by MrBKA95** [deniscerri/ytdlnis#241]
If you edit a title before downloading a video/audio if you switch between the video and audio tab the title just resets to default which is frustrating. 

Would you be able to add the option to keep the edited title when switching between tabs.

https://github.com/deniscerri/ytdlnis/assets/105092892/28079446-f292-4c70-ae8f-ac7dd1a8cbdd

**Comment by deniscerri** [comment]
title and authors are now synced.

**Comment by deniscerri** [comment]
[1.6.6.2](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.6.2-beta)
