### ISSUE TITLE
[BUG]If a large number of videos are downloaded at the same time, many videos to be downloaded will not enter running.

### ISSUE THREAD

**Issue by Calvaria-U** [deniscerri/ytdlnis#244]
At the same time, I downloaded a lot of youtube videos. However, during the work of these tasks, many tasks will not enter the running queue, which means that they will not start downloading unless they rejoin the queue through links, but this is too troublesome and needs to be done again for each task.

Can Redownload be added to tasks in the IN QUEUE, just like in the Errored queue?This helped me a lot.Thanks.

android:9
app-version:2023.07.06(1.6.4[arm64])

**Comment by deniscerri** [comment]
wdym they will not enter the running queue? They stay in queued indefinitely?
can you reproduce this with a video recording

**Comment by Calvaria-U** [comment]
> wdym they will not enter the running queue? They stay in queued indefinitely? can you reproduce this with a video recording
![LG V30-2023-08-18-02-04-29-2720](https://github.com/deniscerri/ytdlnis/assets/142531173/c9874184-7590-495b-81ba-70a690215982)
![LG V30-2023-08-18-02-04-40-7910](https://github.com/deniscerri/ytdlnis/assets/142531173/0351fad9-61c6-4118-b30d-46e260e467ea)
As you can see, they won't start.

**Comment by Calvaria-U** [comment]
They may need to stay in the queue until I delete them, because even if I add the link again, a new task will be generated without overwriting the original task.

**Comment by deniscerri** [comment]
does no download start at all or do some start and the rest just stop

**Comment by deniscerri** [comment]
lets talk in telegram

**Comment by deniscerri** [comment]
Closing this as it was fixed in the beta
