### ISSUE TITLE
[BUG] Please fix cut menu bug which forces you to change start and end time in order to enable feature

### ISSUE THREAD

**Issue by MrBKA95** [deniscerri/ytdlnis#246]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue:

Yes I am using the latest version of yt-dlp

https://github.com/deniscerri/ytdlnis/assets/105092892/b9c152f7-63fb-44ec-b2ac-3ddfdff55e80

**Describe the bug**
When you select the cut feature on video & audio you have to change the start and the end time in order for the cut feature to work. Majority of the time I only need to cut one end of the video/audio so really it would be ideal if you can just edit the start or end only and the cut feature is enabled.

**To Reproduce**
In the cut feature menu before download

**(please complete the following information):**
 - Android Version: 13
 - App Version:  YTDLnis 1.6.4 arm64-v8a
 - Other Device Information: Samsung Galaxy S21

**Comment by deniscerri** [comment]
Noted

**Comment by deniscerri** [comment]
This has been fixed. Please wait for the next release

**Comment by MrBKA95** [comment]
> This has been fixed. Please wait for the next release

Brilliant thanks for the quick response.
