### ISSUE TITLE
[FEATURE REQUEST] Translated title

### ISSUE THREAD

**Issue by sekedus** [deniscerri/ytdlnis#247]
Download video with `translated title`.

Example: [https://youtube.com/watch?v=5dmiKojDJA8](https://youtube.com/watch?v=5dmiKojDJA8) 

tried [alt_title](https://github.com/yt-dlp/yt-dlp#output-template), but it doesn't work

![Screenshot_20230819-082734](https://github.com/deniscerri/ytdlnis/assets/25115799/4ef4966b-f4f2-4e42-8e03-968947d02c25)

![Screenshot_20230819-083050](https://github.com/deniscerri/ytdlnis/assets/25115799/eb0dd4e4-7742-4ce4-a798-becc3a52b7ee)

![Screenshot_20230819-083103](https://github.com/deniscerri/ytdlnis/assets/25115799/11bbf4c2-4068-4fce-b612-5f65475aa6a0)

**Comment by deniscerri** [comment]
Leave the title empty and it will resort to your template

**Comment by sekedus** [comment]
Like this ?ㅤ👇

![Screenshot_20230819-184944](https://github.com/deniscerri/ytdlnis/assets/25115799/992feac9-8f0e-46d7-80ab-dc8d71540333)

**Comment by deniscerri** [comment]
yes

**Comment by sekedus** [comment]
Back to original title

![Screenshot_20230819-185001](https://github.com/deniscerri/ytdlnis/assets/25115799/dd5c0f2f-3721-4b51-a2be-2db298768dc5)

**Comment by deniscerri** [comment]
look at the actual file. The history item is irrelevant

**Comment by sekedus** [comment]
Does not work

![Screenshot_20230819-192138](https://github.com/deniscerri/ytdlnis/assets/25115799/cdaf07ab-d3f3-45b1-bbff-97cb5ad9cba8)

**Comment by deniscerri** [comment]
ok. I will fix it

**Comment by sekedus** [comment]
> ok. I will fix it

Please add option to use translated title in settings or autofill title with translated title instead by leaving title field blank.

**Comment by deniscerri** [comment]
The translated title cannot be added as i havent found a way to get it using yt-dlp. Also i have allowed the app to respect your filename template if the title is empty.

If you can produce this in desktop or any other. please give me the command. Thanks

**Comment by deniscerri** [comment]
A workaround is this
write --extractor-args "youtube:lang=en" as an extra command. Leave the title empty of course

**Comment by deniscerri** [comment]
no, enable extra commands in the settings
and use normal audio/video tab and just add the command in the extra tab button at the bottom

**Comment by deniscerri** [comment]
@sekedus simply make a command template with that and set it as extra command. It will always get included in the configuration for every download

**Comment by sekedus** [comment]
> simply make a command template with that and set it as extra command

Thank's.

Hopefully, in the next update, I no longer need to empty the title to get translated title.

**Comment by deniscerri** [comment]
U can turn on quick download, it will have an empty title

**Comment by sekedus** [comment]
> U can turn on quick download, it will have an empty title

if `quick download` is enabled, downloaded video is blank (black) with audio & subtitles.

**Comment by deniscerri** [comment]
dm me in telegram so i can know more.

**Comment by sekedus** [comment]
Sorry, it's an error because the default video player can't play videos with output settings:
- format: mp4
- quality: 360p 

Now, videos can be played with VLC.

**Comment by qzmtch** [comment]
> [@sekedus](https://github.com/sekedus) simply make a command template with that and set it as extra command. It will always get included in the configuration for every download

--extractor-args "youtube:lang=en"
 This doesn't work for other sites, like Pornhub (or some others). It always downloads the video title with a translation instead of the original. Is there a way to manually set it to English?
Is the system language added to the config file?
