### ISSUE TITLE
[BUG] Cut feature not working when downloading video/audio

### ISSUE THREAD

**Issue by MrBKA95** [deniscerri/ytdlnis#252]
Yes i'm using the latest yt-dlp

**Describe the bug**
After using the cut feature in the app when you press download the download just freezes. You're unable to pause and resume the download it's just frozen. For some reason github isn't uploading my video so here is a link (only available for 2 days)

https://streamable.com/bxsog9

**To Reproduce**
Use the cut feature in the app then press download.

**(please complete the following information):**
 - Android Version: 13
 - App Version: 1.6.5 (tried both arm64-v8a and universal apk)
 - Other Device Information: Samsung Galaxy S21

**Comment by deniscerri** [comment]
Does the file download on the end or does it stay frozen always?

I tried your config. Yes it took long and has no progress, this is known because the progress was passed to ffmpeg and we dont ovserve it yet.

**Comment by MrBKA95** [comment]
The download stays frozen. I'm unable to pause or delete the download so I had to force stop the app to remove download.

**Comment by deniscerri** [comment]
Never mind that. Does the file itself download? Since that can be looked at

Do you see it in the .CACHE folder growing?

**Comment by MrBKA95** [comment]
Yes now you pointed me to the cache folder I did see that the file did grow and eventually downloaded. So I guess it's a very slow process depending on size of file - is that something I need to bear with for future downloads?

What confused me was nothing was happening to the download bar in the app or the download notification

**Comment by deniscerri** [comment]
Yes this is a limitation is the YouTubedl android library. It doesn't show progress while you were cutting cuz its transferred to another tool ffmpeg.


Also yes cut downloads take a bit depending on circumstance. Sometimes the app has to re encode the file and that is expensive. You have to live with it. But the progress thing could be fixed in the future

**Comment by MrBKA95** [comment]
Ok thanks for the clarification. In the future I will download the full file and use an external app to cut files to speed up the process.
