### ISSUE TITLE
[BUG] Video downloaded from TikTok are in 
.bin format

### ISSUE THREAD

**Issue by TheHighGroundWins** [deniscerri/ytdlnis#253]
**Describe the bug**
videos downloaded from tiktok are in .bin format

**To Reproduce**
Download a video from tiktok and the result will have the filename extension .unknown_video.bin

**Expected behavior**

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.6.5
 - Other Device Information: Lineage OS 20 rooted OnePlus 7 Pro

**Additional context**
YouTube works fine but TikTok suddenly started doing this. Videos work after being renamed to .mp4, so it's just the filename extension that's having this issue

**Comment by deniscerri** [comment]
Try setting the container to mp4. Don't leave it default

**Comment by TheHighGroundWins** [comment]
> Try setting the container to mp4. Don't leave it default

Still has the same problem

**Comment by deniscerri** [comment]
This issue has been fixed now in the latest beta

**Comment by TheHighGroundWins** [comment]
Same issue just popped up recently I'm thinking maybe someone behind Tiktok doesn't wan't people to download videos

**Comment by deniscerri** [comment]
get the app now
