### ISSUE TITLE
[BUG] Extracting Download URL on version 1.6.5

### ISSUE THREAD

**Issue by hunkyburrito** [deniscerri/ytdlnis#255]
**Describe the bug**
There is a generic HTTP 403 error returned when I tried to download from either google drive or redgifs. Something changed from YTDLnis version 1.6.4 to 1.6.5 that broke extracting from these sites. It seems to me that YTDLnis is not extracting/parsing the download url correctly, giving yt-dlp only the end of the url as can be seen in the screenshot below.

**To Reproduce**
1. Try to download any video from redgifs
2. Download fails
3. Check the log and see HTTP 403 error.

**Expected behavior**
The download should complete successfully like when using YTDLnis(1.6.4), yt-dlp in Termux, or Seal.

**Screenshots / Video Recording**
![Error Screenshot on version 1.6.5](https://github.com/deniscerri/ytdlnis/assets/48025161/37a90ccc-9453-4969-bc94-c6ec3a769006)

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.6.5
 - Other Device Information: Samsung Galaxy S10

**Additional context**
Link in error is SFW and was used for an example. I've tried the same link and settings in both app versions and was able to successfully download it only in 1.6.4.

**Comment by deniscerri** [comment]
dm me on telegram. Send me more samples

**Comment by hunkyburrito** [comment]
Latest release (1.6.7) hasn't been giving me these errors anymore so I'm closing this issue.
