### ISSUE TITLE
Bug:- doesn't show any option to select audio quality before downloading. 

### ISSUE THREAD

**Issue by soymadip** [deniscerri/ytdlnis#26]

**Comment by deniscerri** [comment]
Not a bug. Currently the app just downloads the best quality. The next ver will have it

**Comment by soymadip** [comment]
> Not a bug. Currently the app just downloads the best quality. The next ver will have it

Got it, wanna say one more thing. 
If it shows download size when selecting video / Audio quality (like powertube), it will be super useful

https://user-images.githubusercontent.com/84225810/217014990-a88ca5db-befa-4a31-8532-e459dd6c36c1.mp4

**Comment by deniscerri** [comment]
Yeah, file size has been implemented. Ill just implement a card like powertube when sharing, and some other changes soon.
Im thinking of adding most of the features right from the share card.

**Comment by soymadip** [comment]
> Yeah, file size has been implemented. Ill just implement a card like powertube when sharing, and some other changes soon. Im thinking of adding most of the features right from the share card.

🥺 That sounds so good . As of now there's not a single yt-dlp client that offers video format selection at the first.
