### ISSUE TITLE
[FEATURE REQUEST] Navbar color

### ISSUE THREAD

**Issue by AntonDzutstsati** [deniscerri/ytdlnis#260]
**Is your feature request available in yt-dlp? Please describe.**

Is there any way to update navbar in settings menu and make its color adaptive?

![Screenshot_20230831-183055.png](https://github.com/deniscerri/ytdlnis/assets/74765004/8b935fce-bb65-4a0a-beab-2a54164661d5)

**Comment by deniscerri** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/64997243/0363d4cc-823e-4375-9007-ecc256674633)
it already is?

**Comment by deniscerri** [comment]
Fixed it. Wait for official release
