### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tigger-S** [deniscerri/ytdlnis#261]
Yes I have latest app version and ytd version, youtube videos download in mkv instead of mp4 even though I've set it as mp4 in settings, the only way it downloads in mp4 is if I set video codec to webm but then I can't share it.... Also when I try to share/send the mkv videos they send without sound......

**Comment by deniscerri** [comment]
latest release or latest beta?
this issue has been resolved in the beta. Try it and come back at me

**Comment by deniscerri** [comment]
Also if you are sharing to whatsapp, download a video format that has avc1 codec and combine it with a m4a or aac audio format. Should work

**Comment by Tigger-S** [comment]
Oh I don't usually do beta, I run latest official, but thank you
