### ISSUE TITLE
[FEATURE REQUEST] [KOR] Language Translarion done.

### ISSUE THREAD

**Issue by root-kernelhacker** [deniscerri/ytdlnis#263]
I was surprised that you invited me to translate. ^^ 

The Korean translation has been completed.  

I will check the entire Korean language as soon as I have time.

**Comment by deniscerri** [comment]
Yes you are now the manager of your language. If you see the strip not being blue someone changed it that wasnt you.

**Comment by root-kernelhacker** [comment]
> Yes you are now the manager of your language. If you see the strip not being blue someone changed it that wasnt you.

yes.  All right.  thank you!
