### ISSUE TITLE
[FEATURE REQUEST] add a feature to create a subfolder for playlists

### ISSUE THREAD

**Issue by not-programmer98** [deniscerri/ytdlnis#270]
**Is your feature request available in yt-dlp? Please describe.**
A clear and concise description of what the problem is.
When downloading a whole playlist like 40 video my download folder become a mess.

**Describe the solution you'd like**
Download playlists to subfolders. Usually playlists videos have the same name with just a different number, you can use this to name the sub folder

**Comment by deniscerri** [comment]
@Wa1t5 this can only be done in terminal or quick download mode.

Otherwise if the app is processing every item it wont apply. But ill think of a solution for the latter

**Comment by deniscerri** [comment]
[1.6.6.2](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.6.2-beta)
