### ISSUE TITLE
[BUG] sponsor block filter bug

### ISSUE THREAD

**Issue by not-programmer98** [deniscerri/ytdlnis#271]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
I was downloading a playlist and choosed to remove intro by sponsor block but it didn't work

**To Reproduce**
When Downloading a playlist click the 3 dots the sponsor block the check intro and hit ok.
When repeating this I found that the intro is unchecked

**Expected behavior**
It should keep intro checked and remove the intro from downloaded files

**(please complete the following information):**
 - Android Version: 
 - App Version:
 - Other Device Information:
Will fill this later

**Additional context**
Sponsor bolck was disabled from settings because I only want to do this once not for every thing I download

**Comment by deniscerri** [comment]
Just select intro and press ok. It will apply to every item. But if you go back and press ok. It will clear all.

I'll make it show as checked if all items have it checked in the next update. This is merely an ui thing

**Comment by deniscerri** [comment]
and now its fixed

**Comment by deniscerri** [comment]
[1.6.6.2](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.6.2-beta)
