### ISSUE TITLE
[FEATURE REQUEST] Feature to download subtitles as .lrc for music files

### ISSUE THREAD

**Issue by Wa1t5** [deniscerri/ytdlnis#273]
**Is your feature request available in yt-dlp? Please describe.**
A feature to download subtitles as ,lrc files for use alongside music players, I know that yt-dlp  currently has a issue that prevents it from embeding the subtitles on the music, but most music player support using .lrc files alongside the music file

**Describe the solution you'd like**
An option to download the subtitles and then convert it to .lrc

**Comment by deniscerri** [comment]
what is the command

**Comment by Wa1t5** [comment]
> what is the command

to convert to .lrc?: yt-dlp <link> <other args> --write-subs --convert-sub 'lrc'

**Comment by deniscerri** [comment]
add that as an extra command in the audio tab and you are set
