### ISSUE TITLE
[BUG] YouTube video sharing no sound 

### ISSUE THREAD

**Issue by Tigger-S** [deniscerri/ytdlnis#274]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

YES

**Describe the bug**
Whenever I try to share videos that I downloaded from YouTube to WhatsApp it sends without sound

**To Reproduce**

Download youtube video share to whatsapp 

**Expected behavior**
No sound

**Comment by deniscerri** [comment]
select an avc1 video format and scroll down and select an aac or m4a audio format. Then press ok

**Comment by Tigger-S** [comment]
Noted....

**Comment by akashpal-21** [comment]
I selected Codec h.264 (avc1); video format MP4, the video downloaded has audio codec OPUS. Doesnt matter if I select an audio format in the processing menu, it seems to be for an audio only download.

How to change audio codec for the video itself ?

**Comment by deniscerri** [comment]
Yes the audio format is only for audio only
In the download card, tap the format item and update formats if necessary. Choose the avc1 video format and then scroll all the way to the bottom and there are the audio formats, select the audio format/s u want then tap ok. thats it

**Comment by deniscerri** [comment]
now that you mention it. I should incorporate the audio format preference to the video too. thx for letting me know

**Comment by akashpal-21** [comment]
> Yes the audio format is only for audio only In the download card, tap the format item and update formats if necessary. Choose the avc1 video format and then scroll all the way to the bottom and there are the audio formats, select the audio format/s u want then tap ok. thats it

Finally I have it working, thank you. It is currently very unintuitive and selecting from the download card nullifies the easeness that preconfiguring the formats grants, also the audio formats do not appear unless 'Update Formats' is selected - it shows only the quality before updating. 

I wouldve never figures it out by me without you giving me the hint. Thank you.

**Comment by deniscerri** [comment]
yes ill try to make the app auto-choose the audio format based on the preference in the next release

**Comment by deniscerri** [comment]
but for the time being, considering that format id 140 is the most common m4a audio format, set that as preferred audio format in the processing settings. Also in the updating settings see what format source you have, set it to piped if you want the app to have formats preloaded as soon as you open the download card

that way it will choose the preferred video (avc1) + the 140 if its available ready to go

**Comment by MrTahran** [comment]
@deniscerri I have a question. Will I be able to I share the downloaded video on Instagramor WhatsApp status if I choose avc1 codec + opus audio? As far as I know m4a audio codec is bound to avc1 codec.

**Comment by deniscerri** [comment]
@MrTahran yes. If that doesnt work for some reason, tap the recode video in the download card and enable compatible video toggle. It will force recode the video to generic mp4 which most apps will accept

**Comment by MrTahran** [comment]
> [@MrTahran](https://github.com/MrTahran) yes. If that doesnt work for some reason, tap the recode video in the download card and enable compatible video toggle. It will force recode the video to generic mp4 which most apps will accept

Thank you so much for answer.

**Comment by AdityaMH** [comment]
Now every downloading video from youtube, audio always replaced to ai voice. This is disgusting.

**Comment by deniscerri** [comment]
@AdityaMH try setting preferred audio language in the processing settings

**Comment by AdityaMH** [comment]
> try setting preferred audio language in the processing settings

Didn't work. Still same result.
