### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by al13tar** [deniscerri/ytdlnis#275]
**Describe the bug**
When i try download a video from Instagram!

**To Reproduce**
When i copy a post link from Instagram and try to download it,an error is displayed.

**Expected behavior**
Download the post

**Screenshots / Video Recording**
![IMG_20230910_153355.jpg](https://github.com/deniscerri/ytdlnis/assets/85931669/739b1741-2391-4da1-8f60-c3b7af94c6e7)

**(please complete the following information):**
 - Android Version: 11
 - App Version: v1.6.6 (yt-dlp version:2023.07.06)
 - Other Device Information: Xiaomi Mi9T

**Comment by teddysulaimanGL** [comment]
Try updating to yt-dlp nightly, this issue is from yt-dlp's side, the error even says so
