### ISSUE TITLE
[BUG] app crashing 

### ISSUE THREAD

**Issue by Wa1t5** [deniscerri/ytdlnis#276]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
When I download something (only tested with music) and I have set the maximum downloads that can be done at the same time set to 10, the app downloads only one file and crashes

**To Reproduce**
1 - Set the maximum parallel downloads to 10
2 - Try to download a playlist

**Expected behavior**
App download files without crashes

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 13
 - App Version: latest beta
 - Other Device Information: samsung a03

**Additional context**
I already tried reinstalling the app, btw the app seems to crash even when I have my maximum parallel downloads set to 1, but setting it to 10 makes the app crash faster

**Comment by Wa1t5** [comment]
App seems to crash when downloading music that have special characters on it's name too, more specifically music with Japanese title

**Comment by teddysulaimanGL** [comment]
10 concurrent downloads cause the app to crash is expected at some point. Just don't use 10 concurrent downloads if that crashed your device.

Also, try enable Restrict Filenames or if the title of that video is too long, try reducing the title manually

**Comment by teddysulaimanGL** [comment]
Let's keep talking about issues when you're using stable one, please. If you're using beta, let's share the issue on Telegram

**Comment by Qaz-6** [comment]
There shouldn't be a problem, it just causes the phone to slow down or not. If the error occurs, there is a problem🤔

**Comment by deniscerri** [comment]
Send the playlist. Also a video recording

**Comment by Wa1t5** [comment]
Playlist: https://music.youtube.com/playlist?list=OLAK5uy_kxz9S92TWs4cJUDLCLcr42KjJIYbnm7LU&si=WrUeL93s1T_d6j_v

Video: https://github.com/deniscerri/ytdlnis/assets/79410846/d37b1691-9ba9-49a6-b6ee-8b6b9655c72f

The app crashes even when concurrent downloads is set to 1

**Comment by deniscerri** [comment]
Ok I'm able to reproduce. Will fix. And you are right it's the bad characters in the file.

**Comment by deniscerri** [comment]
Fixed it

**Comment by Wa1t5** [comment]
> Fixed it

Thanks
