### ISSUE TITLE
[BUG] i cant download video in h264 codec

### ISSUE THREAD

**Issue by artem45ik** [deniscerri/ytdlnis#277]
if i try download video in h264 codec 
video still downloads in vp9 codec not h264

i tried this video to download:https://youtu.be/qUGXz2X0vqY?si=zbMZ1RiKE_r6ljTd

https://github.com/deniscerri/ytdlnis/assets/94762989/c8e4e980-c5d3-4221-ac65-9aa7059e642d

android version:13
app version:1.6.6
device:samsung galaxy a03s model sm-a037f/ds

**Comment by deniscerri** [comment]
If the app doesn't find h264 then it will get the best video instead.

Also im assuming you should use avc1 instead of h264. They are the same thing but some sites write h264 instead. Avc1 is mostly used. So choose that. Good luck
