### ISSUE TITLE
[BUG] there's no way to disable "Move temporary files"

### ISSUE THREAD

**Issue by not-programmer98** [deniscerri/ytdlnis#289]
**Describe the bug**
There's no way to disable this feature.
I clicked it by mistake and it moved cache files to my download folder and it doesn't even clear these files if error occured or if I canceled the download

**Comment by deniscerri** [comment]
Moving the cache files is not supposed to be done when u have leftover downloads that u want to redo soon. U move cache files if for some reason u want them, or u downloaded a livestream and cancelled the download and want that portion of the download.

Why do u want this disabled? Just dont tap it lol

**Comment by not-programmer98** [comment]
It applies automatically to every new download, I wanna go back to the default.

**Comment by deniscerri** [comment]
thats impossible. What kinda cache files are you getting after the download is done?

**Comment by deniscerri** [comment]
just delete those cache files u have in your file system. new ones wont show there. only transfers are there that you yourself tapped in the settings. app doesnt use cached downloads in the downloads folder

**Comment by not-programmer98** [comment]
My English is bad,  but I will try again by default no cache files appear in download folder, but after clicking that option every new download keeps cache there while downloading.
I want to come back to the default where there's no cache files appear while downloading

**Comment by deniscerri** [comment]
again that is impossible. Show me a screenshot of the folders preferences

**Comment by not-programmer98** [comment]
![Imagepipe_0](https://github.com/deniscerri/ytdlnis/assets/126913926/24a88144-e4c1-4d1c-ac01-d8b382d11a86)

**Comment by deniscerri** [comment]
this is why. Turn on cache downloads first on. When you have it off the app will put the cache in the same spot as the final destination

**Comment by not-programmer98** [comment]
I tried it now again. Downloading thia video in the notification 
![Imagepipe_0](https://github.com/deniscerri/ytdlnis/assets/126913926/19d43787-bfb4-4b0e-ba13-7f5bed853738)
After it starts to download, it creates this in my downloads folder
![Imagepipe_1](https://github.com/deniscerri/ytdlnis/assets/126913926/12db9eb2-5a70-43ee-840c-d0e1dbaa17a1)
I cancelled the download and this file still here

**Comment by deniscerri** [comment]
do what i mentioned.

**Comment by not-programmer98** [comment]
> this is why. Turn on cache downloads first on. When you have it off the app will put the cache in the same spot as the final destination

This fix it, thanks.
But now if I cancelled a download or an error occurred, will these cache files be deleted or it will take unnecessary storage on my phone?

**Comment by deniscerri** [comment]
If you cancel it wont be deleted because the app assumes you might redownload later.
If you delete the item completely, then the cache will be deleted.

Also u can delete the cache yourself if you want in the folder settings

**Comment by not-programmer98** [comment]
Is tere a specific folder where I can find these cache files after enabling "cache downloads first"

**Comment by deniscerri** [comment]
Its in the internal app storage.You cant access it normally.
this is the path
/data/data/com.deniscerri.ytdl/cache/downloads/

**Comment by not-programmer98** [comment]
This path doesn't exist in my phone
![Uploading Imagepipe_0.jpg…]()

**Comment by deniscerri** [comment]
Yes i know. You cant access it. Unless you are a root user.
