### ISSUE TITLE
[Feature Request] Add a built-in web browser

### ISSUE THREAD

**Issue by Tarek-Hasan** [deniscerri/ytdlnis#294]
Currently, if anyone wants to download video from a website, they have to go and forth between YTDLnis and web browser or YouTube or other apps. It's very annoying. If anyone wants to download multiple video, that quickly becomes a nightmare.

**Describe the solution you'd like**
Add a built-in web browser, like Snaptube and Vidmate have done. This will make downloading video very easy compared to current method. A simple Android webview based browser would do the trick. 
Only few basic features would be enough:
- Search
- Bookmarks
- Video playback
- AdBlocker

There are few good webview based browser out there, you can use any of those as codebase if you want.
- [FOSS Browser](https://codeberg.org/Gaukler_Faun/FOSS_Browser)
- [Fulguris](https://github.com/Slion/Fulguris)
- [Lightning Browser](https://github.com/anthonycr/Lightning-Browser)

**Comment by deniscerri** [comment]
you dont need to go back and forth, just share the link to ytdlnis
the download card will pop up. No need to jump to the app and search manually
