### ISSUE TITLE
[BUG] .unknown_video

### ISSUE THREAD

**Issue by deaveipslon** [deniscerri/ytdlnis#295]
There is a bug that when you finish downloading a video from TikTok, the app finishes the download, but does not correctly rename the file extension, which has the name (.unknown_video) as the extension. You need to manually rename it to (.mp4) for the video to be readable by the system. YTDLnis has the default configuration.

![Screenshot_2023-10-01-11-36-20-44_55bef12f624c2b805189a6aa783c400d.jpg](https://github.com/deniscerri/ytdlnis/assets/25135112/53f70ff5-9dcd-4c53-8dbb-56a2379e1825)

 - Android Version: 13 (Realme UI 4)
 - App Version: 1.6.7
 - Device: Narzo 50A

**Comment by deniscerri** [comment]
Set the container to mp4 in the download card

**Comment by deaveipslon** [comment]
> Set the container to mp4 in the download card

I've tested this too, but the problem remains, from what I've gathered, this doesn't happen in version 1.6.6.2-beta

**Comment by deniscerri** [comment]
Can you tap the extra commands button after you configured everything and send me the command it creates?
