### ISSUE TITLE
Download Card shows Title / Author in English instead of Translated Language

### ISSUE THREAD

**Issue by atuy1219** [deniscerri/ytdlnis#298]
**Describe the bug**
**To Reproduce**
**Expected behavior**
**Additional context**
When I open YTDLnis from share to download YouTube music and press the update button in the lower right corner, it loads the artist name and song title, but those names are in English, not the language I am using. This problem does not happen with YouTube videos.
I believe this problem is caused by YTDLnis accessing YouTube in English when getting the artist and song names (this is just my very ignorant guess and could be different).

**Screenshots / Video Recording**
![Screenshot_20231012-164734.png](https://github.com/deniscerri/ytdlnis/assets/130917473/222deb31-b5a6-44db-a405-389671c097e6)

Android14
YTDLnis1.6.7

**Comment by deniscerri** [comment]
@atuy1219 come to telegram, ill send you a build so u can test and see if it works

**Comment by atuy1219** [comment]
OK. I just joined YTDLnis Chat.

**Comment by deniscerri** [comment]
Observe [1.6.8](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.8)
