### ISSUE TITLE
[FEATURE REQUEST] add support for armeabi-v7a

### ISSUE THREAD

**Issue by not-programmer98** [deniscerri/ytdlnis#302]
[FEATURE REQUEST] add support for armeabi-v7a

**Comment by deniscerri** [comment]
Every release has v7a. Look again

**Comment by not-programmer98** [comment]
![ResizedImage_2023-10-12_19-21-52_8106](https://github.com/deniscerri/ytdlnis/assets/126913926/5b3e586a-8db8-4198-9190-363f3efa7331)
So do you why this happens?
This device run on Android 8, could this be the reason?

**Comment by tusharchopra07** [comment]
I ,think the app supports Android 6 or later
You can download the apk from their Official GitHub Telegram or Uptodown

**Comment by not-programmer98** [comment]
> ![ResizedImage_2023-10-12_19-21-52_8106](https://user-images.githubusercontent.com/126913926/274665234-5b3e586a-8db8-4198-9190-363f3efa7331.jpg) So do you know why this happens? This device run on Android 8, could this be the reason?

Any idea why this happens? @izzysoft

**Comment by not-programmer98** [comment]
> I ,think the app supports Android 6 or later You can download the apk from their Official GitHub Telegram or Uptodown

But it will be a pain to download apk every update

**Comment by tusharchopra07** [comment]
This issue is reported by 1-2 more people that the app is not available for installation in Droidify also 
You can get update notifications directly from the app

**Comment by not-programmer98** [comment]
Is it droid-ify spacific? Would it work if I tried anther client?

**Comment by tusharchopra07** [comment]
You can try

**Comment by not-programmer98** [comment]
I tried both F-droid client and neo store. The problem isn't about droid-ify.

**Comment by tusharchopra07** [comment]
So you can use their GitHub or Telegram to download latest apk and turn on Update notification in the app settings

Or join their telegram

**Comment by deniscerri** [comment]
You need to complain to other stores to include the arm apk because i always include it in my releases

**Comment by IzzySoft** [comment]
Though I have to guess between the lines it seems the question is why there's no armv7a APK in my repo. My repo only supports 1 APK per version, so it's either arm64 or armeabi-v7a. When the app was included with my repo, [arm64 was chosen](https://gitlab.com/fdroid/rfp/-/issues/2216#note_1354290888).

Btw @deniscerri looking at the `full_description.txt` and [how it renders](https://apt.izzysoft.de/fdroid/index/apk/com.deniscerri.ytdl), don't you think that could need some improvements? It's really hard to read and rather looks like a "wall of text". Is it supposed to be a bullet-point list? But even if: no sections, no introducing paragraph? Maybe…

```markdown
<b>YTDLnis</b> lets you download audio/video files from more than 1000 websites, and offers a lot of features. For example:

<b>process playlists</b>

- edit every playlist item separately just like in a normal download item.
- select a common format for all items and/or select multiple audio formats in case you are downloading them as a video
- select a download path for all items
- select a filename template for all items
- batch update download type to audio/video/custom command in one click
- queue downloads and schedule them by date and time
- you can also schedule multiple items at the same time
- download multiple items at the same time
- use custom commands and templates or go full yt-dlp mode with a built in terminal
- you can backup and restore templates, so you can share with your buddies

<b>COOKIES support</b>

..
```

(not sure where section borders are supposed to be, so just giving the rough idea) The above would render fine as Markdown (with my repo), and F-Droid does understand the "simple HTML tags" fine as well.

**Comment by deniscerri** [comment]
I appreciate the suggestion. Will try to fix it up soon. Now that you mention it, yeah that looks bad lol

**Comment by IzzySoft** [comment]
Please let me know when you've reformatted it so I can check for what steps to configure my update checker. Currently it's set to take the file as-is, just replacing all newlines by `<br>`. The other options are using Markdown (only with my repo, F-Droid.org does not (yet?) support that but would render it the same as I did now) and HTML (take as-is, do not add `<br>`s, perform HTML sanitizing).

**Comment by not-programmer98** [comment]
@deniscerri could you release just one apk for all architectures like when downloading an apk from apkmirror, It is in apk for both arm64 and arm7a

**Comment by deniscerri** [comment]
Split apk are smaller in size

**Comment by IzzySoft** [comment]
Exactly that. A "fat build" would be too big for my repo, so you had to pick that from here again :wink:
