### ISSUE TITLE
[BUG] Cannot send videos downloaded from Facebook in WhatsApp. 

### ISSUE THREAD

**Issue by mridiot0** [deniscerri/ytdlnis#306]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

** Yeah ** I'm using nightly version

**Describe the bug**

 1. Any video downloaded from Facebook cannot be shared in WhatsApp. It's just showing ** this video is not supported please choose another video **. Though the video is playing in any video player even on the WhatsApp preview page but when I tap send, I see the message.  
2. When I ** allow all file access ** in the app and then if I download any other videos, it's just not showing in my file manager (Google Files).
**To Reproduce**
1. Download any video from Facebook and try to share it in WhatsApp it will pop up the message. (Although some videos works but the working rate is too low like 1 in 40-50 videos.)
2.  Go to settings and allow all file access then download any videos (For me it happened in Facebook) It won't show in my file manager.

**Expected behavior**

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 12
 - App Version: [v1.6.8.2-beta](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.8.2-beta), v1.6.7
 - Other Device Information: Samsung galaxy f41

**Additional context**

For the first problem I think there might be problem in the video codec format although I tried using all the available formats (mp4, mkv etc.) and codecs (av1, vp9 etc.). I don't know what's causing the problem as some videos are working and there's no difference in videos and also I have the cookies enabled for Facebook.
For the second problem I have no idea.

**Comment by deniscerri** [comment]
1. Select a video format that has avc1 format PLUS go down in the format list and select a m4a or aac format. Just to make sure set the container to mp4 aswell. This will surely work

2. When you gave access to all files you probably turned off caching. Turn it back on as it seems your device cant write directly to that folder you have set

**Comment by mridiot0** [comment]
Hey thanks for the reply, I can't understand the solution you provided, like is there any "avc1" codec format Or "m4a" video format available for videos. I checked all the settings and the find that the formats are only available for audio only for video there's only "mp4, mkv, webm", and for the codecs  "av1, vp9, avc, hevc"

Is there anything I'm missing 😕. Can you please rectify me.

**Comment by deniscerri** [comment]
Avc1 is avc. 1 is kinda redundant in formats so choose that in the preferred codec.

What i was referring to though is when you are in the dow load card. Click the format list and find a format that is avc AND choose an audio that is m4a

Currently in 1.6.7 it doesnt have preferred audio codec so u have to do it manually
But in 1.6.8 u wont have to worry

**Comment by mridiot0** [comment]
Sorry for late reply, 😅 I was busy.

I tried what you said but it seems it doesn't work at all any other workaround I cab do?

**Comment by teddysulaimanGL** [comment]
![Screenshot_20231028_084520.jpg](https://github.com/deniscerri/ytdlnis/assets/134608531/848a71af-d80a-4872-ab08-1d8481f7f719)
Press this button, wait for a moment

![Screenshot_20231028_084631.jpg](https://github.com/deniscerri/ytdlnis/assets/134608531/168758be-be33-42a2-be68-55feb1003763)
Select one of the video stream that has this codec, scroll all the way down and you'll find this ⬇️

![Screenshot_20231028_084319.jpg](https://github.com/deniscerri/ytdlnis/assets/134608531/6a008882-eaa9-47ab-89a3-5a200bb25417)
After you found this, select the audio that has this codec as well

**Comment by mridiot0** [comment]
Ok that's different, I was changing the formats and codecs in settings in processing page.
Let me give it a try.

**Comment by teddysulaimanGL** [comment]
AVC might not be available most of the time on Facebook videos, so the only thing you can do is to re-encoding the video you're about to download so it can be uploaded to WhatsApp status or whatever

**Comment by mridiot0** [comment]
And how can I do that can explain plz 😄

**Comment by mridiot0** [comment]
Or may be close this issue as there's no proper solution for every video. Some videos work though as they might have the proper encoding format. So, might close the issue.

**Comment by deniscerri** [comment]
send us the link

**Comment by mridiot0** [comment]
Are you talking about the Facebook link??
This is the one: https://www.facebook.com/reel/308632441916471?mibextid=EVDHJDB9vBtcBeCT

**Comment by deniscerri** [comment]
Looks like the extractor is broken again, cant access this.

**Comment by mridiot0** [comment]
Then what to do😕

**Comment by deniscerri** [comment]
As you early mentioned some videos have the proper encoding and some dont. If you can share a video but no audio, then u need to choose the audio format in the bottom of the format list as m4a or aac. That will fix it.
