### ISSUE TITLE
 when downloading playlist, title is not original title on piped results

### ISSUE THREAD

**Issue by calilux** [deniscerri/ytdlnis#308]
When I try to download the YouTube playlist, the title of the video is downloaded in English set by the video publisher for English-speaking users, not the original language. When I download one video at a time, it is downloaded under the title of the original language. I don't know much about programming, so I tried to solve this problem by searching. As a result, I learned about the additional command --extractor-args YouTube:lang=ko and added it. But the title is still printed in English. How do I fix this?
![Screenshot_20231023_095437](https://github.com/deniscerri/ytdlnis/assets/148729698/5c9b4333-24ce-4bcb-b0c0-770d1a996b62)
These videos are korean videos, but english title..

**Comment by deniscerri** [comment]
send me the playlist please. Also a japanese guy had the same issue. ill try --extractor-args YouTube:lang=ko and get back at you

**Comment by deniscerri** [comment]
yt-dlp was able to show the correct titles with that command but with piped i cant do anything yet. I opened an issue for them
https://github.com/TeamPiped/Piped/issues/3067

**Comment by deniscerri** [comment]
The fix for yt-dlp is done in [1.6.8](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.8)
A workaround for now is to make a gibberish url for the piped url so the app is forced to fallback to yt-dlp for data.

**Comment by deniscerri** [comment]
Closing this as piped is not supported
