### ISSUE TITLE
[Crash] 1.6.8-2 Not Startup

### ISSUE THREAD

**Issue by EFIShell0** [deniscerri/ytdlnis#309]
- Android Version: Android 13 based MIUI 14 
 - App Version: 1.6.8-2 
 - Other Device Information: Redmi Note 10S (Secret) 6/128 
There was no such problem in the previous beta.  Now it stops working just when opening (Vanced or normal opening doesn't matter).

**Comment by deniscerri** [comment]
yes because database changed greatly. Reinstall

**Comment by EFIShell0** [comment]
> yes because database changed greatly. Reinstall

Thank you. Reinstall worked.
