### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shubamg1234567890** [deniscerri/ytdlnis#317]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 
 - App Version:
 - Other Device Information:

**Additional context**
Add any other context about the problem here.~~~~

I am using latest version of yt-dlp and updated recently.. kindly add a compatibility mode for WhatsApp as I am unable to either upload the downloaded video.. as whatsapp says this file is not supported.. kindly add an option compatibility mode in which default settings for whatsapp applied automatically

**Comment by deniscerri** [comment]
I did this for new users. The phone will prefer avc1 video formats along with m4a audio formats.

Go to processing settings and set preferred video codec to avc1 and audio up m4a. Should work

**Comment by teddysulaimanGL** [comment]
This isn't even supposed to be an issue nor bug

**Comment by shubamg1234567890** [comment]
Problem is that I have kept these settings avc1 codec and m4a audio format but I am still unable to share.. on WhatsApp.. Can I expect a favour.. :) please do tell me, if the same works for you..

**Comment by deniscerri** [comment]
We have no issues. Maybe you have set the audio format as m4a but not the preferred audio codec to m4a
