### ISSUE TITLE
[FEATURE REQUEST] Option to skip sponsorblock processing if download fails

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#321]
**Is your feature request available in yt-dlp? Please describe.**
Can't tell

Sponsorblock servers stay down a lot and downloading fails during processing if that's the case. It sucks when you have to download multiple GB's of files again in this scenerio.

**Describe the solution you'd like**
A notification/button to process the video without sponsorblock if the error occurs. Getting the output without SB is still much better than entire operation failing.

**Describe alternatives you've considered**
Maybe if there's a way to tell or verify if SB is working fine before the download starts?

**Additional context**

**Comment by zaednasr** [comment]
Sponsorblock is integrated with yt-dlp so the only way to know is to fire yt-dlp up. That is expensive. What you could do is add a preferred extra command with the following

--no-abort-on-error --ignore-errors

I think these will try to continue downloading even if sponsorblock fails. Havent tested it but it might work.

**Comment by NikunjKhangwal** [comment]
This will skip any error not just SB related it seems. But something is better than nothing i guess. Thanks for the suggestion.
