### ISSUE TITLE
[FEATURE REQUEST] Aria2c integration

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#323]
**Is your feature request available in yt-dlp? Please describe.**
Aria2 can use yt-dlp to access yt content for downloading as far as i know. Doesn't have much to do with yt-dlp itself.

**Describe the solution you'd like**
Having Aria2 as a optional downloader. This is probably a very low priority feature but it's nice to have.

**Describe alternatives you've considered**

**Additional context**
For reference
[Seal](https://github.com/JunkFood02/Seal) has the option. Also it has been ported to Android [before](https://github.com/devgianlu/Aria2App)

**Comment by zaednasr** [comment]
It has been part of the app from the beginning. Go to Downloads settings, scroll near the bottom

**Comment by NikunjKhangwal** [comment]
Ah! My bad. Now i feel extremely dumb.
Can this be mentioned under README as a feature?
