### ISSUE TITLE
[FEATURE REQUEST] Custom Backup Directory and Automatic backups

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#324]
**Is your feature request available in yt-dlp? Please describe.**
Unrelated

**Describe the solution you'd like**
An option to select a backup directory for "Backup and Restore" instead of saving to Downloads folder by default. Also an automatic backup feature with a scheduler, like on weekly basis

**Describe alternatives you've considered**
If something like weekly auto backups is going to make app run in background and hog memory then you can consider something like making a automatic backup whenever there's a new command template added or change in settings.

**Additional context**
Add any other context or screenshots about the feature request here.#

**Comment by zaednasr** [comment]
There is no reason to over complicate things. Also there is no real reason to have the app hog resources by trying to make new backups on every element of the app is added or removed or modified.

App backups are meant to be manual and pretty rare. When you want to switch phones, or before you update to the new version or sending your backed up stuff to a friend. Having redundant backup json files is excessive.

**Comment by NikunjKhangwal** [comment]
Not every single element but at least things like commands and cookies doesn't feel useless. In my case i keep all of my apps backups in a specific folder (reason why i asked for a custom directory) which gets synced to cloud on a daily basis. Particularly useful when your phone is dead, gets stolen and all, in that case you can't make manual backup.
Either way these are just suggestions and it's fine if you don't agree with my reasons. 👍🏼

**Comment by zaednasr** [comment]
🤔 Ill keep that in my mind and find a way to make it work

**Comment by NikunjKhangwal** [comment]
Thank you, take all the time you need.
