### ISSUE TITLE
Instagram video download is showing error [BUG]

### ISSUE THREAD

**Issue by vishan-git** [deniscerri/ytdlnis#325]
WARNING: [Instagram] CzT-r3xrs5w: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CzT-r3xrs5w: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
#issue

**Comment by zaednasr** [comment]
As the error explains, you need to report the issue to yt-dlp and not here. Also see the suggestion. Try using cookies as the video might be private, or you need to update yt-dlp in the settings.
