### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by kKuteKuto** [deniscerri/ytdlnis#326]
How to add icon YTDLnis to tw directly
I found the flag of X but not successful
**shortened_tracking_parameters_mapping**
![My Image](https://i.upanh.org/2023/11/13/Picsart_23-11-08_15-14-19-2737defff5b8cc9c0be.jpeg)

**Comment by zaednasr** [comment]
Its not possible afaik. I think X has a list of apps it likes to share to and shows them in their custom share sheet.
