### ISSUE TITLE
[BUG] can't download certain videos

### ISSUE THREAD

**Issue by 4kNiko** [deniscerri/ytdlnis#328]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
Im unable to download certain files
**To Reproduce**
Just try and download certain videos, I don't know if its every video but I've gotten it with quite a few.
**Expected behavior**
Start downloading the video and a few seconds later i get the error "ERROR: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']" 

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.
I don't have any since i don't have a screenshot/ video taking app, sorry!!
**(please complete the following information):**
 - Android Version: 11
 - App Version:1.6.8 [arm64]
 - Other Device Information: Samsung SM-T290, 2GB RAM And 32GB Storage

**Additional context**
I dont know if i need to install termux, but i can try if you guys want, also it only happens in very specific videos, like for example, i can be downloading one music video, then i download another and the error appears

**Comment by Qaz-6** [comment]
What does Termux have to do with it?
You can send:
1. Log Downloads(Activate it in the settings, see in the more section, copy and send)
2. A screen recording explaining the problem
3. The link of the video that does not download.
4. The app is not related to termux.What do you use Termux for?
5. Please write clear information

**Comment by 4kNiko** [comment]
Ill send a log, gimme a sec.

**Comment by 4kNiko** [comment]
Well, it works now but heres a screenshot for proof that it did appear, all i did was uninstall termux (i only use it for linux stuff, but maybe its a yt-dlp error?)![Screenshot_20231115-072105.jpg](https://github.com/deniscerri/ytdlnis/assets/136009590/c1b2ce48-6262-47d5-bdd2-d0c5392dd1af)

Im using a random video since i deleted the URL but it is the same video from the screenshot, thanks anyway!!

**Comment by Qaz-6** [comment]
![Screenshot_20231115-173015](https://github.com/deniscerri/ytdlnis/assets/140435478/5d7985a8-b0c0-4a92-b63d-acd08c9c6b94)

**Comment by zaednasr** [comment]
This is not related to termux. That "termux" folder is used for yt-dlp through the youtube-dl android library. Apps like Seal have the same issue. [https://github.com/yausername/youtubedl-android/](https://github.com/yausername/youtubedl-android/) needs to fix this

**Comment by zaednasr** [comment]
@4kNiko someone else had this same issue and he had installed the wrong version of ytdlnis. Maybe u installed armv7 instead of arm64 or vice versa. Try getting the one that matches your phone's architecture. It will work
