### ISSUE TITLE
 Editing filename template doesn't insert selected field at cursor

### ISSUE THREAD

**Issue by sanctimoniousape** [deniscerri/ytdlnis#339]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

_Using v1.6.9 via IzzyOnDroid_

**Describe the bug**

_Adding a field by clicking one from the predefined list causes the field to always be appended to the end of the format string, rather than at the insertion point indicated by the cursor's placement._

**To Reproduce**

_I chose to modify the default audio filename template, clicked just after the hyphen (and before in another attempt) between the two preexisting fields, then selected the "%(artist)s" predefined tag from the list below the input box.  The field always gets appended to the end of the existing string rather than where the cursor is placed._

**Expected behavior**

_The selected field to be inserted at the current cursor location._

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

_I believe the description given should be sufficient without requiring creating a video, however feel free to request one if I'm incorrect in that assumption._

**(please complete the following information):**
 - Android Version: _11_
 - App Version: _v1.6.9 from IzzyOnDroid_
 - Other Device Information:  _OnePlus 7 Pro_

**Additional context**

_None._

**Comment by teddysulaimanGL** [comment]
That's by design, mate. But what's the reason to append those fields in the cursor in your opinion, I wonder?

**Comment by sanctimoniousape** [comment]
I'm curious why you _wouldn't_ insert it where the cursor is located, but only append at the end?  The way I'm expecting it to work makes changing the format easier by allowing you to insert an additional field without having to remove every field that you want to follow it first, then replace them after you've placed your additional field.  That would seem rather tedious to me. What I was expecting to happen is typically the way virtually all text editing operations work elsewhere in my experience.

**Comment by teddysulaimanGL** [comment]
Calm down, I just need to know it from other's perspective. It'll be changed later, no need to worry

**Comment by sanctimoniousape** [comment]
Not worried so much as confused.  I'm guessing from your response you weren't serious, however.  That's what I get for responding right before bedtime, I guess...

**Comment by zaednasr** [comment]
@sanctimoniousape i will add this feature. no problem

**Comment by zaednasr** [comment]
this feature has been added. wait for release
