### ISSUE TITLE
[FEATURE REQUEST] show 3 favorite formats instead of 1

### ISSUE THREAD

**Issue by Alisis33** [deniscerri/ytdlnis#341]
If multiple formats are available, it would be very useful if up to 3 variants are shown in the first main screen. set in options.
mostly it could be for example 480 360 240, (code 136 134 133).
It would make workflow faster and easier. No need to search prevered in a long list, and easy to compare sizes fast.

**Comment by zaednasr** [comment]
In the preferred video format id, you can write 136,134,133. The app will check each of them if they are present and select the first occurrence.
It would be a huge design change to allow multiple formats in the main download card. Also might get confusing if those are the only formats or if there are others.

**Comment by zaednasr** [comment]
Also in the settings u can change the format order by id if u want, or by filesize since u like to compare sizes

**Comment by zaednasr** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/e0d117e5-77f9-4a8e-be49-fdbe11949bef)
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/9410797f-295e-4e71-b97e-70f46dd8c182)
