### ISSUE TITLE
[BUG] No longer able to add multiple urls to search bar

### ISSUE THREAD

**Issue by MrBKA95** [deniscerri/ytdlnis#342]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
After upgrading to version 1.6.9. I am no longer able to add multiple urls from my clipboard to the ytdlnis search bar when you open the app. The app does not recognise anymore urls after the first and the plus icon that was used to add more urls no longer show up. Therefore I can only download one video/audio at a time

**To Reproduce**
Copy and paste more than one url and attempt to add them to the search bar. The first will be added but additional urls will not be recognised.

**Expected behavior**
To be able to add multiple urls like previous versions of the app so I can download multiple files in one go.

**Screenshots / Video Recording**

https://github.com/deniscerri/ytdlnis/assets/105092892/2ec8b2e8-4908-49d0-8499-adba069da1a7

**(please complete the following information):**
 - Android Version: 13
 - App Version: 1.6.9. arm64-v8
 - Other Device Information: Galaxy S21

**Comment by zaednasr** [comment]
noted

**Comment by zaednasr** [comment]
issue has been fixed. please wait for next release
