### ISSUE TITLE
[BUG] --no-check-certificates doesn't work on non-YouTube sites but works in DLnis terminal

### ISSUE THREAD

**Issue by Omegaplexx** [deniscerri/ytdlnis#350]
**Describe the bug**
Hello! I tried to download a video from Twitter, or X (or Twix as I like to say).

When I add an extra command template with "--no-check-certificates" in it, I still get SSL: CERTIFICATE_VERIFY_FAILED and for some reason this argument duplicates to that long download command everytime I add an extra template.

![Screenshot_20231207-040928_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/95503207/1fa1395a-4667-4811-afbb-842acd152f37)
![Screenshot_20231207-040935_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/95503207/eca81e60-2d99-4c46-b3f5-2b0cc9c02441)

"If YTDLnis can't download the video, then there must be a problem with yt-dlp" I thought to myself and was wrong.

![Screenshot_20231207-045159_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/95503207/7b6cd8fc-3ff3-4a56-9c7d-41e1ebb141c7)
It works.

Even simple "yt-dlp link --no-check-certificates" works perfectly.
![Screenshot_20231207-035547_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/95503207/6c49e0be-cb0b-4dca-89e2-9d60402b1c57)

**To Reproduce**
1. Find a Twitter video in browser and click "Share".
2. Choose YTDLnis and wait.

**Expected behavior**
It should work cuz it's yt-dlp GUI. Can you fix this bug please?

**(please complete the following information):**
 - Android Version: 10
 - App Version: 1.6.9
 - Other Device Information: Samsung Galaxy S7, LineageOS 17.1, rooted

**Comment by zaednasr** [comment]
You are doing two distinct actions. In GUI you are fetching data but in terminal you are simply downloading. Adding an extra command and hitting update doesnt do anything. That command is there waiting to be used when you start the download. Data fetching is built in the app.

Looks like there is something wrong with -j in twitter so just hit download, it will still work. The app doesnt have to fetch data beforehand.

**Comment by Omegaplexx** [comment]
> Looks like there is something wrong with -j in twitter so just hit download, it will still work.

Just checked in terminal if -j option works on Twitter and VK (russian video site) and it does only with --no-check-certificates. Can you make a setting that adds that parameter in YTDLnis data fetching command? I cannot even paste a link in a field on YTDLnis Home screen without it bc I'll get an error.

**Comment by error-reporting** [comment]
> @zaednasr
> 
> > just hit download, it will still work.
> 
> Thank you, it worked!
> 
> > Looks like there is something wrong with -j in twitter
> 
> Just checked in terminal if -j option works on Twitter and VK (russian video site) and it does only with --no-check-certificates. Can you make a setting that adds that parameter in YTDLnis data fetching command? I cannot even paste a link in a field on YTDLnis Home screen without it bc I'll get an error.

Ytdlnis 1.8.1 or newer have the settings you want just pass  --no-check-certificates in command template then set that command as data fetching extractor-args
