### ISSUE TITLE
[FEATURE REQUEST] Support option to download both video and audio for single link.

### ISSUE THREAD

**Issue by BanDroid** [deniscerri/ytdlnis#352]
the download for a link could be either audio or video, using custom command didn't work, hopefully the app could provide both download in the GUI.

**Comment by zaednasr** [comment]
I dont even know if you can even do this with yt-dlp to begin with

**Comment by BanDroid** [comment]
here

![Screenshot_20231208-201633.png](https://github.com/deniscerri/ytdlnis/assets/68449470/1675fb5a-c187-4fa5-8e6c-f5dbf57bdc27)

the download only could chose between audio and video for a url, add another to download both (Audio and Video) in the ui

**Comment by zaednasr** [comment]
That is not the problem lol. The problem is that yt-dlp as far as i know cant do that by design.
The only thing you can do is write -x -k in the extra commands while being in the video tab

It will download the audio but also keep the intermediary files that u have to delete yourself

**Comment by BanDroid** [comment]
> The only thing you can do is write -x -k in the extra commands while being in the video tab

the audio downloaded as random format, how to control the file format for audio?
