### ISSUE TITLE
[FEATURE REQUEST] add youtube and other supported app in manifest.

### ISSUE THREAD

**Issue by BanDroid** [deniscerri/ytdlnis#356]
![Screenshot_20231211-075833](https://github.com/deniscerri/ytdlnis/assets/68449470/1ad87f97-ff99-4f6e-9ea1-eaa12623370e)

please add youtu.be and other supported platform into the manifest intent uri. so user could customize the default link for an app to open, and could chose ytdlnis as default youtu.be when youtube app trying to share link and directly open ytdlnis.

**Comment by zaednasr** [comment]
I dont think this is a good idea because every single youtube link that you will click will send you to the app for download, when in reality u wont really download every link you click, you just wanna watch it.
Just long press the link and share to the app, or share from youtube
