### ISSUE TITLE
[BUG] Failed download notification is permanent?

### ISSUE THREAD

**Issue by sombresu** [deniscerri/ytdlnis#358]
**Describe the bug**
Can't remove notification of "could not download file" of members only video. I download all videos inside a playlist and one of them is members only

**To Reproduce**
Try to download members-only video:

**Expected behavior**
Be able to remove notification of failed download. (Like usual, by sliding right) I can't close it.

**Screenshots / Video Recording**
https://freeimage.host/i/Juqp9uj

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.6.9
 - Other Device Information: MIUI 13

**Comment by zaednasr** [comment]
fixed in 1.7.0
