### ISSUE TITLE
[FEATURE REQUEST] Subdirectory

### ISSUE THREAD

**Issue by ZiadEl-kashif** [deniscerri/ytdlnis#360]
Can we get a "Subdirectory" feature just like the one available in the Seal Application 

Similar to these screenshots
![Screenshot_20231219_131350_Seal.jpg](https://github.com/deniscerri/ytdlnis/assets/43435905/6a7b8c57-6ec8-40d3-a377-8daf546d8fc5)

![Screenshot_20231219_131357_Seal.jpg](https://github.com/deniscerri/ytdlnis/assets/43435905/50358c3f-8192-4007-b586-fe6643ca4637)

**Comment by zaednasr** [comment]
This app has something better called filename templates
Go to folder settings.

And set anything. Not just website or playlist title

The website tag is %(extractor)s
The playlist tag is %(playlist_title)s


You can modify the template right in the download card if you want

**Comment by tusharchopra07** [comment]
![IMG_20231219_155214_195](https://github.com/deniscerri/ytdlnis/assets/128215171/c483938e-58e7-4b98-852f-658eb85dd0d5)

You can do this thing by adding this : %(playlist_title)s/%(title)s

For Website Then put this
 
%(webpage_url_basename)s/%(title)s

Example : I have downloaded a video from youtube the link is www.youtube.com/xyz/BeastorYeast

So the file will be 

youtube/BeastorYeast.mkv

**Comment by ZiadEl-kashif** [comment]
I'm sorry, but i have a question. i don't know all the intricate ins and outs of yt-dlp

How Does this "Filename template" work exactly?

Does it add the name of the website of which i downloaded the video from to the video title and then save the video in the typical ../YTDLine/video

Or does it actually give me what I wanted and create a subdirectory with the name of the website to save that video file IN?

because the naming is a little confusing. 
"Filename template" makes me think about the actual video file being downloaded, NOT the folder it's saved IN

sorry if it all comes off as rambling. Thank you for dedicating time for my request

**Comment by teddysulaimanGL** [comment]
As you can see, the app already suggested all of those fields that you can fill your template in, so enjoy
