### ISSUE TITLE
[BUG] Instagram Reels not downloading when shared from Facebook Reels

### ISSUE THREAD

**Issue by everypizza1** [deniscerri/ytdlnis#361]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
When trying to download videos through Instagram on Facebook Reels, I get this error:
`Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: wrong OPTS for --compat-options: manifest-filesize-approx`

**To Reproduce**
Go to Facebook, press Reels and look for a video with the Instagram icon next to their name. For example, this one is one that gave me the error:
![Screenshot_20231220-072844.jpg](https://github.com/deniscerri/ytdlnis/assets/82726593/15ce7766-265f-423f-937e-0aba1961bef3)
Then put the link in the search bar.

**Expected behavior**
The video should download as normal.

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 11
 - App Version: 1.7.0
 - Other Device Information: OnePlus Nord N10

**Additional context**

**Comment by zaednasr** [comment]
Have you tried switching ytdlp update channel? And then update it?

**Comment by everypizza1** [comment]
I switched to stable and it works now. Thanks for the help!


________________________________
