### ISSUE TITLE
[BUG] Postprocessing error

### ISSUE THREAD

**Issue by tudos4** [deniscerri/ytdlnis#362]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
Postprocessing error when yt-dlp try to merge formats

**To Reproduce**
video link: https://youtu.be/Eq0tABUW-eY
Id's: 251(audio)+315(video)
**Expected behavior**
To not error out and merge the formats succesfully

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 13
 - App Version:1.7.0 arm64 downloaded from github releases
 - Other Device Information:

**Additional context**

Searched on google for the error and found this: https://github.com/yt-dlp/yt-dlp/issues/871

Appareantly these special ffmpeg builds with those custom patches should help?:
https://github.com/yt-dlp/FFmpeg-Builds#ffmpeg-static-auto-builds

**Comment by zaednasr** [comment]
Show me the error it gives out from the download log?

**Comment by tudos4** [comment]
> Show me the error it gives out from the download log?

-N "25" --trim-filenames "203" --no-mtime --sponsorblock-remove "music_offtopic" --parse-metadata "%(channel,uploader,creator,artist|null)s:%(uploader)s" --parse-metadata "%(uploader)s:%(album_artist)s" --audio-quality "10" --sponsorblock-mark "all" --embed-chapters -f "315+251/315+ba/315/b" --embed-subs --sub-langs "en.*,.*-orig" --write-auto-subs -P "/data/user/0/com.deniscerri.ytdl/cache/downloads/30" -o "%(uploader,channel)s - %(title)s.%(ext)s" --replace-in-metadata "title" ".+" "GHOST OF TSUSHIMA PS5 Gameplay Walkthrough FULL GAME (4K 60FPS) Director's Cut" --replace-in-metadata "uploader" ".+" "Shirrako" --replace-in-metadata "uploader" " - Topic$" " " "[https://youtu.be/Eq0tABUW-eY](https://l.facebook.com/l.php?u=https%3A%2F%2Fyoutu.be%2FEq0tABUW-eY%3Ffbclid%3DIwAR2qrD7NOQt3_7g3ptzxZ0Xv5FFIT2nKGLvpoLkQboF2LlSsIICSgph9rrQ&h=AT3XaZ89RSs0RmutSMs19ZOHoBEVtIei9SHbJCWt3Uhbfv8PqMi3JtC08iaLiR7nkzPc9CzvyfOaaIgh5Rf8LZb-mjVELO2xeMUhS5RxOR3Wp_m1Gze98fMhFIr3FtbQtHyKz-u2KCcruA)"

ERROR: Postprocessing: Conversion failed!

**Comment by zaednasr** [comment]
Im using 2023.12.22.232735 nightly. Took me 3 and half hours but it downloaded it fine. Try updating your yt-dlp. Also i glanced at the yt-dlp issue and they say to use a different format. Updating the ffmpeg executable itself is not possible, unless you create an issue in [this repo](https://github.com/yausername/youtubedl-android/commits/master) to update it, then i could pull the latest version and use it in this app.

**Comment by tudos4** [comment]
> Im using 2023.12.22.232735 nightly. Took me 3 and half hours but it downloaded it fine. Try updating your yt-dlp. Also i glanced at the yt-dlp issue and they say to use a different format. Updating the ffmpeg executable itself is not possible, unless you create an issue in [this repo](https://github.com/yausername/youtubedl-android/commits/master) to update it, then i could pull the latest version and use it in this app.

Ok i try with nightly, in the meantime i downloaded the video and audio seperately and merged them manually.

I have a seperate video that errored out, tought not with this exact error. I will try with that.

**Comment by tudos4** [comment]
Oh wait,im already using that version

**Comment by zaednasr** [comment]
Its strange. The app supports resuming the download, so u can go to the errored tab and redownload it and try to push through it i guess. Its a really big file tho so that could be a factor.

**Comment by tudos4** [comment]
Well,i use different methods in the meantime, it seems there is already an issue to upgrade ffmpeg

**Comment by iAvoe** [comment]
I have reproduced this issue just now. The problem being the video stream is VP9 stream and ffmpeg can't use -c copy on it (at least it is on my case), it has to be re-encoded to a different format, after that you could do multiplex as usual.
