### ISSUE TITLE
[BUG] Postprocessing error

### ISSUE THREAD

**Issue by MagicWizard2345** [deniscerri/ytdlnis#369]
**Describe the bug**

ERROR: Postprocessing: file:/storage/emulated/0/1DM/Youtube/Perception Check (Official Music Video) - Tom Cardytom cardy.en.temp.srt.concat: Math result not representable

**To Reproduce**
--no-quiet --no-simulate --print "after_move:'%(filepath,_filename)s'" -N "8" --trim-filenames "223" --no-mtime --sponsorblock-remove "music_offtopic" --parse-metadata "%(channel,uploader,creator,artist|null)s:%(uploader)s" --parse-metadata "%(uploader)s:%(album_artist)s" --sponsorblock-mark "all" --embed-chapters -S "+hasaud,vcodec:h264,acodec:opus" -f "bv+ba/bv/b" --write-subs --sub-format "srt/best" --convert-subtitles "srt" --embed-subs --sub-langs "en, pt" --write-auto-subs -P "/storage/emulated/0/1DM/Youtube" -o "%(title)s%(uploader,channel)s.%(ext)s" "https://youtu.be/8HqLysSnnlQ"

**Expected behavior**
The download of the video

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.7.1
 - Other Device Information: S20FE 5G

**Comment by teddysulaimanGL** [comment]
This is simply isn't bug, this error is most likely due to bad config. Which is probably the language you set, and you shouldn't separate the comma with a space. It should be like this: `en,pt`

**Comment by tusharchopra07** [comment]
SponsorBlock database server is down right now !!!
Disable it
