### ISSUE TITLE
[FEATURE REQUEST] Ability to disable swipe in download card

### ISSUE THREAD

**Issue by Omegaplexx** [deniscerri/ytdlnis#370]
**Please describe.**
When I try to swipe thin chips in download card, I often suddenly swipe tabs (Video/Audio/Command).

**Describe the solution you'd like**
1. Add a checkbox in Settings → General → Swipe Gestures that will enable/disable tab swiping in download card.
2. Ignore a few pixels before swipe gesture is triggered.

Sorry for my bad English and thank you for this awesome app! :)

**Comment by zaednasr** [comment]
![Screenshot_20231228_061713](https://github.com/deniscerri/ytdlnis/assets/75589932/039cad25-4360-491c-aaf9-a583f2b11493)

**Comment by Omegaplexx** [comment]
Yeah, this dialog. Would be good if there was "Download card" checkbox

**Comment by zaednasr** [comment]
Oh you mean the multiple download card. Gotcha

**Comment by zaednasr** [comment]
This feature is implemented. Please wait for release

**Comment by Omegaplexx** [comment]
Thank you very much! \(^O^)/

**Comment by zaednasr** [comment]
check 1.7.2

**Comment by zaednasr** [comment]
Lol. Well that feature was needed there too.
Why do you want it disabled here. I don't get it

**Comment by NikunjKhangwal** [comment]
I got confused when i read the changelog of new version as well. What is exactly the "multiple download card" anyway? I thought it's when you download a full playlist consisting multiple videos.

**Comment by zaednasr** [comment]
The multiple download card is this 
![Screenshot_20240206_114732](https://github.com/deniscerri/ytdlnis/assets/75589932/b7d5794c-6c6b-433f-8136-86925a617464)

**Comment by NikunjKhangwal** [comment]
@zaednasr When you swipe between these small buttons the download card can switch between audio/video/command as well if you aren't precise. Since you can manually press the audio/video/command buttons on top to switch to them anyway, the swipe gestures aren't necessary here. This is what @Omegaplexx meant to say. Also I'm seconding this feature.

![IMG_20240206_161520](https://github.com/deniscerri/ytdlnis/assets/99175083/f532bf30-d00e-499c-8f84-7ca232227d84)

**Comment by Omegaplexx** [comment]
> Since you can manually press the audio/video/command buttons on top to switch to them anyway, the swipe gestures aren't necessary here


Yeah, that's exactly what I meant, thank you! My English is not very good, so I have trouble describing such things.

**Comment by zaednasr** [comment]
Ok I'll add it as an option

**Comment by zaednasr** [comment]
ok i added it now

**Comment by zaednasr** [comment]
Fixed in [1.7.3](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.3)

**Comment by NikunjKhangwal** [comment]
Thank you
