### ISSUE TITLE
[FEATURE REQUEST] "Save description" option in download card

### ISSUE THREAD

**Issue by Omegaplexx** [deniscerri/ytdlnis#372]
**Is your feature request available in yt-dlp? Please describe.**
Sometimes I need to save video description file with the video itself but enabling Save Description from the Settings every time is really annoying.

**Describe the solution you'd like**
It would be good if [Settings → Processing → Save Description] option was available in download card with Save Subtitles and Save Thumbnail features.

Thank you!

**Comment by zaednasr** [comment]
The amount of chips in the download card is getting too much. The option can easily be added but its not essential. Just make a save description command template and quickly add it as an extra command. Will be the same thing

**Comment by Omegaplexx** [comment]
Oh, you're right. Extra command could solve the problem. Didn't think about it at first time. Thank you :)
