### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Izzy1897** [deniscerri/ytdlnis#373]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 
 - App Version:
 - Other Device Information:

**Additional context**

**Comment by deniscerri** [comment]
??????????????????
