### ISSUE TITLE
[BUG] Could not download file

### ISSUE THREAD

**Issue by ghost** [deniscerri/ytdlnis#377]
**---LOGGER---**

`
 -N "3" --trim-filenames "203" --no-mtime --sponsorblock-remove "music_offtopic" --parse-metadata "%(channel,uploader,creator,artist|null)s:%(uploader)s" --parse-metadata "%(uploader)s:%(album_artist)s" --parse-metadata "%(release_year,release_date>%Y,upload_date>%Y)s:%(meta_date)s" --parse-metadata "%(album,title)s:%(meta_album)s" -f "140" -x --audio-format "m4a" -P "/data/user/0/com.deniscerri.ytdl/cache/downloads/15" -S "hasaud,acodec:aac,ext:m4a" --embed-metadata --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1" --ppa "ffmpeg:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" -o "%(uploader,channel)s - %(title)s.%(ext)s" --replace-in-metadata "title" ".+" "I'm with You" --replace-in-metadata "uploader" ".+" "Avril Lavigne" --replace-in-metadata "uploader" " - Topic$" " " "https://music.youtube.com/watch?v=_qHWIvq_WR4"
`

_WARNING: Unable to communicate with SponsorBlock API: The read operation timed out. Retrying (1/3)...
WARNING: Unable to communicate with SponsorBlock API: HTTP Error 502: Bad Gateway. Retrying (2/3)...
WARNING: Unable to communicate with SponsorBlock API: HTTP Error 502: Bad Gateway. Retrying (3/3)...
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: HTTP Error 504: Gateway Time-out
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: HTTP Error 504: Gateway Time-out_

**Comment by zaednasr** [comment]
Turn off sponsorblock in processing settings. Their api is down

**Comment by inavleb** [comment]
Suggestion before downloading:
	Check [status.sponsor.ajay.app](https://status.sponsor.ajay.app/) for server status.

**Comment by zaednasr** [comment]
@inavleb it would be better if yt-dlp did this on its own. You could make a request at them
