### ISSUE TITLE
[BUG] Extra commands aren't automatically added

### ISSUE THREAD

**Issue by Omegaplexx** [deniscerri/ytdlnis#381]
**Describe the bug**
Extra command templates are not automatically added as they were in previous versions.

**To Reproduce**
1. Create a command template, enable "Extra Command" switch and check "Audio" and "Video" checkboxes.
2. Try to download any video and check the current download command. You won't see any extras you created.

**Expected behavior**
I was counting on them being added automatically :-(

App Version: 1.7.1

**Comment by zaednasr** [comment]
That's unexpected. Can you show some screenshots

**Comment by Omegaplexx** [comment]
Sure! Here's a shoet video.
https://github.com/deniscerri/ytdlnis/assets/95503207/934d2d80-1ab8-4289-bbd0-42b9dc00bfdb

**Comment by zaednasr** [comment]
I can't reproduce but I'll look into it

**Comment by zaednasr** [comment]
check 1.7.2

**Comment by Omegaplexx** [comment]
It's working fine! Thank you very much :)
