### ISSUE TITLE
[BUG] Mixed up titles of downloaded music files

### ISSUE THREAD

**Issue by Mixcraftio** [deniscerri/ytdlnis#384]
**Describe the bug**
After downloading a playlist with videos that fail to download. The titles aren't correct, though the thumbnails are.

**To Reproduce**
- select a playlist to download that contains videos that fail to download
- download the playlist
- downloads placed after the failing videos will have mixed up titles

**Expected behavior**
After a video fails to download, the following videos should have the correct names.

**Other information**
 - Android Version: 14
 - App Version: 1.7.1
 - Other Device Information: Evolution X ROM, POCO F5

**Comment by zaednasr** [comment]
check 1.7.2
