### ISSUE TITLE
[BUG] The file name cannot contain Cyrillic characters

### ISSUE THREAD

**Issue by Korb** [deniscerri/ytdlnis#386]
**Describe the bug**
When saving a video from YouTube, the file name is formed with complete disregard for national characters. At least in the case of the Russian language.

**To Reproduce**
1. Open the application and specify the link https://www.youtube.com/watch?v=2qRCVeWJJwA
2. Filename Template: %(playlist_title)s. %(playlist_id)s. %(fulltitle)s
3. Saved video file name: "_ by _ (20240124).webm"

**Expected behavior**
Saved video file name: "Как валютный контроль обвалит рубль by Радио Свобода (20240124).webm".

**Screenshots / Video Recording**
![Screenshot_2024_0130_133420](https://github.com/deniscerri/ytdlnis/assets/3509797/eaf6b357-99e0-41bc-b37c-b59bf6bc5baa)
![Screenshot_2024_0130_133442](https://github.com/deniscerri/ytdlnis/assets/3509797/d35195b9-1de5-4aef-98ab-df39f83fbda2)
![Screenshot_2024_0130_133457_com cxinventor file explorer](https://github.com/deniscerri/ytdlnis/assets/3509797/e8ffbf28-787f-4f69-b2be-f73db1db7195)

**(please complete the following information):**
 - Android Version: 13
 - App Version:1.7.1
 - Other Device Information:

OS version: Funtouch OS 13 Global
Model: Vivo T1 4G / V2153
Hardware version: MP_0.1
Build number: PD22010F_EX_A_13.1.16.4.W20.V000L1
Baseband version: 6.HA.1.1.c2-00012-KD_ALL_PACK-1.6347.130
Kernel version: 4.19.157-perf+, 1 Tue Dec 5 10:36:31 CST 2023
Compile time: 5 Dec 2023 05:25:06
Android security update: 1 December 2023
Google Play system update: 1 November 2023

**Comment by zaednasr** [comment]
Do you have restrict filenames on?

**Comment by Korb** [comment]
Yes, you are right, this setting was enabled.  After disabling it, files began to be saved with the correct names.  Thank you!
