### ISSUE TITLE
Can't download YouTube Video

### ISSUE THREAD

**Issue by gigachaand** [deniscerri/ytdlnis#392]
**Describe the bug**
Can't download YouTube videos saying File name to long... ( I face this issue in YTdlnis previous version also.. I jus didn't report it.. 😅)

**To Reproduce**
Try to Download this Video - https://youtu.be/-yLBuimG-IM

**Expected behavior**
Download should started.. 

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.2
 - Other Device Information: Poco X5 5G MODEL - 22111317PI

**Additional context**

 -N "25" --trim-filenames "204" --no-mtime --parse-metadata "%(channel,uploader,creator,artist|null)s:%(uploader)s" --parse-metadata "%(uploader)s:%(album_artist)s" -f "399+251/399+ba/399/b" -P "/data/user/0/com.deniscerri.ytdl/cache/downloads/1" -o "%(uploader,channel)s - %(title)s.%(ext)s" --replace-in-metadata "title" ".+" "গান শুধু গান নয় , জীবনের প্রতিচ্ছবি । ভবা পাগলার গানে বরুণ ক্ষ্যাপা । ভাব সাগরে ভাবের মানুষ | #BAUL" --replace-in-metadata "uploader" ".+" "MALIK BHAROSA" --replace-in-metadata "uploader" " - Topic$" " " "https://youtube.com/watch?v=-yLBuimG-IM"

ERROR: unable to open for writing: [Errno 36] File name too long: '/data/user/0/com.deniscerri.ytdl/cache/downloads/1/MALIK BHAROSA - গান শুধু গান নয় , জীবনের প্রতিচ্ছবি । ভবা পাগলার গানে বরুণ ক্ষ্যাপা । ভাব সাগরে ভাবের মানুষ ｜ #BAUL.f399.mp4.part'
ERROR: unable to open for writing: [Errno 36] File name too long: '/data/user/0/com.deniscerri.ytdl/cache/downloads/1/MALIK BHAROSA - গান শুধু গান নয় , জীবনের প্রতিচ্ছবি । ভবা পাগলার গানে বরুণ ক্ষ্যাপা । ভাব সাগরে ভাবের মানুষ ｜ #BAUL.f251.webm.part'

**Comment by zaednasr** [comment]
Just make the title shorter

**Comment by gigachaand** [comment]
> Just make the title shorter

Ok got it.. 👍😁
