### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [deniscerri/ytdlnis#393]
On today's update, my scanner reported:

    ! repo/com.deniscerri.ytdl_107020004.apk declares sensitive permission(s): android.permission.READ_EXTERNAL_STORAGE android.permission.READ_MEDIA_VIDEO android.permission.READ_MEDIA_AUDIO android.permission.MANAGE_EXTERNAL_STORAGE android.permission.REQUEST_INSTALL_PACKAGES

Most of those I think I could identify (please correct me where I'm wrong – and be welcome to fill in for the others):

![image](https://github.com/deniscerri/ytdlnis/assets/6781438/09ad550b-8f72-47e1-a3f2-4f807bd8f804)

But what is `REQUEST_INSTALL_PACKAGES` for? Which apps does it want to install?

As for `DEPENDENCY_INFO_BLOCK`, this is probably easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by IzzySoft** [comment]
Thanks @aicynide!

> REQUEST_INSTALL_PACKAGES is for updating the app.

A self-updater? Is it opt-in – or enabled by default? Does it inform about where the APK is downloaded from?

> Since, i couldn't update from your repo, i updated it from settings.

Did you receive an error when trying to update from my repo – or what happened? If there's a problem on my end, I should see to get that fixed ASAP.

**Comment by IzzySoft** [comment]
> I mean last version in your repo is 1.7.2

Which came in here just 2 days ago, yes. And which happens to be the latest release available here as well. So what's wrong with it?

**Comment by teddysulaimanGL** [comment]
> But what is `REQUEST_INSTALL_PACKAGES` for? Which apps does it want to install?

Hey, @IzzySoft, as far as I know, yes, this permission is newly added for some reason. And yes, I think it's for built-in app updater, but I won't be certain. The app has it for a while now, and it can be triggered by pressing the app version number from Settings

**Comment by teddysulaimanGL** [comment]
As per where it takes the APK from, I'm pretty sure it's directly from source code repo

**Comment by zaednasr** [comment]
Request install packages has been there for a while. Same with the self updater. The apk it uses are from the GitHub repo

**Comment by IzzySoft** [comment]
@teddysulaimanGL @zaednasr thanks! So it's not running automatically, but only when explicitly triggered by hand? That's "opt-in" then, good.

Background of the question are the inclusion criteria with my repo (which in this regard match those of F-Droid.org). Quote:

> The app … must not download additional executable binary files (e.g. addons, auto-updates, etc.) without explicit user consent. Consent means it needs to be opt-in (it must not be harder to decline than to accept or presented in a way users are likely to press accept without reading) and structured in a way that clearly explains to users that they’re choosing to bypass the checks performed in this repo if they activate it.

So I see opt-in is given. @zaednasr could you include a short explanation so it's clear where the APK is taken from? Then I'd add this to the app's "allow-list" here, including a short explanation with the permission (as shown in above screenshot). The `DEPENDENCY_INFO_BLOCK` currently is just shown for transparency; that hint/info would go away if the block is gone – which would be good but is not a "must" :wink:

**Comment by teddysulaimanGL** [comment]
> So it's not running automatically, but only when explicitly triggered by hand? That's "opt-in" then, good.

Yes. But there's actually an option to automatic update check when opening the app which is enabled by default, and that's it. The app will still show you a confirmation dialog whether you want to proceed or not either way

**Comment by zaednasr** [comment]
The apk is taken straight from the github repo using the github api. You can go to utils. Update util to see for yourself

**Comment by IzzySoft** [comment]
I believe you, @zaednasr – but could that be made transparent, and the setting opt-in? It's reaching out to a non-free network service (yeah, so is grabbing YT content, but that one is clear to those using the app as they installed it because of that) which not everyone is comfortable with :wink:

As for the setting: it could e.g. be initially set to `NULL` – and when `NULL`, the app could ask for whether to turn it on or off. If at that point the context (checked at/downloaded from Github directly etc) is made clear, that's what GDPR calls "explicit and informed consent" :stuck_out_tongue_winking_eye: Thanks in advance!

**Comment by zaednasr** [comment]
The option to turn the auto updater off is present in the updating setting category.

The reason is on by default is so users are not stuck in older versions as there are constant changes and bug fixes.


I could note it down that the auto updater gets the apk from github no problem

**Comment by IzzySoft** [comment]
> The option to turn the auto updater off is present in the updating setting category.

Yes, but the policy in F-Droid repos (at least in mine and at fdroidorg) requires it to be opt-in, not opt-out. Maybe you could at least check the installer source (see [get the installer source of an android app](https://stackoverflow.com/a/70421558/2533433)), and only auto-enable it if that is either the app itself (after a self-update) or Android's package installer (when installed directly from a Github download)? If it's something else (F-Droid client, Obtainium, …) the user obviously wants to use that for update management.

> The reason is on by default is so users are not stuck in older versions as there are constant changes and bug fixes.

Understood – and that would be covered this way as well.

> I could note it down that the auto updater gets the apk from github no problem

That would be a good start, thanks!

**Comment by IzzySoft** [comment]
@zaednasr what you describe does not need `REQUEST_INSTALL_PACKAGES` then as installation would happen via "download notification" – or do I miss something? Apart from that, did the user consent to the update check itself?

> Consent means it needs to be opt-in […] and structured in a way that clearly explains to users that they’re choosing to bypass the checks performed in this repo if they activate it.

No offense meant; as someone not using the app myself I might simply miss something here. And I won't "argue" if that information is at least clear at the time of the download itself (gray zone maybe – but I'm neither a moralist nor a bureaucrat :wink:). Just pointing out how a "clean solution" would *IMHO* look like.

And to be clear on that point as well: I'm **not**, repeat, **not** saying **you** would want to "sneak something in" there. I tend to trust the authors of apps I include with my repo. But mistakes happen to the best of us – and it wouldn't be the first time that my scanners caught something brought in by e.g. some dependency. So it's an additional screening for the benefit of all – which everyone is free to bypass, but should be aware of the implications :wink:

**Comment by zaednasr** [comment]
I understand. I believe that permission was added in early development during experimentation. Will remove

**Comment by zaednasr** [comment]
Added the note and removed the permission in the latest release

**Comment by IzzySoft** [comment]
Thanks! No warning about the permission anymore. The only thing left now is:

```
! repo/com.deniscerri.ytdl_107030004.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Looks like you forgot to include those lines with your `build.gradle`?

**Comment by zaednasr** [comment]
oh right, my bad. Yes ill add them now

**Comment by Incog5** [comment]
Awesome app! Would it be possible to remove the excess permissions to all users photos and videos, which is a privacy concern for apps that have internet access. Similar functioning apps work without these permissions.
![Screenshot_20240607_083602](https://github.com/deniscerri/ytdlnis/assets/14378320/456bd714-a6a2-4191-be11-c527ac6b4125)
![Screenshot_20240607_080108_Permission controller](https://github.com/deniscerri/ytdlnis/assets/14378320/6858e79f-f514-4a88-a5b3-329c72c5ca9a)
![Screenshot_20240607_083020_Permission controller](https://github.com/deniscerri/ytdlnis/assets/14378320/9df899a7-df6c-4342-979b-e3319e462ac9)
![Screenshot_20240607_080127_Permission controller](https://github.com/deniscerri/ytdlnis/assets/14378320/5df88e08-8be2-4796-98b9-daa4144d6998)

**Comment by zaednasr** [comment]
Will look into this

**Comment by IzzySoft** [comment]
@zaednasr as your app requires at least Android 6, you could look into using Storage Access Framework (SAF) for this and let the user pick a location for download. Some locations would be off-limit then, though, including…

* the `Downloads/` directory
* the root of the SD card
* I guess everything in `DCIM/` and `Pictures/` as well, as that might require the corresponding media permissions @Incog5 is concerned about (I'm not entirely sure with that, though).

Same intro: Since Android 6, storage access has become a runtime permission. So @Incog5, even if an app declares it in its manifest, it doesn't automatically get them. Runtime permissions (aka AppOps) require the "user¹" to explicitly confirm them – meaning the app must fire up a dialog asking, which needs to be confirmed or the app would **not** get access to storage.

But you're correct of course, this would be a dilemma: You would need to grant those permissions in order to save downloaded files – but the permission would include almost the entire storage. While with SAF, you pick the location and the app only gets access to the location you selected.

¹ <sub>I try to avoid terms like "user" and "consumer" as it degrades humans to object, but sometimes it's hard to if it should be easy to understand, so apologies.</sub>

**Comment by Incog5** [comment]
To follow up, Seal is able to download to its default download directories **_without_** granting any access, no popup or SAF selection.

Video folder 
/storage/emulated/0/Download/Seal
 Audio folder /storage/emulated/0/Download/Seal/Audio

Newpipe requires user to select the folder, while Downloads can't be used, subdirectories inside Downloads can.

@IzzySoft you can test this, Seal will create it's own subdirectory in Downloads on app launch, are subdirectories that an app creates in Downloads exempt from user opt-in permissions?

**Comment by IzzySoft** [comment]
> `/storage/emulated/0/Download/Seal`

Ah, right! Yes, I've heard that. That should work, just directly into `Downloads/` would not.

> while Downloads can't be used, subdirectories inside Downloads can.

That ^^

> you can test this, Seal will create it's own subdirectory

I can't, no: neither am I using Seal, nor am I a developer. So this question should rather go to @zaednasr or another contributor of the project :wink: I'm just the founder and maintainer of the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid), where this app is listed at.

**Comment by zaednasr** [comment]
I believe this is more likely an issue for API 30 and above. because i tested for api 23-29 and they all needed the write/read permissions to actually move the finished file from the data internal directory to the downloads/ytdlnis folder. The app couldnt even tell if the file existed or not. So it needs to be there

For 30 and above i removed the permissions as the app appears to be working without them

**Comment by IzzySoft** [comment]
> For 30 and above i removed the permissions as the app appears to be working without them

Thanks! I still need to update the scanner to check for maxSdk on permissions…

Btw, today the scanner found another permission added: `android.permission.SYSTEM_ALERT_WINDOW`. Can you please give me the background, so I can add that to the "green list" as well?

**Comment by zaednasr** [comment]
I am experimenting with it. You know how the app shows the popup card when you share a link from youtube. Well in revanced, youtube goes picture in picture instead of just staying in the background.
Newpipe has that permission but it amounted to nothing. Ill have to investigate further how to achieve it.

**Comment by IzzySoft** [comment]
OK, thanks – then I'll leave the warning color in for now until you decided. Just let me know then what to put up – if it's still needed that is.

**Comment by zaednasr** [comment]
I ended up removing the permission for now in the latest release 1.7.7

**Comment by IzzySoft** [comment]
Great! Then the warning will disappear automatically once the new release has been pulled.

**Comment by IzzySoft** [comment]
> I ended up removing the permission for now in the latest release 1.7.7

@zaednasr looks like you have added it back. Do we need to roll back the last release, as the app violates our inclusion criteria now?

```
2026-03-12 19:32:59 local ERROR  ! repo/com.deniscerri.ytdl_108080004.apk declares flag(s): usesCleartextTraffic
2026-03-12 19:32:59 local ERROR  ! repo/com.deniscerri.ytdl_108080004.apk declares sensitive permission(s): android.permission.REQUEST_INSTALL_PACKAGES
```

Further, APK size reached 50 MB – our per-app size limit is 30 MB. That would be reason number 2 for removal then (you already have `legacyCompression` active, so there's hardly a way to reduce APK size). We can close one eye – but closing both would leave us blind 😉 

> Since beyond skd28 downloadable executables can't execute, the only way to make them executable is if they are part of jniLibs inside the app OR inside another app. So now downloadable packages are shipped as apks u can install. The app will immediately recognize them.

Oof. Quoting from our [App Inclusion Policy](https://izzyondroid.org/docs/general/AppInclusionPolicy/):

> The app **must not download additional executable binary files** (e.g. addons, auto-updates, etc.) without explicit user consent. Consent means it needs to be opt-in (it must not be harder to decline than to accept or presented in a way users are likely to press accept without reading) and structured in a way that clearly explains to users that they’re choosing to bypass the checks performed in this repo if they activate it.

(emphasis mine). So we need to clarify this **instantly** – or we will have to remove the app. Pinging @deniscerri as well here. I hate to put pressure, but if not clarified very soon, we'll have to take action. A policy is no good if not enforced. And neither your Readme, nor your app description, give any clue in this regard.

Right at app start, without any user interaction, this is what the network protocol shows:

<img width="459" height="632" alt="Image" src="https://github.com/user-attachments/assets/b6dd57c2-ecdc-4b08-8c7e-b5bd3fe0f937" />

So: definitely **WITHOUT CONSENT!** Next, settings, right after install, without any modifications:

<img width="457" height="531" alt="Image" src="https://github.com/user-attachments/assets/023296ff-261a-4df2-9eda-422f93e4cfee" />

Yes, it's "just for yt-dlp" – but it's on by default, which violates our inclusion policy. You can have a popup on first start, asking for consent. But you cannot simply have it on without the people using it having a clue. So, as much as I hate to do that, I now _have to_ put some pressure:

> [!WARNING]
> Please clarify within the next few days, or we'll have to remove the app. 😢

**Comment by deniscerri** [comment]
Hello sir
The previous update 1.8.7.2 had a filesize of 64.6mb.  The new update i put it back to the original size since i downgraded ffmpeg and made the new version downloadble within the app.

Request install packages is a new permission, because now the app will manage large packages like ffmpeg nodejs, through helper apps. App can install and delete them.
Also no addons are installed on startup or with no consent. The user has to navigate to the packages setting page and install the package himself.

Should i remove that permission and instead make the app launch an open intent for the apk? I could do that. And for deletion i guess just navigate the user to the app info page to delete it.

For yt-dlp, should i add a popup dialog when u first install to approve auto updates of yt-dlp?
Let me know, i will try to make a quick release with the fixes hopefully this weekend or next weekend.

**Comment by IzzySoft** [comment]
> The previous update 1.8.7.2 had a filesize of 64.6mb.

Yes, I know – which made me feel bad about bringing the size issue up here again. IIRC, we've talked about this before, and agreed on it (i.e. that we'd accept this as "exception"). But in combination with another factor, it requires closing two eyes 🙈 

> Request install packages is a new permission, because now the app will manage large packages like ffmpeg nodejs, through helper apps. App can install and delete them.

I've read that in the notes. And I assume these are actions explicitly triggered by the person using the app, and it can be assumed they know what they do when "pulling the trigger". As you just described, that then is **NOT** "without explicit user consent", and thus can be marked as "OK" (but we need to know such things, or we cannot mark them 😉 

> Should i remove that permission and instead make the app launch an open intent for the apk? I could do that. And for deletion i guess just navigate the user to the app info page to delete it.

If that is an option, it would be the "cleanest" approach indeed – and avoid raising doubt about the install permission. But that's not a "hard condition", though the one unable to trigger any alerts.

> For yt-dlp, should i add a popup dialog when u first install to approve auto updates of yt-dlp?

Now, **THAT** would be the only "hard requirement" indeed. See the quote above from our inclusion criteria: "Consent means it needs to be opt-in" – your current setup is "opt-out". So please, at least make this one opt-in (and yes, a popup dialog at first start is totally fine there – it also shows you respect the privacy, and it's no nagging as it would be a one-timer. Like: "Would you like to enable …? You can always change it later in the settings."

I totally see the need for updating the ytdlp binary. So if the install permission is required for that, it can't be helped (though if there are other means, they should be evaluated). Can you give some basic details regarding the "helper apps", please?

**Comment by deniscerri** [comment]
Alright i will apply these changes. I'll try to release a patch this weekend.
 
Helper apps are released in
https://github.com/deniscerri/ytdlnis-packages

They are just blank apps that only have jniLibs folder containing the executables like ffmpeg or nodejs.
Android allows to access such files as long as u note the package name in the manifest.
App when first launches or when the helper is installed, it grabs the libnode.zip.so file from it unzips it in its own home folder just as how it would unzip libpython.zip.so which is prebundled with the app.
That's the idea.

**Comment by deniscerri** [comment]
Im working on the changes now and i really need the permission REQUEST_INSTALL_PACKAGES
Otherwise the intent wont launch the app installer.

This is sample of code. contentUri is the apk file of the downloaded plugin within the app

```kotlin
val contentUri = FileProvider.getUriForFile(requireContext(), requireContext().packageName + ".fileprovider", file)
val intent = Intent(Intent.ACTION_VIEW).apply {
    setDataAndType(contentUri, "application/vnd.android.package-archive")
    flags = Intent.FLAG_GRANT_READ_URI_PERMISSION
}
installLauncher.launch(intent)
```

If there is any other way it is done, let me know.
The new changes are in this commit:
https://github.com/deniscerri/ytdlnis/actions/runs/23085849852/job/67062455648

**Comment by IzzySoft** [comment]
I'm consulting the team on that. A few culprits I see there are:

* the linked repo has no license. Thus we'd need to apply the `NonFreeAdd` to YTDLnis.
* those APKs would bypass our scanner, so that should probably be clearly pointed out.
* also clearly pointed out should be where they come from.
* already addressed: all those actions need to be opt-in (including the "update check" for the ytdlp binary we discussed above)

These are just my personal remarks. Waiting for the team to approve. But regardless of this, you should have a license declared on the other repo.

**Comment by deniscerri** [comment]
Added GPL-3 License to the repo.
Currently apart from nodejs, which is built from the .sh script i have put in the repository, the rest are built from youtubedl-android libraries
I extracted the jniLibs from them and made an apk out of them.

Also by the way i have tried to make reproducible builds with the .sh script but it was unsuccessful as it went past the execution time limit.
Locally to build nodejs it took my pc 5 hours, the CI ran for 8 hours and still was not finished and then failed automatically by timing out.

For anything else let me know, i will do it.

**Comment by IzzySoft** [comment]
> those APKs would bypass our scanner, so that should probably be clearly pointed out.

Has that been done? That's the currently critical point, as your updater otherwise goes against our policy (which is why it is currently "marked for removal if unsolved", which just popped up again today. As there's no new release since, I'll shift the deadline once more – but we need a clear answer to that. We cannot ignore our own policy – and it is there for a reason. See above "warning", and the suggestion:

> Yes, it's "just for yt-dlp" – but it's on by default, which violates our inclusion policy. You can have a popup on first start, asking for consent. But you cannot simply have it on without the people using it having a clue.

Remember we do not ask to remove the `REQUEST_INSTALL_PACKAGES` permission. You've explained its need, and that is acceptable. But it must be transparent. Auto-updates enabled by default, don't meet that requirement.

> i have tried to make reproducible builds with the .sh script but it was unsuccessful

Achieving RB is blocked here due to EventBus as well, I'm afraid (which is known to cause RB to fail).

**Comment by deniscerri** [comment]
You are free to test out the latest CI build as i have implemented the popup dialog in startup to confirm auto update preferences.
Also the REQUEST_INSTALL_PACKAGES permission is not related to the plugin system. Plugins cant be auto updated, user has to manually look up for updates within the app and download the plugin.

Please let me know what needs to be done to make REQUEST_INSTALL_PACKAGES transparent?

> Achieving RB is blocked here due to EventBus as well, I'm afraid (which is known to cause RB to fail).

I think you might be confused. This has nothing to do with EventBus. Eventbus is a library in the app, and RB works ok here.
I am talking about the https://github.com/deniscerri/ytdlnis-packages repository.
Building packages through termux-packages builder passed the build time limit in github.

**Comment by IzzySoft** [comment]
<img width="410" height="468" alt="Image" src="https://github.com/user-attachments/assets/f1556b0d-6f1d-4ceb-8ee4-b5951e71eccc" />

That is opt-out; the toggles need to be off by default. Also, the first one lacks the clarification that those downloads bypass our additional scans. Sorry, but your app has the installer permission – so how shall we ensure there are no installs of app updates, bypassing our scans? We're already closing a lot of eyes there, you cannot make our entire team blind 🙈 Ideally, you'd remove this part entirely (if you think it's needed for those installing from Github, a separate build flavor could be used there). The app checking for updates itself makes no sense, when updates should happen by the "store".

> Eventbus is a library in the app, and RB works ok here.

The former is clear, the latter would be news to me. We have several apps stuck with that, RB failing because of that library.

**Comment by deniscerri** [comment]
@IzzySoft It has been a while since i have dealt with users of this app and one thing i have learned is that the vast majority of people just roll with the default, and would complain if something is not configured to work by default.

The dialog here is undismissable, so user has to confirm his choices. Either way i made them on by default because i know the average user will just accept them, and that is for the best because the app needs constant updates of yt-dlp to keep working smoothly. Because of the nature of the app, the app cant just stay with an old version forever as youtube and other websites make up new ways to prevent downloading.
If i made them off by default and 99% of users just click ok, i will be flooded with complains why doesnt the app work. 

As for the installer permission, what needs to be done? Axe it completely, and use a downloadmanager with a notification so user has to install it manually? I guess that will be sufficient?

As for the eventbus thing im confused. When i added eventbus library a long time ago, it didnt affect the github workflow and the app built fine, and neither i had a complaint from you or the fdroid team.
Also eventbus was added back in 2024...

https://github.com/deniscerri/ytdlnis/blob/33de21bce9590b5095bebb80c3b5b6e50caf11e0/app/build.gradle

**Comment by IzzySoft** [comment]
> i made them on by default because i know the average user will just accept them

yeah, that is the argument of the ad industry as well: tick them by default, folks are impatient and will just click next (which they would also if ticked off, which we don't want). But OK, for `yt-dlp` I understand that: it indeed needs frequent updates, or things will break; which people then would blame on the app, if they don't know better (which too many don't). I'd suggest to mention that with the explanation to that toggle somehow, e.g. `as yt-dlp _needs to be_ updated pretty often _to stay working_`. That would then also make clear why that box is "pre-ticked".

Trouble is the other one. Those update checks make no sense, if the app is installed from and maintained by an "app store". This one is preferably removed (at least for the build we would use). So if you insist in keeping that, it **must** be toggled **off** by default – and the accompanying test **must** name the implications (like, that it would bypass additional screening performed by the app store the app was installed from).

> When i added eventbus library a long time ago, it didnt affect the github workflow and the app built fine, and neither i had a complaint from you or the fdroid team.

Sure it builds fine – just often not deterministically. And thus the F-Droid team never complained, as your app is **not** established as [Reproducible Build](https://izzyondroid.org/about/security/ReproducibleBuilds/) there (they just build it, and sign it themselves). We distribute the APK you build and sign, and our RBs confirm whether we can build an identical APK (apart from your signature of course, as we have neither your keystore nor your credentials, nor should we). And that is where EventBus often blocks: not building deterministically, we cannot match your APK, as always "some bytes differ". I write "often": I see it mostly works in your case (out of 15 releases, only 2 failed). So OK, seems safe to drop _that_ topic here (apologies I brought this up at all, given the success rate of RBs for your app, I should have checked that first – it was just too often the culprit causing us headaches there, and usually costing us hours without being solvable; must be some specific functionality then which you do not use from it).

**Comment by deniscerri** [comment]
Alright. i will add the note you suggested for ytdlp and remove the app one completely from the dialog on fdroid, izzy builds. also have the app auto update off by default and not search for new versions from github on settings on your builds.
For that i guess i need to make a separate flavour?
if you are able to can you provide me what is the proper way to do it? Storing a variable somewhere and there make logic against it? 
Ill make up the changes asap this weekend.

For eventbus either way ill note it down perhaps ill find an alternate library that does the same thing. all i use eventbus is to pass progress data from workmanager to a fragment/activity. workmanagers livedata is not accurate and some progress is lost through it thats why i found a separate library

**Comment by IzzySoft** [comment]
> For that i guess i need to make a separate flavour?

If you want to keep "the app one" for people downloading from e.g. GitHub: yes, that would be the best approach.

> if you are able to can you provide me what is the proper way to do it?

You mean, how to configure [build variants](https://developer.android.com/build/build-variants)? I'm no Android dev, so that link is the best I can give you on this.

> Ill make up the changes asap this weekend.

🤗

> For eventbus either way ill note it down …

As long as it does not cause any trouble, there's no need to replace it. But if you want to be ready "Justin Case", I can copy you something from my local notes (not tested/confirmed yet, hence not yet in our documentation):

* [Android event bus alternative using Kotlin Flow](https://scribe.rip/android-better-alternative-for-eventbus-and-local-broadcast-receivers-using-flow-c0d0ae3e8344)
* [minibus](https://github.com/jneat/minibus)

From what you describe, the first one seems suitable – unless it proves as not reliable enough (matching your experience with workmanager), in which case the second might come in. Feedback on those welcome, should you try – so I can update my notes, and maybe even make them public with [our documentation](https://izzyondroid.org/docs/).

**Comment by deniscerri** [comment]
@IzzySoft please try this commit
https://github.com/deniscerri/ytdlnis/commit/13e9bee408f6124a96a142efd3e278df1256de89

Added build flavors, you should use the foss flavor, ill use the github flavor
I also removed eventbus with this one.

**Comment by IzzySoft** [comment]
Initial popup looks good, thanks! But… maybe you forgot the settings screen? See the second toggle here:

<img width="449" height="541" alt="Image" src="https://github.com/user-attachments/assets/484d1e67-a6bb-47c4-a753-33a6ade93da1" />

(seems only the setting remained. After force-closing and restarting the app, I see only a single connection made to Github, which would be the one for yt-dlp then)

**Comment by deniscerri** [comment]
ah yes. i have forgotten these. I'll push in a bit

**Comment by deniscerri** [comment]
Try the commit
https://github.com/deniscerri/ytdlnis/commit/11dac2c133b2eb1d821f904f94531d6cf580fdd2

**Comment by IzzySoft** [comment]
<img width="447" height="555" alt="Image" src="https://github.com/user-attachments/assets/8b8dd480-6020-4e54-a135-fc9c14bbc81c" />

still there.

**Comment by deniscerri** [comment]
Can you doublecheck, maybe you assembled the github flavor by mistake?

**Comment by IzzySoft** [comment]
I didn't assemble anything. I simply took the APK your workflow produced from that commit 😉

**Comment by deniscerri** [comment]
@IzzySoft well the workflow will always build the github flavor, which ill use in future github releases
Fdroid and you should assemble the foss one.

**Comment by deniscerri** [comment]
Or should i assemble both in the workflow file?

**Comment by IzzySoft** [comment]
If you want me to verify: yes, I'd need a signed APK 😉

**Comment by deniscerri** [comment]
Try now
https://github.com/deniscerri/ytdlnis/commit/2511147b9fdb504a07ec56845176ee4f81232f79

**Comment by IzzySoft** [comment]
Looks good, thanks! 🤗

**Comment by IzzySoft** [comment]
Now just for clarification, as `android.permission.REQUEST_INSTALL_PACKAGES` is still there: what exactly is it needed for with the foss flavor? I tried to read this from the top, but am clearly confused:

> REQUEST_INSTALL_PACKAGES is for updating the app.

no longer true now, for the foss variant. Then:

> This is sample of code. contentUri is the apk file of the downloaded plugin within the app

But a little later:

> Also the REQUEST_INSTALL_PACKAGES permission is not related to the plugin system.

🤪 Guess I'm lost in translation there 🙈 So: is it still needed with the foss version? If so, what for? If not, will you remove it?

**Comment by deniscerri** [comment]
yes I'll remove it. I'll let you know

**Comment by IzzySoft** [comment]
Wonderful, thanks! 🤗

**Comment by deniscerri** [comment]
@IzzySoft 
https://github.com/deniscerri/ytdlnis/actions/runs/24282144646/job/70905556828
The permission should be gone in the foss version.

I decided to keep the permission in github releases version though, because even though you can manually install the package after its downloaded, the user has to restart the app for changes to take effect, but when the app installs the apk, it does that automatically.

**Comment by IzzySoft** [comment]
Thanks! Confirming the permission to be gone with the FOSS release. Of course, the Github release is a different duck and not to be shot at: that's not the one we will take. Updated at our end to match `/foss-arm64-v8a/i` for the next releases.

**Comment by deniscerri** [comment]
@IzzySoft so now i have to include the foss apks aswell in the release
or do you grab them from the release commit?

**Comment by IzzySoft** [comment]
We always fetch APKs from their corresponding releases, yes. So what's not attached there, cannot be fetched…

**Comment by deniscerri** [comment]
Alright, noted

**Comment by IzzySoft** [comment]
Thanks! Just for the record: we only fetch the foss-arm64 one (but others might be interested in the other ABIs as well).

Shall we wait for the next release to pass, before we close this issue here?

**Comment by deniscerri** [comment]
I don't mind including every abi. also yeah no problem

**Comment by IzzySoft** [comment]
Any ETA for the next release? We still get the warnings here on each check.

**Comment by deniscerri** [comment]
sorry about this. i have been pushing features people keep telling me to implement this implement that 😅

I'll do one this weekend for sure

**Comment by IzzySoft** [comment]
Thanks! Yeah, people can be pushy. And repo maintainers, too, sometimes 🙈

**Comment by deniscerri** [comment]
@IzzySoft new version is up

**Comment by IzzySoft** [comment]
But only the github variant attached. Can you attach the `foss` ones as well?

Btw: the badge on your Readme maybe should point to https://apt.izzysoft.de/packages/com.deniscerri.ytdl instead of android.izzysoft.de (the latter is just a "convenience integration", lacking some features).

**Comment by deniscerri** [comment]
@IzzySoft Added the foss apks
Also updated the readme url

**Comment by IzzySoft** [comment]
Thanks! Got pulled in fine, and are RB 🥳 Can you shortly explain what `usesCleartextTraffic` is needed for? Our scanner yielded that when pulling the APK over.

**Comment by deniscerri** [comment]
@IzzySoft If i remember correctly, i added it when debugging webview problems. If its problematic and not really needed, i can remove it
Actually now that i think of it i probably dont need it.
This was back when tiktok was not loading in webview, but i managed to make it work later on without it

**Comment by IzzySoft** [comment]
When it's needed, we'd simply add a proper explanation. When it's not needed, it's of course better not there 😉 I cannot tell which it is – so just let me know.

**Comment by deniscerri** [comment]
@IzzySoft i removed it in 1.8.9.1

**Comment by IzzySoft** [comment]
Thanks! Guess all solved then here, and we can close (we always can reopen if needed).
