### ISSUE TITLE
[FEATURE REQUEST] Embed the thumbnail into the video

### ISSUE THREAD

**Issue by Ehab-d** [deniscerri/ytdlnis#396]
**Is your feature request available in yt-dlp? Please describe.**
I don't know. But it's easy to implement.

**Describe the solution you'd like**
Instead of downloading the thumbnail separately, YTDLnis can merge the thumbnail with the video file.

**Comment by zaednasr** [comment]
Apart from webm videos, the other videos have embed thumbnail command on by default. Webm videos dont support embed thumbnail. Just enable embed thumbnail in your processing settings and you are good to go
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/9382001f-44d8-4583-8ca7-bd3c5cd1ebef)
