### ISSUE TITLE
[FEATURE REQUEST] "go straight to download" setting 

### ISSUE THREAD

**Issue by fcassia2017** [deniscerri/ytdlnis#397]
**Is your feature request available in yt-dlp? Please describe.**
My workflow with ytdlnis is always coming from the official YouTube app after watching a video, copying the link then pasting it into ytdlnis for download. 

However the default download process happens IN THE BACKGROUND. The download job is hidden from view, and I have to tap two or three times into the downloads icon to finally watch the animated progress bar. It Is a very well done and visually pleasing progress bar that I wonder why do you hide the process by default. This repeated tapping to see the progress of a download I just started is very frustrating. 

**Describe the solution you'd like**
I would like the App to have a setting called "go straight to download view" that when enabled switches immediately to the download view after a download is started, with no extra tapping. 

**Describe alternatives you've considered**
Using other Android YT downloader

**Additional context**
None

**Comment by zaednasr** [comment]
just tap the download notification, it will lead you straight to the active downloads page.
or better yet, just tap the result card in the middle and u will have a minified version of the progress shown
