### ISSUE TITLE
[BUG] MIUI 13 Android 13 Crash on clicking app icon.

### ISSUE THREAD

**Issue by Danik2343** [deniscerri/ytdlnis#400]
Crashing when I clicking App icon.
Version: 1.7.2
Log:
[09_02-21-55-12_397.zip](https://github.com/deniscerri/ytdlnis/files/14225367/09_02-21-55-12_397.zip)

**Comment by Danik2343** [comment]
Crash log (only crash):
[crash-com-deniscerri-ytdl-09_02-21-55-17_315.zip](https://github.com/deniscerri/ytdlnis/files/14225378/crash-com-deniscerri-ytdl-09_02-21-55-17_315.zip)

**Comment by zaednasr** [comment]
Your phone didn't migrate well with the new database. Just fresh install
