### ISSUE TITLE
[FEATURE REQUEST] Simplify containers formats

### ISSUE THREAD

**Issue by Rikiub** [deniscerri/ytdlnis#401]
When you download a file, you have the option to select a **container**, for example, in audio we have *m4a, mp3, opus* and in video *mp4 and mkv*. However, many containers are **redundant**.

- [Webm](https://en.wikipedia.org/wiki/WebM) is a subtype of [MKV](https://en.wikipedia.org/wiki/Matroska)
- [Opus](https://en.wikipedia.org/wiki/Opus_(audio_format)#Containers) is used in [Ogg](https://en.wikipedia.org/wiki/Ogg)
- [Aac](https://en.wikipedia.org/wiki/Advanced_Audio_Coding#Container_formats) and [Alac](https://en.wikipedia.org/wiki/Apple_Lossless_Audio_Codec#Codec) is used in [m4a](https://en.wikipedia.org/wiki/MP4_file_format#Data_streams)

**Webm** does not have much player compatibility (and does not support basic metadata like thumbnails).

Also, formats like `flac` and `wav` are used for **lossless compressed files**, but it doesn't make sense since most web pages compress their files in formats like `mp3`. You should prioritize containers with **lossy compression** to avoid confusion.

To add, in `yt-dlp` using the `--audio-format` command will **convert** the file. This will increase the final file size without any difference in quality.

**Is your feature request available in yt-dlp? Please describe.**

You can change the final container of a file with this command:

`--remux-video "webm>mkv:opus>ogg:aac>m4a:alac>m4a"`.

For example: `webm` will be remuxed to `mkv` without **convert/recode the file**.

**Describe the solution you'd like**.

Simplify the list of containers to the most essentials, like:

- **Video**
	- mp4
	- mkv
- **Audio**
	- mp3
	- m4a
	- ogg

By default, it should look for the **best** format, but in case the user selects another container, the **list of formats** could be checked. If the **format extension** is not found in the **selected container**, it should notify through the interface that *"file would be converted"*.

**Comment by zaednasr** [comment]
@Rikiub dm me on telegram so we can talk about with others and find a solution.

**Comment by SyCoREAPER** [comment]
Please leave the download settings exactly as they are.

They are useful even if some containers seem "redundant". If individuals (I'm not referring to you OP) need something with "less confusing" options, there are plenty of other apps out there.

I love this app precisely for the control it gives.

**Comment by zaednasr** [comment]
@SyCoREAPER i decided to not change it. At the end of the day, if you dont like some containers, dont choose them. As you said the app gives you options, its up to you to use them or not.

Closing this as i forgot :)
