### ISSUE TITLE
[BUG]"Save Subtitles" gives no files. "Save Automatic Subtitles" gives 2 files.

### ISSUE THREAD

**Issue by rusegithub** [deniscerri/ytdlnis#403]
I'm using this in Revanced. Thanks; it's great.

When I use the setting "Save Subtitles" - with the Subtitle Languages set to "en.*" I don't get a subtitle file.

When I have both "Save Subtitles" and "Save Automatic Subtitles", I get two files.

I don't want two files because MX Player Pro on my phone shows both sets of subtitles at the same time - and it's cumbersome to have to go into subtitles and turn one of them off.

I just want one file, containing the best version available.

I don't actually know where you get the "Save Subtitles" version from. Is that when the uploader has uploaded a separate subtitle file?

And I presume "Save Automatic Subtitles" gets the automatically generated "Subtitles/closed captions". Is that right? I obviously want to avoid that file if there is a proper subtitle file.

But I do want a subtitle file. (I don't want them embedded and that setting is off.)

What should I be doing?

 - Android Version: 14 
 - YTDLnis Version: 1.7.2 [arm64] 
 - yt-dlp Version: 2023.12.30
 - Other Device Information: Samsung S9. Noble ROM.

EDIT: Here's the video I've been testing on https://www.youtube.com/watch?v=msXUHX9yoZ0

**Comment by deniscerri** [comment]
In the history tab tap the video you downloaded and tap the command chip. Send it here please so i can know what settings you used

**Comment by rusegithub** [comment]
That was quick. Thanks. You've caught me off guard!

I can't see a history tab. Do you mean in YouTube (Revanced)? Or in YTDLnis?

And I've no idea what the command chip is. 

I'm sorry.

**Comment by rusegithub** [comment]
OK, I've worked it out. You mean the downloads tab.

The following is copied from the Command button.

This first one is when I just had "Save Subtitles" selected in Settings. No subtitle file is downloaded, only the mp4 video.

-N "3" --trim-filenames "204" --no-mtime --sponsorblock-remove "music_offtopic,selfpromo,sponsor,interaction" --parse-metadata "%(channel,uploader,creator,artist|null)s:%(uploader)s" --parse-metadata "%(uploader)s:%(album_artist)s" --sponsorblock-mark "all" --embed-chapters -S "+hasaud,vcodec:h264,acodec:aac" -f "137+140/137+ba/137/b" --write-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*" -P "/data/user/0/com.deniscerri.ytdl/cache/downloads/9" -o "%(uploader,channel)s - %(title)s - %(id)s.%(ext)s" --replace-in-metadata "title" ".+" "Lids 101: Restoring Your Hat" --replace-in-metadata "uploader" ".+" "Lids" --replace-in-metadata "uploader" " - Topic$" " " "https://youtu.be/msXUHX9yoZ0"

This next one is when I had "Save Subtitles" and also "Save automatic subtitles" selected in Settings. This time I get the mp4 video and 2 subtitle files: .en-orig.srt and .en.srt

-N "3" --trim-filenames "203" --no-mtime --sponsorblock-remove "music_offtopic,selfpromo,sponsor,interaction" --parse-metadata "%(channel,uploader,creator,artist|null)s:%(uploader)s" --parse-metadata "%(uploader)s:%(album_artist)s" --sponsorblock-mark "all" --embed-chapters -S "+hasaud,vcodec:h264,acodec:aac" -f "137+140/137+ba/137/b" --write-subs --sub-format "srt/best" --convert-subtitles "srt" --write-auto-subs --sub-langs "en.*" -P "/data/user/0/com.deniscerri.ytdl/cache/downloads/10" -o "%(uploader,channel)s - %(title)s - %(id)s.%(ext)s" --replace-in-metadata "title" ".+" "Lids 101: Restoring Your Hat" --replace-in-metadata "uploader" ".+" "Lids" --replace-in-metadata "uploader" " - Topic$" " " "https://youtu.be/msXUHX9yoZ0"

---
I would also like to tell you that after the video is downloaded, in my notification YTCLnis says "Open file". That's nice and when I click on the first one above (the one that had "Save Subtitles" selected), it opens in MX Player because I've set that app to open mp4 files by default.

But when I click on "Open file" with the other video (the one that had "Save Subtitles" and "Save Automatic Subtitles" selected), it obviously doesn't recognise that it's a video file and only offers me Code Editor and Text Editor to open the files (see attached screenshot). Android must be looking at one of the subtitle files instead of the file I really want to open: the video file. I can still open the video file but I just have to go and find the file and then play it.

![YTDLnis_1](https://github.com/deniscerri/ytdlnis/assets/574761/5f4a9d2c-0049-454d-a1eb-74a3f945ec8a)

**Comment by rusegithub** [comment]
I deleted my first reply (I was being stupid) and slightly amended the important reply above. 

But if you've already read that reply there's nothing important new. 

Again, thanks for your help and the great app. Hopefully we can get top the bottom of this.

**Comment by zaednasr** [comment]
You are correct the app got the sub file instead of the video. I think i can fix this in the next release, no worries

**Comment by zaednasr** [comment]
fixed

**Comment by zaednasr** [comment]
Fixed in [1.7.3](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.3)
