### ISSUE TITLE
[BUG] When adding two or more urls to download app does not change to selected format first time

### ISSUE THREAD

**Issue by MrBKA95** [deniscerri/ytdlnis#407]
**Describe the bug**
When you add two or more urls and you choose the video & audio formats for the links the format change is not recognised by the app and it stays at Best Quality for the first time. If you back out of the menu and press 'Download All' again then the selected formats are shown. Can you fix the bug to show the formats straight away like previous versions.

**To Reproduce**
Add two or more urls to search bar and then click Download All. Select formats and the bug should then show up.

**Expected behavior**
The selected formats should be recognised first time.

**Screenshots / Video Recording**

https://github.com/deniscerri/ytdlnis/assets/105092892/922823d9-3021-4e99-ac92-c9475c1039de

**(please complete the following information):**
 - Android Version:  14
 - App Version: 1.7.2
 - Other Device Information: Samsung Galaxy S21

**Comment by zaednasr** [comment]
Ok noted

**Comment by zaednasr** [comment]
Looks like the app was preventing the items from updating if you were inside incognito. For now turn it off and it will work. Next release this wont be an issue.

**Comment by zaednasr** [comment]
Fixed in [1.7.3](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.3)
