### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sasikarank** [deniscerri/ytdlnis#409]
I am Using 1.7.2 latest version on Android 12 Arm64 Device. When I try to download a video from Instagram through share button, i got this issue. 
WARNING: [Instagram] C3pj6lUx8dz: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C3pj6lUx8dz: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

**Comment by zaednasr** [comment]
Use cookies

Cookies are a way of downloading private videos or videos that can only be downloaded when you have access to that website.

"How to create one?"
1. Go to "More" screen
2. Find "Cookies" button and press it
3. Enable cookies and press "New Cookie" button
4. Type the supported website address (check the "Supported sites" button below), then press "Get Cookies" button
5. Log in to your account. After you successfully logged in to your account, press "OK"
Then try again

If it doesnt work then as the error says, report the issue at that link.

**Comment by teddysulaimanGL** [comment]
> rate-limit reached or login required. Use --cookies…

It said this. You need a cookie by log in to that site
