### ISSUE TITLE
[BUG] Share it

### ISSUE THREAD

**Issue by alabotski** [deniscerri/ytdlnis#417]
**Describe the bug**
When I use "Share it" on android
I can't download any video
But when I paste the link into the application itself, everything downloads correctly

**To Reproduce**
Open any youtube url. And use share

**Expected behavior**
All video should download

**Screenshots / Video Recording**
[error 1.txt](https://github.com/deniscerri/ytdlnis/files/14472962/error.1.txt)
[error 2.txt](https://github.com/deniscerri/ytdlnis/files/14472963/error.2.txt)
[error 3.txt](https://github.com/deniscerri/ytdlnis/files/14472964/error.3.txt)

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.3
 - Other Device Information:

**Additional context**

**Comment by tusharchopra07** [comment]
Ah please update to new version (clean install is recommended)
You can back-up your settings using back-up and restore feature

**Comment by zaednasr** [comment]
^
