### ISSUE TITLE
Publish ARM releases in lzzyOnDroid

### ISSUE THREAD

**Issue by hosnifraj9** [deniscerri/ytdlnis#418]
I recently found this app and when I wanted to download it, I didn't find an option to download it and I am sure because it doesn't support my device but there are ARM releases in Github releases. 

I hope ARM releases gets added to lzzy so I can easily get updates.

**Comment by hosnifraj9** [comment]
I don't know or maybe there is no way to change the label **bug** to the related one.

**Comment by zaednasr** [comment]
I dont publish them there. You need to talk with @IzzySoft

**Comment by zaednasr** [comment]
Also i think this is a good time to talk about it being added to the main fdroid repo as i know your repo has space constraints

**Comment by hosnifraj9** [comment]
> I dont publish them there. You need to talk with @IzzySoft

Aren't you who uploads apks there?



> Also i think this is a good time to talk about it being added to the main fdroid repo as i know your repo has space constraints

Yeah, don't forget to add arm support there. I think it's not that hard to add it to fdroid repo

**Comment by zaednasr** [comment]
I only publish here in the official repo.  Izzy gets the apk and then publishes it in his own repo

**Comment by hosnifraj9** [comment]
By mistake ...

**Comment by hosnifraj9** [comment]
> I only publish here in the official repo. Izzy gets the apk and then publishes it in his own repo

what is this official repo?

**Comment by zaednasr** [comment]
The one you are currently talking in 😅

**Comment by hosnifraj9** [comment]
if you are talking lzzy repo, you said you are not who uploading to it

**Comment by zaednasr** [comment]
Yeah because it's not my repo. Izzy checks my releases then gets the apk and shares it in his repo

**Comment by hosnifraj9** [comment]
> I only publish here in the official repo. Izzy gets the apk and then publishes it in his own repo

Oh, I understand now, you mean you share releases here in the **app github repo**. Okay, we will close the issue until the app is added to fdroid?

**Comment by zaednasr** [comment]
Leave it open in case izzy replies so he can talk with fdroid to add it there

**Comment by IzzySoft** [comment]
The APK is already over the size limit here (slightly, so I did not yet "yell"), so a "fat build" (multi-arch) is out of question. So is having multiple archs separately (packageNames would collide, so no way). Switching to armeabi only would leave some of the newer 64bit-only devices out. So not much that can be done here.

As for F-Droid, I won't talk with them to add it there, sorry – I'm currently [not active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447). But of course you are free to do so. For some pointers:

* [the process of integrating an app with F-Droid](https://android.izzysoft.de/articles/named/fdroid-intro-2#rfp)
* [Quick path to get your app into F-Droid](https://gitlab.com/-/snippets/1896503#quick-path-to-get-your-app-into-f-droid)
