### ISSUE TITLE
[FEATURE REQUEST] cache to a writable SD card directory when the output folder is not writable.

### ISSUE THREAD

**Issue by bartoszek** [deniscerri/ytdlnis#419]
**Is your feature request available in yt-dlp? Please describe.**
* Currently when setting the output folder to non writable SD card directory e.g: `/storage/{uuid}/YTDLnis/`
, downloads get cached to internal storage.

**Describe the solution you'd like**
* when output is a non writable SD card directory cache downloads to `/storage/{uuid}/Android/data/com.deniscerri.ytdl/files/` then move merged downloads to the non writable output folder.

**Describe alternatives you've considered**
* currently one can set the output path to a writable SD card directory, but it's suboptimal soliton as this path is not indexed by android gallery.

**Comment by zaednasr** [comment]
What's the issue with having the app store them in internal folders? 

It's there a reason you want them in the data folder instead

**Comment by bartoszek** [comment]
> It's there a reason you want them in the data folder instead

I'm hitting the internal memory limit when downloading long VODs
* ~5h VOD at 720p can reach 6GB.
* requires ±12GB to merge.
* On 64GB phone this requires 25% free space.

**Comment by zaednasr** [comment]
Noted

**Comment by bartoszek** [comment]
Currently I'm using Automate flow monitoring `/storage/{uuid}/Android/data/com.deniscerri.ytdl/files` and moving new files to the `/storage/{uuid}/YTDLins`. But this result in YTDLnis loosing control of those files.

**Comment by zaednasr** [comment]
Yes that's true. The app downloads in chunks that later get coupled so this will crash the download process.

Moving the cache to data is easy i guess. No problem

**Comment by zaednasr** [comment]
check 1.7.4
