### ISSUE TITLE
Get direct link 

### ISSUE THREAD

**Issue by ahmedaa6122** [deniscerri/ytdlnis#42]
I try use youtubedl to get direct link but its lag can i know how do it without lag please

**Comment by deniscerri** [comment]
Can you give more details and show a video recording?

**Comment by ahmedaa6122** [comment]
This app use youtubedl android  library i also use it in my app but its lag when get direct link but in ytdlnis app its not lag how you do thats ?

**Comment by deniscerri** [comment]
Well idk what kinda lag you are talking about. What do you mean by direct link?

**Comment by ahmedaa6122** [comment]
Can you tell me what the file or code or class that's used to get direct link in this app

**Comment by deniscerri** [comment]
Join the discord and we can talk more in detail

**Comment by ahmedaa6122** [comment]
Send discord link please

**Comment by soymadip** [comment]
> Send discord link please 

See in homepage
