### ISSUE TITLE
[FEATURE REQUEST] supported web addresses.

### ISSUE THREAD

**Issue by bartoszek** [deniscerri/ytdlnis#421]
Just noticed that `supported web addresses` list is empty for YTDLnis.

Could we please fill it with the major video sharing websites links, those making YTDLnis shows up in the `open with` dialog for matching  URLs?

e.g: supported web addresses for the no longer maintained `YouTubeDownloader` app:
 ![20240306_233133.jpg](https://github.com/deniscerri/ytdlnis/assets/1213348/cab3f88b-60d7-4b2d-a516-2236da2bb29d)

**Comment by zaednasr** [comment]
check 1.7.4
