### ISSUE TITLE
Don't activate PiP on YouTube ReVanced

### ISSUE THREAD

**Issue by bremaya** [deniscerri/ytdlnis#422]
**Is your feature request available in yt-dlp? Please describe.**
When using the download button in the YouTube ReVanced player, I would like PiP mode not to be activated.

**Describe the solution you'd like**
Implement the same function when we click on the YouTube ReVanced share button.

**Describe alternatives you've considered**
Clicking the YouTube ReVanced share button instead of the download button in the player.

**Additional context**
It's uncomfortable to click the download button on the player because when you return, you have to expand the app again.

**Comment by zaednasr** [comment]
Revanced minimises itself when a new app is launched. It's by design. So either pause or disable pip
