### ISSUE TITLE
[BUG] Incognito mode bugs when downloading two or more files

### ISSUE THREAD

**Issue by MrBKA95** [deniscerri/ytdlnis#424]
**Describe the bug**
Incognito mode bugs: When downloading multiple urls you are unable to change the title of each file & app does not save selection for all options in the additional menu such as Sponsorblock and Filename Template

**To Reproduce**
Switch incognito mode on in Downloads settings and then add two or more urls to the search bar

**Expected behavior**
File name changes & additional menu selections should be recognised in app before download when using incognito mode

**Screenshots / Video Recording**

https://github.com/deniscerri/ytdlnis/assets/105092892/3bf0b69b-4446-4fca-8e53-8f0c6a43e0e8

https://github.com/deniscerri/ytdlnis/assets/105092892/e50840dd-fc9c-44c4-8151-ad7661e20f05

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.3.1
 - Other Device Information: Samsung Galaxy S21

**Comment by zaednasr** [comment]
fixed it :)
wait for the next release

**Comment by MrBKA95** [comment]
> fixed it :) wait for the next release

Great thanks for the quick response 👍

**Comment by zaednasr** [comment]
check 1.7.4
