### ISSUE TITLE
[BUG] ERROR: [Instagram] C26OqYgonqm: Unable to extract video url; 

### ISSUE THREAD

**Issue by umang2931** [deniscerri/ytdlnis#428]
-N "3" --trim-filenames "203" --no-mtime --sponsorblock-remove "music_offtopic" --parse-metadata "uploader:(?P<uploader>.+)(?: - Topic)$" --parse-metadata "%(uploader,channel,creator,artist|null)s:%(uploader)s" --sponsorblock-mark "all" --embed-chapters -S "+hasaud,vcodec:h264,acodec:aac" -f "bv+ba/b" --embed-subs --sub-langs "en.*,.*-orig" -P "/data/user/0/com.deniscerri.ytdl/cache/downloads/15" -o "%(uploader)s - %(title)s.%(ext)s" "https://www.instagram.com/reel/C26OqYgonqm/?igsh=bW9jcHkwaHQxajM3"  WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U ERROR: [Instagram] C26OqYgonqm: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by tusharchopra07** [comment]
This app mainly uses ytdlp as the engine, or you can say it is based on yt-dlp. 
So, I guess the Instagram extractor is currently broken.

However, you can try using cookies to see if it works.

Also, please create a GitHub issue in a good manner and ensure that you correct things in the appropriate fields for next time.
