### ISSUE TITLE
[FEATURE REQUEST] Connect to PC via SSH

### ISSUE THREAD

**Issue by airisama019** [deniscerri/ytdlnis#429]
**Is your feature request available in yt-dlp? Please describe.**
Doesn't need to be

**Describe the solution you'd like**
Connect to PC via SSH and download there

**Describe alternatives you've considered**
Just login and run command from custom template
Also keep track of progress

**Comment by zaednasr** [comment]
How is that even supposed to work?
Also, its better to use an app like folder sync. Let this app download on a certain folder and folder sync sends it to your pc and deletes it on your phone afterwards. You can use ssh there or google drive whatever

**Comment by airisama019** [comment]
> How is that even supposed to work? Also, its better to use an app like folder sync. Let this app download on a certain folder and folder sync sends it to your pc and deletes it on your phone afterwards. You can use ssh there or google drive whatever

These apps only work if they allow access through default file manager
That uses android API which is slow and unusable on big files or folders.

MixPlorer is fast but there is no access from default file manager.

**Comment by zaednasr** [comment]
Well this app uses the the android api to transfer files around to the folder you have set. 
Also i use folder sync its pretty fast syncing my music to my pc.

**Comment by airisama019** [comment]
Besides
isn't it redundant to download to phone then sync
and you can use these apps to access your music directly 
there is no need to sync

**Comment by zaednasr** [comment]
The app uses yt-dlp to handle the download and it sets a certain download path where to put the file. So there needs to be a location somewhere where the app has to point to to store the file. 
If you have a rooted phone you could rclone mount your pc's shared folder to your droid and point the app to there.

**Comment by airisama019** [comment]
> The app uses yt-dlp to handle the download and it sets a certain download path where to put the file. So there needs to be a location somewhere where the app has to point to to store the file. If you have a rooted phone you could rclone mount your pc's shared folder to your droid and point the app to there.

there is no need to change the app
just ssh and "run something from the custom command template"

**Comment by zaednasr** [comment]
i dont follow.
Who is initiating the ssh the phone or the pc? Please describe step by step what is supposed to happen

**Comment by airisama019** [comment]
> i dont follow. Who is initiating the ssh the phone or the pc? Please describe step by step what is supposed to happen

![photo_2024-03-16_16-30-04](https://github.com/deniscerri/ytdlnis/assets/155326638/1fd2e018-9c39-4f66-9c71-ba2b87941c12)

Like this
this is all the app has to do.

**Comment by zaednasr** [comment]
uhhh, why dont u just use ytdlnis on your pc through windows subsystem for android? Why overcomplicate things

**Comment by airisama019** [comment]
> uhhh, why dont u just use ytdlnis on your pc through windows subsystem for android? Why overcomplicate things

yeah
I am using termux on phone with clipboard app
There is linux on my pc and all I have to do is copy and paste the commands on termux
But I thought this could improve this app and make it faster

**Comment by airisama019** [comment]
Seal's developer also didn't understand lol

**Comment by zaednasr** [comment]
The issue is not what you want. The issue is how to get the app to do that because its not that easy due to how android works.
For example, both this app and seal use a library that interfaces yt-dlp on android so its not really running raw commands somewhere, the yt-dlp has to be local on android.

**Comment by zaednasr** [comment]
ill keep a note of this in case i figure something out

**Comment by airisama019** [comment]
oh I know easy way to implement this
get shizuku working with this app 
then all you have to do is use ssh through adb since it's built-in on android
the only issue is that it won't save known_hosts file
but it doesn't need to save
just save password somewhere and repeat login every single time

**Comment by zaednasr** [comment]
Well storing the ip and the password can be done through the app's settings, it can be stored there so that is not an issue. Ill see what shizuku can do.
Problem is even if would do this under the hood, id lose progress and output since that is all parsed from the library.

**Comment by airisama019** [comment]
> Well storing the ip and the password can be done through the app's settings, it can be stored there so that is not an issue. Ill see what shizuku can do. Problem is even if would do this under the hood, id lose progress and output since that is all parsed from the library.

Output and progress is going to be wonky
Maybe we should give up on that

I can only think of = yt-dlp "your-link" > log.txt 2>&1 &
then assuming pc is already connected with wireless debugging
adb push log.txt ytdlnis-folder
parse it somehow
then repeat adb push because that's not going to be everything

maybe this is too much of a pain xd

**Comment by zaednasr** [comment]
and thats why its hard to do lol. I mean sure i might bundle up something like this but it will look like a bunch of messy code at the end lol.
Need to think of a structure and stuff, you know. So its better for me and others to know wtf i meant when i wrote that code on a tuesday
