### ISSUE TITLE
[BUG]Multiple downloads, when one of them is paused, the synchronization of other progress becomes invalid

### ISSUE THREAD

**Issue by leeblackc** [deniscerri/ytdlnis#434]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
Multiple downloads, when one of them is paused, the synchronization of other progress becomes invalid

**To Reproduce**
1.Set the number of downloads to be greater than 1
2.Open two download tasks
3.When the task starts downloading, pause one of them, logcat can see Ignoring setProgressAsync (...), the progress of the notification bar is updated normally, and the progress bar of ActiveDownloadsFragment stops updating

**Expected behavior**
When canceling one of the tasks, the progress of the other tasks is synchronized normally

**Screenshots / Video Recording**
https://github.com/deniscerri/ytdlnis/assets/21374847/4c6fb562-89bd-47b9-a387-c21df85decc9

**(please complete the following information):**
 - Android Version:  9
 - App Version:1.7.3.1 arm64
 - Other Device Information: yt-dlp[version]=2024.3.10

**Additional context**
I have tested on multiple devices and without any surprise, I have discovered this bug. ytdlnis is a great application, and I hope it will be even better

**Comment by zaednasr** [comment]
Might be a remnant of old code somewhere, because before every download had its own download worker, but now they are all in a single one. Will check. Thanks for this

**Comment by zaednasr** [comment]
pull the latest commit and test please

**Comment by leeblackc** [comment]
Thank you for your reply. It is now working normally
