### ISSUE TITLE
Tapping errored download notification leads to Running queue tab instead of Errored

### ISSUE THREAD

**Issue by matt873** [deniscerri/ytdlnis#437]
Also, tapping on logs in notification leads to Running downloads queue instead of Logs.

**Comment by tusharchopra07** [comment]
> Also, tapping on logs in notification leads to Running downloads queue instead of Logs.

 

https://github.com/deniscerri/ytdlnis/assets/128215171/6e76e77d-a64c-4673-b157-5b738fdd0dca

Can't reproduce, can you share an screenrecord

**Comment by zaednasr** [comment]
can you show us a video?

**Comment by matt873** [comment]
Can be reproduced for any video.

**Comment by zaednasr** [comment]
I dont want to know how to reproduce an errored download cuz i can just write gibberish in command mode and it will fail, but when i tap the notification im sent to logs so not sure whats the issue here

**Comment by zaednasr** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/69ac9f87-6099-4a08-b656-fb968125803b)
The app has two intents, the download queue and the log

you might have tapped the body of the notification and not the action below it

**Comment by matt873** [comment]
https://github.com/deniscerri/ytdlnis/assets/108935493/d43ca03b-64d3-4486-8061-e5b75eff08f0

**Comment by zaednasr** [comment]
dm on telegram, ill give you a test apk

**Comment by matt873** [comment]
Or
