### ISSUE TITLE
[BUG] Facebook Stories Download

### ISSUE THREAD

**Issue by bremaya** [deniscerri/ytdlnis#440]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
A clear and concise description of what the bug
Is not possible to download Facebook Stories

**To Reproduce**
Share Story link

**Expected behavior**
Download the Story video

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 
 - App Version:
 - Other Device Information:

**Additional context**

**Comment by zaednasr** [comment]
send the crash log

**Comment by bremaya** [comment]
Log:

WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F105750625932809%2FUzpfSVNDOjQ1NTQ4NTUyNjkxMzAwNA%3D%3D%2F%3Fview_single%3D1%26source%3Dshared_permalink%26mibextid%3DoFDknk%26rdid%3DgkxyHQpgmodGud6O
