### ISSUE TITLE
[BUG] downloading from YouTube video player forces PiP mode

### ISSUE THREAD

**Issue by Dima793** [deniscerri/ytdlnis#442]
**Description**
Tried to use YTDLnis as an external downloader for YouTube ReVanced. When pressing download button in video player screen YTDLnis pops up normally, but also forces the video into Picture-in-Picture mode. Did not happen with PowerTube that I've been using earlier.

**Reproduction steps**
1. Set up and open YouTube ReVanced app
2. Set YTDLnis as external downloader
3. Play any video in YouTube ReVanced
4. Press "download" button

**Expected behavior**
YTDLnis should open "on top of" YouTube app that should continue to play the video in the same mode, see PowerTube examplary screenshot.

**Screenshots / Video Recording**
Screen recording of YTDLnis forcing video player into PiP mode: https://github.com/deniscerri/ytdlnis/assets/17815003/7689ba84-8bcb-40a2-8955-c26027146cf3
Examplary screenshot with PowerTube of how it should work (PowerTube screen "on top of" YouTube ReVanced app that plays the video): ![Screenshot_20240329-042057_PowerTube](https://github.com/deniscerri/ytdlnis/assets/17815003/f59d7422-c85c-4edf-9773-1891eb85b2ad)

**Software and hardware information:**
 - Android Version: 14
 - YTDLnis App Version: 1.7.3.1
 - YouTube ReVanced App Version: 19.11.43
 - PowerTube App Version: 5.0.3
 - Device model: Asus Zenfone 10
 - Root status: device was never rooted

**Comment by zaednasr** [comment]
I believe i have a solution ready. Revanced root works ok and the default share menu works ok. normal revanced with hook btn pulls pip but i believe its an issue with the download hook button.

**Comment by zaednasr** [comment]
check 1.7.4
