### ISSUE TITLE
[BUG]  Error since new update

### ISSUE THREAD

**Issue by CrescatScientia** [deniscerri/ytdlnis#445]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
error message appear when i press download in revanced, and when i update quality also

**To Reproduce**
open revanced and download a video using yt-dlp

**Expected behavior**
there is no error message before update

**Screenshots / Video Recording**
![Screenshot_2024-04-01-16-10-00-46](https://github.com/deniscerri/ytdlnis/assets/78627411/66e8757c-e2c9-43d4-aa42-b88ea11b4c7c)
![Screenshot_2024-04-01-16-10-11-49](https://github.com/deniscerri/ytdlnis/assets/78627411/5847e401-a8dd-47aa-8682-629fd2b5ee09)

**(please complete the following information):**
 - Android Version: 10
 - App Version:2024.03.31.232706
 - Other Device Information: non-root

**Additional context**

**Comment by CrescatScientia** [comment]
> Well, it's a known issue not from ytdlnis but from ytdl-android. Ytdlnis uses ytdl-android to run yt-dlp on the Android system with ease. Anyway, you can try these fixes: Things you can try:
> 
> 1. Try restarting your device.
> 2. Check your device architecture and install the correct version.
> 3. Completely uninstall it, then reinstall it again.

![Screenshot_2024-04-01-17-20-20-47](https://github.com/deniscerri/ytdlnis/assets/78627411/91cc9308-7fb6-48c7-ba55-abcea1fc1447)
how about this one? can't update format anymore.

**Comment by teddysulaimanGL** [comment]
That one is already reported. It'll be fixed for the next release
