### ISSUE TITLE
[FEATURE REQUEST] Visual changes in download card

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#446]
Since this app already take inspiration from Seal, i want to suggest some visual changes in download card if possible.

1. Moving Schedule and Download Button after command and Decreasing empty space around link. This will make card a bit shorter.
2. Making Navigation Bar follow App colors.
3. Moving "Free Space" text in middle to make it look less cluttered.
4. Using outlines button like Seal. They'll be highlighted only if selected instead of always being highlighted & having checkmarks to indicate selected. This'll differentiate them a bit better.

Here's a very rough mockup i made for reference:
![Picsart_24-04-01_20-50-15-483](https://github.com/deniscerri/ytdlnis/assets/99175083/febebbdd-27ad-4363-8582-fb62d02938ce)

This pull down indicator pill isn't really needed

**Comment by NikunjKhangwal** [comment]
That's a totally fair point

**Comment by NikunjKhangwal** [comment]
Btw aside from 4th suggestion, these aren't native to Seal. (I should've phrased it better).
1st and 3rd are my ideas. Navigation Bar coloring is something a lot of apps do. What do you think about them?

**Comment by zaednasr** [comment]
about the navigation bar color, i have noted it down
