### ISSUE TITLE
[FEATURE REQUEST] Option to register YTDLnis as a browser

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#447]
I have a lot of apps in my phone and currently to share links i have to swipe a lot to find the right app. If the app can act like a browser then i can just click on a link and choose ytdlnis from there. The process will be much easier and faster. There's this app called [Leon](https://github.com/svenjacobs/leon) which has this feature (also written in Kotlin) if you can use it as a reference.

**Comment by NikunjKhangwal** [comment]
Yes the web address support get added in new update but this request is a bit different. The app supports only a handful of sites to open links from. As browser it can open any link. Put the link through share activity and open pop-up download card just like normal sharing.

**Comment by zaednasr** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/bfed5ccb-cf81-4ef6-8f0b-72ba03ea9628)
The app already has the browsable intents. So idk how leon handles this

**Comment by NikunjKhangwal** [comment]
Well I'm not a developer so i don't know how everything works. I just suggested it because i like the behavior

**Comment by NikunjKhangwal** [comment]
I'm actually already using LinkSheet. The issue was created before i discovered it. Yes, it does solve half the problem but for supported links only. Yt-dlp supports hundreds of websites.

Either way now with linksheet, it's usable and the issue is probably too much of a headache for dev too so I'm closing it.

**Comment by zaednasr** [comment]
I'll have another crack at it

**Comment by NikunjKhangwal** [comment]
Yeah I'm aware of verified links too. I does have SUI installed but Linksheet didn't needed it so far. Thanks

**Comment by zaednasr** [comment]
Ok so i found the way to make the app show up as an option for the default browser list. I guess in the next release it will be good to go. 
Although kinda strange to ask for this app to be a browser lol. 
U will have to select it in android's settings

**Comment by zaednasr** [comment]
I found the way how leon can appear as a browser and i could make ytdlnis do the same, but then the app loses the ability to select default urls because it would allow any url to redirect to the app which is pointless as it wont support them all.

So the best course of action was to just add more alternate domains for sites so that the urls can be recognised by android to redirect to the app

**Comment by NikunjKhangwal** [comment]
Yeah, fair. But is it possible to support all websites supported by yt-dlp? It supports thousands of them

**Comment by zaednasr** [comment]
Each intent has to be written manually...

**Comment by NikunjKhangwal** [comment]
That sounds like a drag. Anyway it's your choice. Do whatever feels right.

**Comment by zaednasr** [comment]
That's why i just added the top websites

**Comment by NikunjKhangwal** [comment]
So we can close this issue?

**Comment by zaednasr** [comment]
I'll close it on the next release
