### ISSUE TITLE
[FEATURE REQUEST] Set download archive path

### ISSUE THREAD

**Issue by ZobaJakColbert** [deniscerri/ytdlnis#449]
When in **Settings->Downloads->Downloading section->Download Archive** option is turned on **where archive.txt is stored?**

I would like to set custom path for archive.txt or whatever it called. And set name for custom archive.txt so it could be downloaded.txt or something else.txt.

Or I would like option to open this archive.txt file in edit mode. So I can remove lines or copy whole content to clipboard.

**Comment by zaednasr** [comment]
Added ability to set the folder location of the download archive. The app will autocreate the archive file itself or use one named as download_archive.txt in the folder. Wait for the release

**Comment by zaednasr** [comment]
Check the latest beta:
https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.6.1-beta
