### ISSUE TITLE
[BUG] Video downloads music file instead when using M4A music format

### ISSUE THREAD

**Issue by fg817sw751478** [deniscerri/ytdlnis#453]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
When using M4A as a music format in videos, for some reason, the downloader only downloads a music file.

**To Reproduce**
1. Download a video with M4A music format
2. The music file gets downloaded instead (and is in the videos folder too)

**Expected behavior**
My video would download normally.

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.
None

**(please complete the following information):**
 - Android Version: 14
 - App Version: Latest as of now
 - Other Device Information: Xiaomi Redmi Note 12 4G NFC EEA, HyperOS 1.0.5.0

**Additional context**
When downloading with Opus, issue is fixed.

**Comment by tusharchopra07** [comment]
Show your extra commands screenshot or just paste it , or if you can provide log of the download

**Comment by tusharchopra07** [comment]
Hmm can you share a ss too (with configurations )

**Comment by zaednasr** [comment]
Yes this appears to be a bug. Will fix

**Comment by zaednasr** [comment]
check [1.7.5](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.5)
