### ISSUE TITLE
[BUG] Doesn't load formats.

### ISSUE THREAD

**Issue by HideSpy** [deniscerri/ytdlnis#456]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
When i click to load formats this appears : java.lang.NumberFormatException: For input string: "None" .And unfortunately doesn't load any formats therefore i can't download a song.

**To Reproduce**
Steps to reproduce the behavior: Don't know.

**Expected behavior**
I thought it would work fine like my other device.

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.
![Screenshot_20240411-113513](https://github.com/deniscerri/ytdlnis/assets/163342046/0f868009-f0dd-4ebe-848c-dc3404dcb339)

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.4
 - Other Device Information:

**Additional context**

**Comment by Derkades** [comment]
Very quickly clicking the download button before this message appears still works

**Comment by Inrixia** [comment]
+1 happening for me too

**Comment by zaednasr** [comment]
Yes it's a known bug. I have fixed it in my local machine. For now use piped format source

**Comment by Inrixia** [comment]
Awesome thanks! Can confirm using `PIPED [Youtube]` for Settings>Updating>Formats Source fixes it!

**Comment by zaednasr** [comment]
@Bub0 you could set the premium format id as preferred format id
And in format list tap filtrr button and then generics
Select the format.

Sorry for inconvenience. The fix will come soon

**Comment by Bub0** [comment]
Alright I'll check it out later, TY 🙂

Den fre 12 apr. 2024 18:13zaednasr ***@***.***> skrev:

**Comment by zaednasr** [comment]
check [1.7.5](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.5)
