### ISSUE TITLE
Cutting specific part with miliseconds

### ISSUE THREAD

**Issue by linuxtopia** [deniscerri/ytdlnis#457]
Hi,

Thanks for this awesome useful tool that I use to cut for specific parts of YouTube videos especially for into sound converting. But for better cutting we need milliseconds input. Can you enhance that timing.

thanks.

**Comment by zaednasr** [comment]
Will see what i can do

**Comment by zaednasr** [comment]
its implemented. Please wait for the next release

**Comment by linuxtopia** [comment]
hopefully will work flawlessly. 
thanks man,

**Comment by zaednasr** [comment]
Check the latest beta:
https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.6.1-beta
