### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Don1250** [deniscerri/ytdlnis#459]
**Describe the bug**
java.lang.NumberFormatException: For input string: "None"

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.7.4
 - Other Device Information: None

**Comment by tusharchopra07** [comment]
Known issue 
Switch to Piped formats source (only for YouTube downloads). No workaround for other sites, babes. Wait for the next release

**Comment by zaednasr** [comment]
check [1.7.5](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.5)

**Comment by Don1250** [comment]
it fix thanks
