### ISSUE TITLE
[BUG] Cannot Download Tiktok Videos

### ISSUE THREAD

**Issue by Stale-1** [deniscerri/ytdlnis#464]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
I cannot download Tiktok Videos, it used to work before though. 

**To Reproduce**
Copy a link from tiktok then download
**Expected behavior**
It used to work before without any problem

**(please complete the following information):**
 - Android Version: 10
 - App Version: 1.7.5
 - Other Device Information: Huawei Matepad T8 (KOB2-L09) 

Here is the log from the app:

WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
WARNING: [TikTok] 7357370391548955909: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
ERROR: [TikTok] 7357370391548955909: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by teddysulaimanGL** [comment]
> Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 
Follow what it says. YTDLnis is a GUI, it depends on another library, so every error is up to [yt-dlp](https://github.com/yt-dlp/yt-dlp/). So tell them.

And before everyone mentioned that it has less formats now, [read this](https://github.com/yt-dlp/yt-dlp/issues/9567)
