### ISSUE TITLE
[BUG] ERROR: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

### ISSUE THREAD

**Issue by SpeeterYT** [deniscerri/ytdlnis#465]
**Describe the bug**
This message appears when loading video info

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.7.5
 - Other Device Information: pixel 3a

**Additional context**
Termux is installed on device

**Comment by SpeeterYT** [comment]
3. Worked for me

**Comment by tusharchopra07** [comment]
Great 👍🏼
