### ISSUE TITLE
[FEATURE REQUEST] Ability to Download video from Desi Cinemas

### ISSUE THREAD

**Issue by Don1250** [deniscerri/ytdlnis#467]
**Is your feature request available in yt-dlp? Please describe.**
it does download from other website can you add Desi Cinemas and give ability to Download Video from Desi Cinemas???

**Additional context**
can it download video from desicinemas because it does it will be awesome...

**Comment by tusharchopra07** [comment]
ytdlnis uses yt-dlp as backend so you should create the issue in yt-dlp repo 
Basically yt-dlp is a cli tool and ytdlnis is gui version of yt-dlp, For more you can read on [their page](https://github.com/yt-dlp/yt-dlp) Site Request: [Here](https://github.com/yt-dlp/yt-dlp/issues/new?assignees=&labels=triage%2Csite-request&projects=&template=2_site_support_request.yml)
