### ISSUE TITLE
Translation bug, I think [BUG]

### ISSUE THREAD

**Issue by NicoaraAlex** [deniscerri/ytdlnis#468]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
It's a bug in custom quality and audio quality. I think the translation is incorrect? I also checked the translations and left a comment.

**To Reproduce**
1. Start app
2. Go to "More"
3. Go to "Settings"
4. Go to "Processing"
5. Scroll down, and see "Use Custom Audio Quality"
6. Turn on, and see "Audio Quality 0 (best) 10 (worst)"

**Expected behavior**
I knew that 0 is worse and 10 is better.

**Screenshots / Video Recording**
![image](https://github.com/deniscerri/ytdlnis/assets/82382328/6731950c-97ff-4a74-8db3-528689a86669)
![image](https://github.com/deniscerri/ytdlnis/assets/82382328/9b0fe448-5bb3-4fad-a705-aafd5316ab5b)
(on Weblate - https://hosted.weblate.org/translate/ytdlnis/-/en/?q=state:%3Ctranslated )
![bug](https://github.com/deniscerri/ytdlnis/assets/82382328/fe2610ea-7718-4033-be18-53e274438197)
(ss on bug in app)

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.5
 - Other Device Information: Samsung SM-G998B [arm64-v8a]

**Additional context**
I don't think that the error (if it is an error) is due to the version of the application or android

**Comment by tusharchopra07** [comment]
No, YTDLnis uses yt-dlp, and for yt-dlp 0 = best 10 = worst, the quality decreases in increasing order of numbers, also for more information you can checkout in yt-dlp page, the command is --audio-quality 
![Screenshot_2024-04-23-09-50-55-763_com android chrome](https://github.com/deniscerri/ytdlnis/assets/128215171/703ccaa4-ad44-4879-aa07-6663c58a2337)
