### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [deniscerri/ytdlnis#47]
Please support the "Android 13"Themed App Icons" feature.

![Screenshot_2023-03-13-21-42-24-325_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/224791613-7e475129-cc3d-472f-a1e5-8d18465a63fa.jpg)

**Comment by deniscerri** [comment]
![image](https://user-images.githubusercontent.com/64997243/224814826-a4a425d2-86d1-4b2a-96ea-30ae484d8635.png)
![image](https://user-images.githubusercontent.com/64997243/224814841-c2d85aee-22fc-42da-a701-2d8cf908d3e5.png)

Implemented
Dark and Light Mode

Please wait for the future release :)

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by xmha97** [comment]
Hi @deniscerri 
The least version don't have monochrome icon. Please check.

![Screenshot_2023-04-25-05-02-48-745_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/234152880-f76e08f7-50fc-43c5-9d6b-c79817d3f341.jpg)
