### ISSUE TITLE
[FEATURE REQUEST] Option to automatically number each chapter when using "split by chapter"

### ISSUE THREAD

**Issue by MrBKA95** [deniscerri/ytdlnis#473]
I was wondering if you could add an option to automatically number each chapter in the video titles in numerical order when using the "split by chapters" feature. I've tried multiple times using different options in the filename template and have tried finding command lines on websites, all to no avail.

Alternatively, if there is something that I need to do in the filename template, or if you or someone else can give me a command line that I can add to the extra commands for this to happen, that would be massively appreciated. 🙏

**Comment by teddysulaimanGL** [comment]
Okay, can you tell what filename template did you try it with?

**Comment by MrBKA95** [comment]
I've tried various to be honest:
%(autonumber)s
%(video_autonumber)s
%(chapter)s
%(chapternumber)s
%(chapter_id)s

**Comment by teddysulaimanGL** [comment]
Now try with %(section_title)s and/or %(section_number)s

**Comment by MrBKA95** [comment]
Tried each separately and together and still only the chapter titles

**Comment by teddysulaimanGL** [comment]
Oh, okay. I see what's going on. Noted

**Comment by MrBKA95** [comment]
Ok thank you

**Comment by zaednasr** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/83405604-8db8-4d35-a140-4ae05135af46)

Split by chapters is hardcoded in the app. So i added the section number in it. It should do the job

**Comment by MrBKA95** [comment]
Brilliant. Thank you

**Comment by zaednasr** [comment]
Check the latest beta:
https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.6.1-beta
