### ISSUE TITLE
[BUG] [ksp] C:/Users/*/AndroidStudioProjects/ytdlnis/app/src/main/java/com/ytdl/videodownloader/database/DBManager.kt:62: Schema '1.json' required for migration was not found at the schema out folder: C:\Users\*\AndroidStudioProjects\ytdlnis\app\schemas\com.ytdl.videodownloader.database.DBManager. Cannot generate auto migrations.

### ISSUE THREAD

**Issue by hamza0786** [deniscerri/ytdlnis#474]
Hi!
after replacing the package name getting this error:

[ksp] C:/Users/*/AndroidStudioProjects/ytdlnis/app/src/main/java/com/ytdl/videodownloader/database/DBManager.kt:62: Schema '1.json' required for migration was not found at the schema out folder: C:\Users\*\AndroidStudioProjects\ytdlnis\app\schemas\com.ytdl.videodownloader.database.DBManager. Cannot generate auto migrations.

**Comment by zaednasr** [comment]
Go to build gradle and see the reference of room database

**Comment by hamza0786** [comment]
> Go to build gradle and see the reference of room database

this is in build.gradle file:
ksp {
            arg("room.schemaLocation", "$projectDir/schemas")
        }

**Comment by zaednasr** [comment]
What about the file structure 
It might still have the old package name

**Comment by hamza0786** [comment]
> What about the file structure It might still have the old package name

where to find it?

**Comment by hamza0786** [comment]
i have already change the package name in file directory by compact middle package

**Comment by zaednasr** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/95a12f5d-b49b-4144-b2b5-d8e19b245979)
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/a5919076-594a-4c4e-8fd6-fa63f63065d1)

**Comment by hamza0786** [comment]
yes i have changed these also.

**Comment by hamza0786** [comment]
so, no solution for this?

**Comment by zaednasr** [comment]
https://github.com/deniscerri/ytdlnis/commit/d7819aca98f847ea2201791bcae80370c059c959

Look at this commit. I had changed the package from ytdlnis to ytdl

**Comment by hamza0786** [comment]
> [d7819ac](https://github.com/deniscerri/ytdlnis/commit/d7819aca98f847ea2201791bcae80370c059c959)
> 
> Look at this commit. I had changed the package from ytdlnis to ytdl

after i changed it to this:
com.techinfo.ytdl

again same error

**Comment by hamza0786** [comment]
can you plz change it in android studio to see if you face the same issue or not.

**Comment by zaednasr** [comment]
it all has to do with namespaces and file structure. There might be something you missed. Or maybe clear android studio caches.

![image](https://github.com/deniscerri/ytdlnis/assets/75589932/db666374-800d-49eb-bc59-cb488acf3d1b)
look at this for example.

**Comment by hamza0786** [comment]
ok.thats the issue i did not change the package name in schemas folder.now its working perfectly.thanks for helping out...
