### ISSUE TITLE
Facebook Cookies

### ISSUE THREAD

**Issue by msalah-kw** [deniscerri/ytdlnis#476]
Can't get Facebook cookies![Screenshot_20240507_091731.jpg](https://github.com/deniscerri/ytdlnis/assets/132661669/31d730ad-05d3-4b85-bf32-51f481534667)

**Comment by teddysulaimanGL** [comment]
Can't reproduce. Next time, don't ignore the issue template and give as much details as possible. And for now, tell me the app version you're in and tell me what URL did you type

**Comment by msalah-kw** [comment]
https://www.facebook.com/share/p/yEwo3nxVmh7gTuiR/?mibextid=qi2Omg



Version: 1.7.5 (arm64)

**Comment by msalah-kw** [comment]
WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://m.facebook.com/login/?next=https%3A%2F%2Fm.facebook.com%2Fstory.php%3Fstory_fbid%3D391225167223711%26id%3D100090086921556%26mibextid%3Dqi2Omg%26rdid%3DonEYF9e1bwQf5cqg%26share_url%3Dhttps%253A%252F%252Fm.facebook.com%252Fshare%252Fp%252FyEwo3nxVmh7gTuiR%252F%253Fmibextid%253Dqi2Omg%2526wtsid%253Drdr_0fd1WpMagt8LSlcCQ%26wtsid%3Drdr_0fd1WpMagt8LSlcCQ%26refsrc%3Ddeprecated&wtsid=rdr_0fd1WpMagt8LSlcCQ&rdid=onEYF9e1bwQf5cqg

**Comment by teddysulaimanGL** [comment]
It's so unnecessary to type the whole story URL. Just type it like this. And just run the download as usual after
![Screenshot_20240507_134122.png](https://github.com/deniscerri/ytdlnis/assets/134608531/7a63a464-2456-49bb-a050-b6d6ec8c5741)

**Comment by msalah-kw** [comment]
![Screenshot_20240507_094922.jpg](https://github.com/deniscerri/ytdlnis/assets/132661669/9974fbc2-2eda-4546-b71a-aed539b78bfc)

After writing my login credentials, I get this error 
![Screenshot_20240507_091731.jpg](https://github.com/deniscerri/ytdlnis/assets/132661669/381490a6-1406-47aa-8b60-d28c63520c94)

**Comment by teddysulaimanGL** [comment]
*Shrugs* then pass your credential using `--username` and `--password` as Extra Commands

**Comment by zaednasr** [comment]
This is more of a Facebook issue. You need to find how to enable embedded browsers. 

Or if u have a pc. Use a cookie extractor extension and copy the cookies.
Then import them to the app
