### ISSUE TITLE
[BUG] downloads the wrong videos when given a channel

### ISSUE THREAD

**Issue by Gooberpatrol66** [deniscerri/ytdlnis#477]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
Downloads this video https://www.youtube.com/live/RLRMwXpzNzw?si=S4H2QDlJHKQGutgR

**To Reproduce**
paste this channel https://www.youtube.com/@Anark/featured
download this video in the list https://youtu.be/AYp_0ytt1xE?si=uqFC9yQMfnJNAXvw

**Expected behavior**
the correct video downloads

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 12
 - App Version: 2024.05.05.232701
 - Other Device Information: nord n200, lineageos

**Additional context**

**Comment by zaednasr** [comment]
can't reproduce this. It downloads the 30 minute video as expected. Can you show me?

**Comment by Gooberpatrol66** [comment]
![Screenshot_20240511-232339_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/5498361/a5a6f952-1b22-417f-b18c-6912f36a5821)
![Screenshot_20240511-232348_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/5498361/3eb68c99-041a-4dd5-82fd-d232e3669bf5)
![Screenshot_20240511-232352_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/5498361/bc06e223-ffbd-4b23-8751-1d7814816d8b)

**Comment by zaednasr** [comment]
i have tried this multiple times but it downloads the normal video
