### ISSUE TITLE
[BUG] Multiple errors when downloading more than one url in latest beta release

### ISSUE THREAD

**Issue by MrBKA95** [deniscerri/ytdlnis#479]
I've encountered multiple issues when downloading multiple urls in 1.7.6.0-beta. When you add the urls to the search bar initially they do not list in order of url added.

Then in my case when I selected audio for each file and then renamed each file the app did not recognise this and downloaded the files as a mp4 video file and the title unchanged. I've tried this with incognito mode switched on and off and both times it does the same.

I've attached a video showing this process and a screenshot showing the .mp4 ouput.![Screenshot_20240514_101821_MX Player Pro.jpg](https://github.com/deniscerri/ytdlnis/assets/105092892/718cc702-7b0b-4294-b0b3-f194d89a2de6)

https://github.com/deniscerri/ytdlnis/assets/105092892/3bb074f4-c5b2-41de-8278-0d64035ba0af

**Comment by zaednasr** [comment]
Noted. Thanks for pointing this out

**Comment by zaednasr** [comment]
Check the latest beta:
https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.6.1-beta
