### ISSUE TITLE
[BUG] An error showing up prior to downloading any video through Revanced

### ISSUE THREAD

**Issue by COOLak** [deniscerri/ytdlnis#480]
I'm using YTDLnis in conjuction with YouTube Revanced instead of its integrated newpipe, because this one is so much better in my opinion. There's just a little annoying thing. Every time when I click the download button in Revanced and there's YTDLnis screen coming up with download preferences, immediately an error pops up on top of all that. The error says:

```
NO RESULTS

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: wrong OPTS for —compat-options: manifest-filesize-approx
```

And there's a little link "copy log" at the bottom right corner of this popup that I can click, and after that I can proceed with the download without any issues. However, the download screen will just close if I don't click this "Copy Log" link.

It's not like it's a serious issue, but it's a bit annoying. What can I do in order for this error not to pop up every time? Or should I report this bug to the Revanced team instead?

The screenshot of the error (sorry, in Russian):

<img src="https://github.com/deniscerri/ytdlnis/assets/8677627/ed261d8b-e480-4647-b616-d70defcd5d55)" width=25% height=25%>

**Comment by teddysulaimanGL** [comment]
In case you haven't realized, the latest (stable) app version is 1.7.5.

Also, it's already a part of known issues and is already mentioned in the Telegram group chat.

[More ➔ Settings ➔ Updating ➔ Install new version of yt-dlp
Q: It's not updated successfully. Why can't I update yt-dlp?
 A: The most common reason is either because your ISP or you're using an AdBlocker like Adguard and certain filter lists are blocking the request. The solution is to use VPN or DNS so your ISP can no longer blocking it and temporarily disable your AdBlocker while trying to update it](https://t.me/ytdlnis/36055/70297)

**Comment by COOLak** [comment]
@teddysulaimanGL In case you haven't bother to ask, I already have the latest version of the app, smartass:

<img src="https://github.com/deniscerri/ytdlnis/assets/8677627/1d1c3dff-3606-44a6-8997-9231e3b388c2)" width=25% height=25%>

**Comment by teddysulaimanGL** [comment]
Got it. That's not my whole point. Read my later statement

**Comment by teddysulaimanGL** [comment]
I'm trying to help here. Don't be a jerk

**Comment by COOLak** [comment]
> Got it. That's not my whole point. Read my later statement

I've read your later statement. It's just a link to a Telegram topic that answers the quesion "Why can't I update yt-dlp."
And that isn't my question/issue.

**Comment by teddysulaimanGL** [comment]
I already mentioned in that topic as well that yt-dlp isn't equal to the app

**Comment by teddysulaimanGL** [comment]
[yt-dlp ≠ the app
 When I'm talking about something like, "Update your yt-dlp version", I'm not talking about the app's version. yt-dlp is a dependency that the app uses for most app functionalities and features. Refer to above message to see the steps of updating this thing to fix problem(s) you're having](https://t.me/ytdlnis/36055/67420)

**Comment by COOLak** [comment]
> [yt-dlp ≠ the app  When I'm talking about something like, "Update your yt-dlp version", I'm not talking about the app's version. yt-dlp is a dependency that the app uses for most app functionalities and features. Refer to above message to see the steps of updating this thing to fix problem(s) you're having](https://t.me/ytdlnis/36055/67420)

I had to switch it to nightly, now the problem is gone. Thank you and sorry for misunderstadning and being a jerk. Otherwise, I already had it updated (figured it out myself prior to creating this topic), I just didn't try Nightly. Now I tried Nightly and it helped. Thanks again.

**Comment by zaednasr** [comment]
Lol wth 🤣
