### ISSUE TITLE
[FEATURE REQUEST] Display download speed in Mib/s

### ISSUE THREAD

**Issue by Inrixia** [deniscerri/ytdlnis#481]
**Is your feature request available in yt-dlp? Please describe.**
I cannot find a setting to display download rate in bits per second instead of bytes. 

**Describe the solution you'd like**
The option to display download speed in Mib/s instead of MiB/s

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zaednasr** [comment]
This is more of an yt-dlp feature request. So please ask them if this is possible. If it is, please get back at me with the command needed and it can be done

**Comment by Inrixia** [comment]
Excellent point. Searching through looks like you can use specific progress formatting to achieve it.

https://github.com/yt-dlp/yt-dlp/issues/8683

**Comment by zaednasr** [comment]
> Excellent point. Searching through looks like you can use specific progress formatting to achieve it.
> 
> [yt-dlp/yt-dlp#8683](https://github.com/yt-dlp/yt-dlp/issues/8683)

For the time being you can create a custom command with that and use it by default for your downloads. Let me know how it works and send me the command you used so i could add it in the next release as a setting

**Comment by Inrixia** [comment]
Thx, I'll take a look when I get time.

**Comment by zaednasr** [comment]
Also i believe this should just be an extra command you can set up to always apply on your downloads. Dont want to add excessive commands as its overfilled already
