### ISSUE TITLE
[BUG] Album/playlist track number not being saved

### ISSUE THREAD

**Issue by TuTiuTe** [deniscerri/ytdlnis#482]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue
I am using the latest version, even switched to the beta version to make sure

**Describe the bug**
A few months ago, whenever I downloaded a playlist, its songs were numbered in the metadata in the same order as they are in the playlist
Right now, it just doesn't work despite there clearly being the intent to do the same thing as before when checking the logs

**To Reproduce**
Just try to download any playlist, look at their metadata, and they won't be numbered

**Expected behavior**
The tracks should have been properly numbered in the metadata

**Screenshots / Video Recording**
The playlist I want to download
![Screenshot_20240524-161506_Fennec](https://github.com/deniscerri/ytdlnis/assets/143942440/c8e0657d-3d19-4e08-9dee-3194a87b9f8b)

![Screenshot_20240524-161614_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/143942440/b2d81397-2696-4268-88d3-0cfa2dc69846)

Here is the log, showing it has set the track number to index 11
![image23](https://github.com/deniscerri/ytdlnis/assets/143942440/d044957b-785c-4fcd-810d-27c0ab7f7652)

Here is a screenshot of the change not actually happening (it's not the same track, but every track doesn't have their track number)
![Screenshot_20240524_170943](https://github.com/deniscerri/ytdlnis/assets/143942440/15c20eae-8dcf-4247-be22-8e837514a4f3)

**(please complete the following information):**
 - Android Version: 14
 - App Version: tested on 1.7.5 and 1.7.6 beta

**Comment by zaednasr** [comment]
Did ytdlp change a command? What is supposed to be the correct one? Because the app knows the playlist index at least

**Comment by TuTiuTe** [comment]
I looked around a bit in yt-dl's documentation. I managed to embed the right metadata by doing  --parse-metadata "playlist_index:%(track_number)s". The log in ytdlnis indicates it does --parse-metadata "%(track_number,playlist_index)d:%(meta_track_number)s"
Since I tried yt-dl on my pc, it might be a different version in ytdlnis and the fix is maybe not as easy as modifying that one line of code

**Comment by zaednasr** [comment]
Try copying the apps log and test in terminal mode. Because ytdlp is the same

**Comment by TuTiuTe** [comment]
it solved the issue in the mobile app when using "track_numbers" instead of "meta_track_numbers"

**Comment by zaednasr** [comment]
Check the latest beta:
https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.6.1-beta

**Comment by TuTiuTe** [comment]
Works perfectly thx <3
