### ISSUE TITLE
[BUG] Display over apps is Conflicted with other apps's PIP

### ISSUE THREAD

**Issue by Kimphunh** [deniscerri/ytdlnis#486]
**Describe the bug**
 YTDLnis display over apps is Conflicted with PIP build in android feature, It make the YTDLnis Display all screen just a blackscreen
**To Reproduce**
1) Download video on Youtube by share it to YTDLnis
2) When the download finish, at the Notification, click on "Open File"
3)Choose any video player that supports PIP
4)When the Video is playing, immediately get back the home screen and make sure the video is playing in PIP mode

**Screenshots / Video Recording**
https://drive.google.com/file/d/1az8ejLAxAtiMzu8tule64d8rbQYNrq2Y/view?usp=drivesdk
**Information**
 - Android Version: 12
 - App Version: 1.7.6.1-beta [arm64]
 - Other Device Information: One UI Core 4.1

**Comment by zaednasr** [comment]
Is the black screen the app? Or a random black screen

**Comment by Kimphunh** [comment]
> Is the black screen the app? Or a random black screen

To answer it Clear, it just displays over everything with a blackscreen

**Comment by zaednasr** [comment]
yeah but can you open the recents menu. Can you figure out what is the black screen coming from? The player or the app.

**Comment by Kimphunh** [comment]
> yeah but can you open the recents menu. Can you figure out what is the black screen coming from? The player or the app.

I know this because at the end of the video you will see the message "ytdlnis is displaying over another apps" ,Can you reproduce that or does it still work no problem with your phone and I'm the only one having this problem?

**Comment by Kimphunh** [comment]
It from the app, YTDLnis

**Comment by zaednasr** [comment]
i removed display over apps permission in the newer releases
