### ISSUE TITLE
[BUG] YTDLNIS downloads wrong thumbnails from a playlist

### ISSUE THREAD

**Issue by GoldDa** [deniscerri/ytdlnis#488]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
When trying to download audio files (.opus) from a playlist, for some reason it doesn't download its respective thumbnail from the audio files. It would download a thumbnail from one song and use that for a few files. 

Then for some reason, one of the songs in the photo is exempt from this and the others continue to use the same thumbnail.  My music player I'm using to view this is Samsung Music. 

**To Reproduce**

Download the playlist, by going into YTDLNIS app, copy and paste the link of the playlist, select all audio, move the downloaded content to a folder, pressed download 
**Expected behavior**

I expect to the files to have different thumbnails like how it's being downloaded. 

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

![Screenshot_20240603_105542](https://github.com/deniscerri/ytdlnis/assets/70769154/2a9388e8-76c1-4698-bcfb-1841521b1b9c)
![Screenshot_20240603_105800_Samsung Music](https://github.com/deniscerri/ytdlnis/assets/70769154/34a49091-0e43-4e63-ba1c-f0ec50a09155)
![Screenshot_20240603_105854](https://github.com/deniscerri/ytdlnis/assets/70769154/ff495b07-99e8-4a59-939b-b7fc6bf3189e)

**(please complete the following information):**
 - Android Version: 13
 - App Version: 1.7.5
 - Other Device Information:

**Additional context**

Link to the playlist: https://www.youtube.com/playlist?list=PLhP7YEsBQj6HON4Z78wg3_HJzw7WdwT9e

**Comment by zaednasr** [comment]
noted

**Comment by zaednasr** [comment]
try the latest version

**Comment by GoldDa** [comment]
Thank you!
