### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gowthamkaliyannan** [deniscerri/ytdlnis#489]
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: wrong OPTS for --compat-options: manifest-filesize-approx

**Comment by zaednasr** [comment]
Go to settings, updating, install new version of yt-dlp
If you cant, you are probably from india, and your isp block network connections from github api's, so switch network temporarily just to update yt-dlp and then u can switch back. It will work
