### ISSUE TITLE
[BUG] ytdlnis ignores my format importance order and selects 360p vp9 video

### ISSUE THREAD

**Issue by soredake** [deniscerri/ytdlnis#492]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
I set preferred quality to 1080p and preferred video codec to vp9, format importance set to this:
![изображение](https://github.com/deniscerri/ytdlnis/assets/5204968/506ef2ea-6381-40ca-8e21-8120efbb5311)

Despite format importance set to prefer video quality and then video codec ytdlnis selects vp9 360p video with this https://youtu.be/pQlF1M8WYx4 video.

**To Reproduce**
Upgrade to latest version, set preferred quality to 1080p, preferred video codec to vp9 and format importance to prefer quality to video codec.

**Expected behavior**
It should select the something in the first three formats, not the fourth:
![изображение](https://github.com/deniscerri/ytdlnis/assets/5204968/3d56743d-2a9e-4055-bbf0-a7b574dce495)

**Screenshots / Video Recording**
https://github.com/deniscerri/ytdlnis/assets/5204968/5bd5e9b1-9e76-463a-86e2-8f4382cc7f4a

**(please complete the following information):**
 - Android Version: 14
 - App Version: [1.7.6](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.6)
 - Other Device Information:

**Additional context**

**Comment by zaednasr** [comment]
There will never be a smooth release i guess 😭. Will look into it

**Comment by zaednasr** [comment]
What needs to be done is to adjust the importance quota. Because it looks like the 360p fulfills 2 criteria 
1. <= 1080p
2. vp9 codec

while the 720s only fulfil 1
But those two less important quotas sum up a greater value than 1. Thats why this happens

**Comment by soredake** [comment]
Even if I put codec to bottom, it will still select 360p vp9.

**Comment by zaednasr** [comment]
@soredake buddy, i found time to look into this and i think i figured it out. Can you dm me on telegram so i can send you an apk? Test it out with different preferences and see if its working correctly

**Comment by soredake** [comment]
@zaednasr sure https://t.me/tttttttttodttttttttt

**Comment by zaednasr** [comment]
@soredake dm'd you

**Comment by zaednasr** [comment]
check out 1.7.8
