### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Achrafibou** [deniscerri/ytdlnis#494]
I downloaded the latest version of ytdlnis 1.7.7 and faced an issue when I clicked  pause the app crashes

**Comment by anwar-alsilwy** [comment]
Same thing here, on v 1.7.7, when I clicked pause and resume the app crashes, and the running files are stuck in the queue, and if I try to resume or redownload them the app crashes again.

**Comment by zaednasr** [comment]
i updated the release with the fix, redownload please
