### ISSUE TITLE
[FEATURE REQUEST] Delete records that are older than a certain period

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#496]
When randomly checking the settings I noticed there were a lot of temporary files from failed downloads which resulted in increased app size. This issue propose a feature that'll automatically delete the records that are older than a certain period. For example deleting temporary files older than 7 days or 1 month.
By "records" i mean this could be implemented for download history and logs as well, not just temporary files.

**Comment by zaednasr** [comment]
Implemented. Please wait for next release

**Comment by zaednasr** [comment]
Checkout [1.7.9](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.9)

**Comment by NikunjKhangwal** [comment]
Thanks
