### ISSUE TITLE
[BUG] Can't download video

### ISSUE THREAD

**Issue by alabotski** [deniscerri/ytdlnis#498]
**Describe the bug**
Can't download video

**To Reproduce**
Шедевр а-ля Капабланка! 💖 Нодирбек Абдусатторов  - Александр Грищук 🏆 UzChess Cup 2024.Шахматы https://www.youtube.com/watch?v=jHANaQ0Gmrc

**Expected behavior**
Possibility to download videos

**Screenshots / Video Recording**
[Screenshot_20240613-134102](https://github.com/deniscerri/ytdlnis/assets/439337/09d975b9-a68e-42a1-85d7-fa77dbc6f196)

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.7
 - Other Device Information: Pixel 7 Pro

**Additional context**
 --no-quiet --no-simulate --print "after_move:'%(filepath,_filename)s'" -N "3" --trim-filenames "222" --write-thumbnail --convert-thumbnails "png" --no-mtime --sponsorblock-remove "music_offtopic" --parse-metadata "uploader:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --parse-metadata "%(uploader,channel,creator,artist|null)s:%(uploader)s" --audio-quality "0" --sponsorblock-mark "all" --embed-chapters --merge-output-format "mp4" --embed-thumbnail -S "+hasaud,vcodec:h264,acodec:aac,vext:mp4,aext:m4a" -f "137+ba/137+ba/137/b" --write-subs --embed-subs --write-auto-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,ru.*,.*-orig" -P "/storage/emulated/0/Movies/Chess" -o "[%(upload_date)s] %(title)s.%(ext)s" --replace-in-metadata "video:title" ".+" "Шедевр а-ля Капабланка! 💖 Нодирбек Абдусатторов - Александр Грищук 🏆 UzChess Cup 2024.Шахматы" --replace-in-metadata "video:uploader" ".+" "Шахматы - это Круто" "https://youtube.com/watch?v=jHANaQ0Gmrc&si=dOuPJqypRyFAqNem"

WARNING: Unable to communicate with SponsorBlock API: The read operation timed out. Retrying (1/3)...
WARNING: Unable to communicate with SponsorBlock API: The read operation timed out. Retrying (2/3)...
WARNING: Unable to communicate with SponsorBlock API: The read operation timed out. Retrying (3/3)...
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: The read operation timed out
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: The read operation timed out

**Comment by zaednasr** [comment]
Turn off sponsor block in the settings. Their servers are probably down
