### ISSUE TITLE
[FEATURE REQUEST] Add option to keep screen always on when watching video

### ISSUE THREAD

**Issue by Sopor** [deniscerri/ytdlnis#501]
**Is your feature request available in yt-dlp? Please describe.**
When playing a video it will not block my screen off timeout.

**Describe the solution you'd like**
An option would have been nice that will keep the screen on when playing a video.

**Comment by zaednasr** [comment]
noted

**Comment by zaednasr** [comment]
check out 1.7.8

**Comment by Sopor** [comment]
There must be something wrong because i can't even start the video. 😥

**Comment by zaednasr** [comment]
refresh your results, or check your piped instace preference. Anything else in the player is not changed from previous releases.

**Comment by Sopor** [comment]
After fiddling around i manage to get it to play, but i don't know what i did 🤔

**Comment by Sopor** [comment]
Sorry to say it, but now it is back again and doing the exact same thing 😥

It will not play, but it will load the buffer. If i try to manually start the video by clicking on the play button, nothing happens.

**Comment by zaednasr** [comment]
dm me on telegram to see if i fixed it.

**Comment by zaednasr** [comment]
Checkout [1.7.9](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.9)

**Comment by Sopor** [comment]
Sorry that i haven't contacted you, but when i tried to create a Telegram account they will send my verification code to my other device. The problem is that i don't have any other device and i'm waiting for a reply from the Telegram support. They doesn't seem to be very fast to reply 🙁
