### ISSUE TITLE
[FEATURE REQUEST] Combine Download and Download queue . Add clear all option in respective panel And edit option for adjust video short cut template 

### ISSUE THREAD

**Issue by dipender98** [deniscerri/ytdlnis#503]
Just create a single screen by combining download(for audio,video,short by date added,name add a filter type option) and download queue. By Creating downloaded option in download queue. Because we have tap twice for access download queue 

And segregate clear cancelled, clear schedule,clear error etc. ("Clear all" options) in their respective panel  Clear all options . So confusing can be avoided

Optional :- Edit/customizing option for adjust video shortcut template like we can add multiple audio by customizing commands

**Comment by zaednasr** [comment]
This was once considered but considering that there are many parts to the download history, and the download queue screen, combining them would become an nightmare to manage, and especially confusing for the users.

One thing we can do is to add the download queue as a tab in the home screen. Like an appearance setting for you to choose
home, history, downloads, terminal, more
5 i guess is the limit for bottom nav in phones.

Clear cancelled thing i agree with you. I guess i could add a chip on top of the list to clear them out, and remove that confusing top menu.

**Comment by dipender98** [comment]
And last one if You got my point of view like adding customised command as template under video adjust 
![Screenshot_20240616-132236_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/98155368/b0d43932-e412-4ea0-85bf-3ed34cba0998)

**Comment by zaednasr** [comment]
tap add extra commands
and put it there

**Comment by zaednasr** [comment]
check out 1.7.8
Separate buttons for clearing all is not implemented, but its considered
