### ISSUE TITLE
[BUG] Cannot resolve symbol 'FileInputStream' in build.gradle

### ISSUE THREAD

**Issue by hamza0786** [deniscerri/ytdlnis#506]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
Cannot resolve symbol 'FileInputStream' in build.gradle

**To Reproduce**

**Expected behavior**

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 
 - App Version:
 - Other Device Information:

**Additional context**

**Comment by zaednasr** [comment]
U might not have installed gradle and gradle plugin in android studio
