### ISSUE TITLE
[FEATURE / FIX] Replace non standard chars in metadata to Standard ones

### ISSUE THREAD

**Issue by decipher3114** [deniscerri/ytdlnis#508]
Basically, this feature will replace all chars that are not the standard unicode chars to their standard counterparts.

Example :
`， [U+FF0C (Full width Comma)]` -> `, [U+002C] (Comma)`

It can be easily implemented as there are only 4-5 such chars, namely

- Comma
- Space
- Dots
- Ampersand
- Pipe Symbol

You can search for the symbols that may exist in place of the UTF ones.

**Comment by zaednasr** [comment]
oh damn i forgot about this...
next release i guess

**Comment by zaednasr** [comment]
This could be done in title and author if they are filled out in the download card, but about the rest???
I have no idea

**Comment by zaednasr** [comment]
I think you should just add your own extra command with --replace-in-metadata
