### ISSUE TITLE
[BUG] scheduled download problems

### ISSUE THREAD

**Issue by error-reporting** [deniscerri/ytdlnis#511]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
scheduled download does not download the video when the time I set had been reached 
**To Reproduce**
download any video with scheduled download feature
**Expected behavior**
when the scheduled time I had set comes the scheduled video downloads
**Screenshots / Video Recording**
If applicable, add them to help explain your problem.
![Screenshot_2024-06-28-18-32-58-61_2bde0e07fd61d625cf63c538621e2efc](https://github.com/deniscerri/ytdlnis/assets/166897813/acacb567-28c8-4ece-9095-069766e58d4d)

**(please complete the following information):**
 - Android Version: color os 7.2 android 10
 - App Version: 1.7.7
 - Other Device Information:

**Additional context**
the current time is well over the time I had set in the scheduled download feature
This seems to be a regression because there is no problem using this feature in 1.7.5

**Comment by zaednasr** [comment]
Try turning off battery optimization in the app. Android is probably not prioritizing the scheduled job.

**Comment by error-reporting** [comment]
I have turn off battery optimization in my phone's settings 
![Uploading Screenshot_2024-06-28-18-49-09-93.jpg…]()

**Comment by error-reporting** [comment]
if Android is not prioritizing the scheduled job then why the app or android is not executing the job for over 20 minute I have set the time to 18:30 and now is 19:01

**Comment by zaednasr** [comment]
I'll check what version there was in 1.7.5 because scheduling didn't really change. Maybe a library update.

**Comment by zaednasr** [comment]
Same version

**Comment by zaednasr** [comment]
I'll test it out today

**Comment by error-reporting** [comment]
Here is extra information: I'm currently using the arm64 version of this app installed from f-droid

**Comment by error-reporting** [comment]
you seems to forget about the issue I have reported just like your app forget to download the scheduled task

**Comment by zaednasr** [comment]
@error-reporting i have a life. i dont work on the app 24/7
Also its not as easy. I tested yesterday and it ran as expected, so im still looking at it

**Comment by zaednasr** [comment]
dont close it lol

**Comment by error-reporting** [comment]
sorry I found the reason for the problem and is on the phone's separate battery optimization settings 
![Uploading Screenshot_2024-06-29-13-33-42-05.jpg…]()

**Comment by zaednasr** [comment]
great, im happy its resolved

**Comment by error-reporting** [comment]
after the 1.7.8 update scheduled download fail to work even when the app is active

**Comment by zaednasr** [comment]
testing...

**Comment by zaednasr** [comment]
dm me on telegram, ill send you a debug apk to test on, because for me it never fails. well get to the bottom of this

**Comment by error-reporting** [comment]
How to dm on telegram

3 thg 7, 2024 21:25:26 zaednasr ***@***.***>:

**Comment by zaednasr** [comment]
join the telegram group, its in the readme
