### ISSUE TITLE
[FEATURE REQUEST] Add extra content in the file.txt

### ISSUE THREAD

**Issue by 7Codez** [deniscerri/ytdlnis#514]
**Is your feature request available in yt-dlp?**
Yes it's available in yt-dlp.

**Describe the solution you'd like**
Write content extra in .txt 
Why?  We need a lot of blocks and important texts in file.txt such as : 

ContentExtra.txt
> %(creator)s
%(like_count)s
%(dislike_count)s
%(comment_count)s
%(original_url)s
%(release_year)s
%(timestamp)s
%(modified_timestamp)s
%(release_timestamp)s
%(uploader_id)s

This is a feature that can be customized with the same idea as a feature that exists now in 
> Settings > Folders > Filename Template [Video]

Because the number of characters is very limited for the name of a video file, we need this feature to add important texts in proportion to each person who will allocate it to the information they need from that video on YouTube.

The new feature same idea is to create a new file specifically for the video description, such as 
>Save Description (Write description file)

The new feature
> Add more content to the *.txt file.

New features concept is to expressly generate a new file.

**Comment by zaednasr** [comment]
I have not heard of this feature. Do you have a yt-dlp command example of what is supposed to happen?

**Comment by teddysulaimanGL** [comment]
This can be easily done using Extra Command 🤷🏻‍♂️

**Comment by teddysulaimanGL** [comment]
```
--print-to-file "TITLE= %(title)s," "%(title)s-%(channel)s-%(upload_date>%Y-%m-%d)s [%(id)s].txt"
--print-to-file "ID= %(id)s," "%(title)s-%(channel)s-%(upload_date>%Y-%m-%d)s [%(id)s].txt"
--print-to-file "DESCRIPTION= %(description)s, " "%(title)s-%(channel)s-%(upload_date>%Y-%m-%d)s [%(id)s].txt"
--print-to-file "CHANNEL= %(channel)s, " "%(title)s-%(channel)s-%(upload_date>%Y-%m-%d)s [%(id)s].txt"
--print-to-file "DATE UPLOAD= %(upload_date>%Y -%m-%d)s" "%(title)s-%(channel)s-%(upload_date>%Y-%m-%d)s [%(id)s].txt"
```
https://github.com/yt-dlp/yt-dlp/issues/9520#issuecomment-2016581622

This is an example
