### ISSUE TITLE
Unable to download X Spaces Audio Records

### ISSUE THREAD

**Issue by ondern** [deniscerri/ytdlnis#523]
I use v1.7.8 latest version and logged in to X to keep my cookies. I am paid pro member for some channels.

Channel Link: 

Prof. Dr. Özgür Demirtaş
https://x.com/ProfDemirtas?t=OYo8Ky8MXPx0DvGScX2UHQ&s=09

Spaces Link for pro members: 

Abonelere Özel 13. Canlı Yayın
https://x.com/i/spaces/1dRKZEdbvYgxB

YTDLNis Logs Attached
[logs.txt](https://github.com/user-attachments/files/16172167/logs.txt)

**Comment by teddysulaimanGL** [comment]
This is not within the developer's scope. Instead, create an issue [here](https://github.com/yt-dlp/yt-dlp/issues)

**Comment by ondern** [comment]
Thank you

**Comment by ondern** [comment]
https://github.com/yt-dlp/yt-dlp/issues/10423
