### ISSUE TITLE
[BUG]Issue downloading subtitles 

### ISSUE THREAD

**Issue by jyrg02** [deniscerri/ytdlnis#524]
**Describe the bug**
Videos where subtitles are embedded do not download. The subtitles for the video I tried to download where not auto-generated, meaning that the video had existing subtitles. 

**(please complete the following information):**
 - Android Version: 14
 - App Version:YTDLnis-1.7.8-arm64-v8a-release.apk
 - Other Device Information:

**log**
 -N "3" --trim-filenames "183" --no-mtime --sponsorblock-remove "music_offtopic" --parse-metadata "uploader:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --parse-metadata "%(uploader,channel,creator,artist|null)s:%(uploader)s" --sponsorblock-mark "all" --embed-chapters -f "625+251/625+ba/625/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig,en,en-IN,en-GB" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/41" -o "%(uploader).30B - %(title).170B.%(ext)s" --replace-in-metadata "video:title" ".+" "SABATON - Cliffs Of Gallipoli (Official Music Video)" --replace-in-metadata "video:uploader" ".+" "Sabaton" "https://youtu.be/oOCe2Y7iVF8"

WARNING: Only WebVTT subtitles can be embedded in webm files
ERROR: Postprocessing: file:/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/41/Sabaton - SABATON - Cliffs Of Gallipoli (Official Music Video).en.temp.srt.concat: Math result not representable

**Comment by teddysulaimanGL** [comment]
It means you're being rate-limited. The workaround is to not request too many subs in one go, let it cool down, and try again later

**Comment by jyrg02** [comment]
I've been having this issue repeatedly. In June 23rd I had the same issue. 
![Screenshot_20240711_122743](https://github.com/deniscerri/ytdlnis/assets/99687156/a952c92e-555f-420b-a99a-c6bbe395c4a8)

**logs**
 -N "3" --trim-filenames "184" --no-mtime --sponsorblock-remove "music_offtopic" --parse-metadata "uploader:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --parse-metadata "%(uploader,channel,creator,artist|null)s:%(uploader)s" --sponsorblock-mark "all" --embed-chapters -f "625+ba/625+ba/625/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/1" -o "%(uploader).30B - %(title).170B.%(ext)s" --replace-in-metadata "video:title" ".+" "SABATON - Cliffs Of Gallipoli (Official Music Video)" --replace-in-metadata "video:uploader" ".+" "Sabaton" "https://www.youtube.com/watch?v=oOCe2Y7iVF8"

WARNING: Only WebVTT subtitles can be embedded in webm files
ERROR: Postprocessing: file:/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/1/Sabaton - SABATON - Cliffs Of Gallipoli (Official Music Video).en.temp.srt.concat: Math result not representable

**Comment by zaednasr** [comment]
Try updating yt-dlp, or switching yt-dlp source
I managed to download it with that exact configuration
