### ISSUE TITLE
[BUG] Video title doesn't change in the download card

### ISSUE THREAD

**Issue by Omegaplexx** [deniscerri/ytdlnis#526]
**Describe the bug**
The title of the video I want to download is the same when I try to download another videos.

**To Reproduce**
1. Search something from YTDLnis main screen
2. Open the download card of the selected result
3. Now close it and select another video
4. You'll see the title of the first video

**Screenshots / Video Recording**

https://github.com/user-attachments/assets/20b7ce39-a23f-4046-ad49-f41da5a3b8d7

 - Android Version: 10
 - App Version: 1.7.8 (107080004) (that one you sent me in TG)
 - Other Device Information: Samsung Galaxy S7, LineageOS 17.1

**Comment by zaednasr** [comment]
noted

**Comment by zaednasr** [comment]
fixed, u can ask me the apk if u want

**Comment by Omegaplexx** [comment]
Thanks again! I guess I'd better wait for the release so I don't bother you too often. In case you find more bugs?
