### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jostico96** [deniscerri/ytdlnis#527]
ERROR: [youtube] AL5vANu2gok: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

I tried with cookie and it doesn't work either.
Any solution .

**Comment by teddysulaimanGL** [comment]
"[Your IP has been blocked by YouTube while you are logged out. You can pass logged-in cookies; however, doing so may get your account blocked. The better workaround is to try changing your IP](https://github.com/yt-dlp/yt-dlp/issues/3766)"
