### ISSUE TITLE
[BUG]APP CRASH

### ISSUE THREAD

**Issue by Miseryset** [deniscerri/ytdlnis#529]
Binary XML file line #85 in com.deniscerri.ytdl:layout/fragment_download_video: Binary XML file line #127 in com.deniscerri.ytdl:layout/format_item: Error inflating class TextView

**Comment by zaednasr** [comment]
Can you reproduce this? When does it happen?

**Comment by Miseryset** [comment]
> Can you reproduce this? When does it happen?

![S40727-18080508_com deniscerri ytdl](https://github.com/user-attachments/assets/2b54bcf9-9d61-4d6a-ab2e-0eaa0850acaf)
Click these two buttons on the home page, and the app will crash.
My device is Android 14, flyme 10.

**Comment by zaednasr** [comment]
dm me on telegram, ill hook you up with an apk to try it out

**Comment by zaednasr** [comment]
Checkout [1.7.9](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.9)
