### ISSUE TITLE
instagram:story] unable to extract user info;

### ISSUE THREAD

**Issue by davotoula** [deniscerri/ytdlnis#530]
-N "3" --trim-filenames "183" --no-mtime --sponsorblock-remove "music_offtopic" --force-keyframes-at-cuts --parse-metadata "uploader:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --parse-metadata "%(uploader,channel,creator,artist|null)s:%(uploader)s" --sponsorblock-mark "all" --embed-chapters --merge-output-format "mp4" --embed-thumbnail --convert-thumbnails "jpg" -S "+hasaud,vcodec:h264,acodec:aac,vext:mp4,aext:aac" -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/39" -o "%(uploader).30B - %(title).170B.%(ext)s" "https://www.instagram.com/stories/draegonqueen/3416467090595210168?utm_source=ig_story_item_share&igsh=MXhyYmlkaHNyY2plbg=="

WARNING: [instagram:story] unable to extract user info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [instagram:story] 3416467090595210168: This content is unreachable. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

**Comment by zaednasr** [comment]
This is yt-dlp related. Update yt-dlp or use cookies to login to instagram and download again. If it persists do as the error says
report it to yt-dlp
