### ISSUE TITLE
[BUG] " - Topic" isn't removed from author

### ISSUE THREAD

**Issue by thismoon** [deniscerri/ytdlnis#532]
**Describe the bug**
when i search for a song directly in the ytdlnis app, the ` - Topic` suffix gets removed. however when i paste a link or share a link from another app to ytdlnis, ` - Topic` stays

**To Reproduce**
- copy the link of a youtube video from a topic channel
- paste the url in the ytdlnis app/share it to the ytdlnis app
- the author still has the topic suffix. i always manually remove it

**Expected behavior**
that suffix should be automatically removed

**Screenshots / Video Recording**
i believe the issue is clear so no need for screenshots

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.7.8
 - Other Device Information:

**Additional context**
PS: when making the issue i couldn't find the app version anywhere in the app and had to check neo store for it. is it hidden somewhere or it doesn't exist?

**Comment by teddysulaimanGL** [comment]
1. The suffix should be removed automatically in the next release.
2. The app version is in the Updating settings section, just scroll a little further, you'll find it

**Comment by zaednasr** [comment]
Checkout [1.7.9](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.9)
