### ISSUE TITLE
[BUG] APP CRASHED 

### ISSUE THREAD

**Issue by MustafaMemisogM** [deniscerri/ytdlnis#534]
Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference

com.deniscerri.ytdl.ui.downloads.QueuedDownloadsFragment$onQueuedCardSelect$1.invokeSuspend(SourceFile:247)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
android.os.Handler.handleCallback(Handler.java:958)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loopOnce(Looper.java:222)
android.os.Looper.loop(Looper.java:314)
android.app.ActivityThread.main(ActivityThread.java:8602)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.8
 - Other Device Information:

**Additional context**

**Comment by zaednasr** [comment]
I believe this has been fixed. Wait for next release

**Comment by zaednasr** [comment]
Checkout [1.7.9](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.9)
