### ISSUE TITLE
[FEATURE REQUEST] Allow for Scheduled download for YouTube Premieres 

### ISSUE THREAD

**Issue by Aryanxfa** [deniscerri/ytdlnis#535]
**Is your feature request available in yt-dlp?**
So, I want to schedule a download for any upcoming premieres. yt-dlp currently just throws error
With ytdlnis, If i share a youtube link of the same i get the error Premier will start in 2 hours or something. 

**Describe the solution**
I want implement this functionality to catch this error from ytdlp and automatically schedule it 3 or more hours later (given the length of the video is arbitary but very predictable by end user) 
OR
Just don't close the popup so the end user can schedule it manually

**Alternatives you've considered**
Since the popup closes after throwing an error its not feasible to schedule it directly.

**Comment by zaednasr** [comment]
When you share the link and the error pops up just copy the error and the app wont close the download card. There just tap the clock and schedule. 

The error is just the app failing to get data because it's not out yet

**Comment by Aryanxfa** [comment]
> When you share the link and the error pops up just copy the error and the app wont close the download card. There just tap the clock and schedule. 
> 
> The error is just the app failing to get data because it's not out yet

Thanks for the quick reply. I tested its behaviour, Surprisingly it works but only when i press copy logs. Both either pressing back or pressing outside of the popup completely removes the share menu.  I would appreciate a **continue anyway** button. So it's more clear that there is a way to override this. 

Also i had a query, would it be possible to schedule a command to run at a specific time given that the command automatically downloaded the latest available video from YouTube. Would Scheduling the command with a random video would do it? Or is there a way to achieve it in a different way.

**Comment by zaednasr** [comment]
I'll add continue anyway thx.
Also for the second point, if your planning to download latest videos of a playlist or a channel, the app has the observe sources feature. It's in more section

**Comment by Aryanxfa** [comment]
Sure, I'll look into the observe source option. I must say, you've built this app quite well! Thanks for that! 

Also, please feel free to close the issue as you see fit.
