### ISSUE TITLE
[FEATURE REQUEST] Include Extra command input by default

### ISSUE THREAD

**Issue by bheeshmpita** [deniscerri/ytdlnis#537]
**Is your feature request available in yt-dlp? Please describe.**
I want a functionality to embed subtitles (if present) else embed auto-subtitles without any subtitle file. Currently, there is no single functionality to achieve all these steps at once. 

**Describe the solution you'd like**
So until a new yt-dlp functionality achieves this, I can achieve this by enabling _embed subs, write subs, write auto subs_ in settings and if i can enable an Extra Command input by default such as `--compat-options no-keep-subs`, the purpose can achieved but for now i have to give this input every time.

**Describe alternatives you've considered**

**Additional context**
(context [https://github.com/yt-dlp/yt-dlp/issues/826](url), 
[https://github.com/yt-dlp/yt-dlp/issues/630#issuecomment-893659460](url))

**Comment by zaednasr** [comment]
Go to more
Command templates
Add template
Write the command
Check extra command for audio or video download type

**Comment by teddysulaimanGL** [comment]
The option is already there.

![Screenshot_20240730_181344.png](https://github.com/user-attachments/assets/3530f055-1ba9-4b2c-821d-b22440c1dc5f)

**Comment by bheeshmpita** [comment]
@zaednasr @teddysulaimanGL Can you help me by guiding how to actually use this template while downloading videos along with presets on video info card. From my limited knowledge isnt this feature for those situtations when you manually give the command to yt-dlp?
Thanks

**Comment by teddysulaimanGL** [comment]
It'll always be passed along the GUI configurations. You don't need to do anything else once you set it as "Extra Command"

**Comment by zaednasr** [comment]
If you check extra command the app will write it for you in the extra commands section every time you download
