### ISSUE TITLE
The app can't download and gives me a sign in error pop up

### ISSUE THREAD

**Issue by mahdi921** [deniscerri/ytdlnis#540]
ERROR: [youtube] juN_nnlzlh4: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

How do I sign in from the app?

**Comment by teddysulaimanGL** [comment]
Duplicate of https://github.com/deniscerri/ytdlnis/issues/527

**Comment by zaednasr** [comment]
https://github.com/yt-dlp/yt-dlp/issues/10128
