### ISSUE TITLE
[BUG] APP CRASH - List is empty 

### ISSUE THREAD

**Issue by MustafaMemisogM** [deniscerri/ytdlnis#541]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
When observe resources find a video than app is crashed 

**To Reproduce**

**Expected behavior**

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.9
 - Other Device Information:

**Additional context**

List is empty.

kotlin.collections.CollectionsKt.first(SourceFile:2)
com.deniscerri.ytdl.work.DownloadWorker$doWork$3$emit$4$1$4$1.invokeSuspend(SourceFile:734)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:139)
kotlinx.coroutines.JobKt.runBlocking(SourceFile:102)
kotlinx.coroutines.JobKt.runBlocking$default(SourceFile:3)
com.deniscerri.ytdl.work.DownloadWorker$doWork$3$emit$4$1.invokeSuspend(SourceFile:853)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
androidx.work.Worker$2.run(SourceFile:39)
kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)

**Comment by zaednasr** [comment]
dm me on telegram, i made some changes see if they work for you
