### ISSUE TITLE
After update to 1.7.9, YTDLnis does not follow predefined ID to download audio [BUG]

### ISSUE THREAD

**Issue by mauriicio3** [deniscerri/ytdlnis#542]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
After update to 1.7.9, YTDLnis does not follow predefined ID to download audio [BUG]

**To Reproduce**
Change preferred ID for download audio
Try to download audio from a video
appears a window with various options,
but it not follow ID previously defined.

**Expected behavior**
I expected appears a window with my previous preferred ID checked.

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.9
 - Other Device Information: Xiaomi Redmi 7A

**Additional context**

**Comment by zaednasr** [comment]
Send url
Your preferred format id settings
Your format importance order settings

**Comment by mauriicio3** [comment]
- Send url
I've tested many, all have this situation

- Your preferred format id settings
same here: tested all id settings, none has followed
example: 128kbps
example: wa

- Your format importance order settings
I not change here

Thank for your attention!
Sorry my English



Maurício




Em seg., 5 de ago. de 2024, 02:46, zaednasr ***@***.***>
escreveu:

**Comment by teddysulaimanGL** [comment]
Preferred ID only accepts the actual ID, not the filtering like bitrate and generic "ba" or "wa." Generic "ba" and "wa" are already recognized as "Best Quality" and "Worst Quality"

**Comment by zaednasr** [comment]
![image](https://github.com/user-attachments/assets/ef322b59-7659-40a9-afee-7a4eed7da520)
Preferred ID checks only this element in the format item, nothing else
