### ISSUE TITLE
[BUG] TikTok links still opening in web browser

### ISSUE THREAD

**Issue by MulverineX** [deniscerri/ytdlnis#543]
**Describe the bug**
TikTok links opened from chat apps like Beeper & Discord open in Firefox.

**To Reproduce**
- Ensure TikTok is not installed 
- Add TikTok to supported links in YTDLnis App Info
- Force stop chat apps
- Open up a chat app and attempt to open the TikTok link in YTDLnis

**Expected behavior**
The link should open the popup downloader dialogue when pressed.

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.9

**Comment by zaednasr** [comment]
This is a Google issue. Since android 12 and above, Google wants the app to undergo verification to allow links to open by default to it. But since that can't happen because this app is also a youtube downloader, it is what it is.

**Comment by MulverineX** [comment]
@zaednasr I don't think I phrased the report very well, I'm not talking about automatic/default behavior. Manually setting the link association isn't working.

https://youtu.be/UvVk_HdqzdQ

**Comment by 7Grn** [comment]
YTDLnis is only 'tiktok.com' appears to be on the list
![Screenshot](https://github.com/user-attachments/assets/abfb43b4-3a9e-4aab-92e3-7eae3cf7916b)
@zaednasr can you add "www.tiktok.com" link

**Comment by MulverineX** [comment]
Oh yeah true that might be the issue here

**Comment by 7Grn** [comment]
> Oh yeah true that might be the issue here
@MulverineX currently it works fine if you use the "tiktok.com" link

**Comment by zaednasr** [comment]
Alright, i added the www.titktok but i cant seem to make the app show up lol.

**Comment by 7Grn** [comment]
ahh sorry if i misunderstood you as a YTDLnis dev

**Comment by zaednasr** [comment]
im the dev

**Comment by zaednasr** [comment]
https://github.com/deniscerri/ytdlnis/issues/447#issuecomment-2162144513

Check this out. I installed this app and it works if i long press and tap open. Its meant to bypass the android 12+ limitations

**Comment by zaednasr** [comment]
Meanwhile ill add the other variants for each supported url in the app to be safe

**Comment by MulverineX** [comment]
I'm just trying to figure out why YouTube Revanced works and this doesn't

**Comment by zaednasr** [comment]
@MulverineX it was the alternate domains. I added them on youtube and tiktok, disabled them from rvx and added them in the app and they opened up as expected.
