### ISSUE TITLE
[BUG] Automatically delating downloaded video

### ISSUE THREAD

**Issue by Ktosnapewno999** [deniscerri/ytdlnis#544]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
After downloafing any video app automatically delate it

**To Reproduce**
Just download video

**Expected behavior**

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 14
 - App Version:1.7.9[arm]
 - Other Device Information:Samsung m13 with one ui 6.1

**Additional context**
File is backup of settings 
[YTDLnis_1.7.9_2024-8-5 [902.json](https://github.com/user-attachments/files/16500212/YTDLnis_1.7.9_2024-8-5.902.json)

**Comment by zaednasr** [comment]
try to enable all files access and try again

**Comment by Ktosnapewno999** [comment]
It all time app have this acces

**Comment by zaednasr** [comment]
dm me on telegram

**Comment by zaednasr** [comment]
@Ktosnapewno999 you up?

**Comment by Ktosnapewno999** [comment]
ok reinstaling app helped
