### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ashokkumarmallick58** [deniscerri/ytdlnis#547]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
A clear and concise description of what the bug is.WARNING: [instagram:story] unable to extract user info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [instagram:story] 3432183931999633494: This content is unreachable. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credential

**Comment by zaednasr** [comment]
What you can do
- login to instagram to get cookies in the more -> cookies section
- update yt-dlp in the updating settings
- switch yt-dlp version

If all fail
the create the issue to yt-dlp as this is not really an app bug.
