### ISSUE TITLE
[BUG]The package is packaged as ABB and then distributed as apk. Failed to init is displayed

### ISSUE THREAD

**Issue by zhangyinglong1993** [deniscerri/ytdlnis#548]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 
 - App Version:
 - Other Device Information:

**Additional context**

**Comment by zaednasr** [comment]
I have never packaged as aab. Only apk splits

**Comment by zhangyinglong1993** [comment]
> 我从来没有打包成aab，只有apk拆分

Can you help me out? I use Google's BundleTools, distributed apk. There's a problem. I can't fix it.

**Comment by zaednasr** [comment]
Please show more information about how you set up android studio. Because i tried to build as aab and it built
