### ISSUE TITLE
download music with synced lyrics 

### ISSUE THREAD

**Issue by ItsElw** [deniscerri/ytdlnis#550]
hi.there is any way to download music with synced lyrics ?

**Comment by zaednasr** [comment]
This is not supported yet.
Follow this issue as its still open:
[https://github.com/yt-dlp/yt-dlp/issues/5635](https://github.com/yt-dlp/yt-dlp/issues/5635)

**Comment by 0xKernelEclipse** [comment]
https://github.com/deniscerri/ytdlnis/issues/991
