### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Turkialh14** [deniscerri/ytdlnis#553]
There are two features suggested, the first is desirable and the second is according to your ability.

1-I want to add a feature to specify the bit rate in the general interface because it is difficult with the terminal, especially with many formats.

Terminal commands that can be added to the public interface
tbr: Total average bitrate in kbps
vbr: Average video bitrate in kbps
abr: Average audio bitrate in kbps

General interface commands such as choosing the highest video or audio bit rate and customizing each one.

like -S "res:1080,br>3000kbps" or like -S "res:1080,br"(Which means the best bit rate at the same quality)

Note:It will be especially useful with playlists and txt files that contain multiple links.

2-Show video bitrate and audio bitrate when editing download tag

**Comment by zaednasr** [comment]
Why did you close it lol

**Comment by zaednasr** [comment]
Nvm 🤣😭

**Comment by Turkialh14** [comment]
I'm new here my bad

**Comment by zaednasr** [comment]
I just realized, you can do this using extra commands. Tap it and u can see already the app using -S.
You can write down another -S, i believe yt-dlp takes the last one so yours will apply.
Modify the current -S to add that bitrate thing, or whatever you like.

**Comment by Turkialh14** [comment]
I don't know much about programming but if yt-dlp will leave the -s command that the system puts and take my command I will try it Thank you I also have another problem that I don't think is worth opening another case for I have a txt file that contains 4700 YouTube video URLs when I share it with the application it becomes very slow when displaying the videos unlike when I use the playlist method

**Comment by zaednasr** [comment]
can you send me that file, so i can test with it.

**Comment by Turkialh14** [comment]
Ok on telegram, as you like

**Comment by zaednasr** [comment]
u can send here if u want
