### ISSUE TITLE
[FEATURE REQUEST] add subfolders in download location 

### ISSUE THREAD

**Issue by KamrulShahed** [deniscerri/ytdlnis#556]
It would be nice to have sub folder support in download location. I mean downloaded files should go to subfolders naming the site name it is downloader from. Seal has this feature and i like it very much. It makes organizing files easy and time saving when there is a lot of downloaded files.

**Comment by teddysulaimanGL** [comment]
[Q: What does Filename Template do? Is it limited to filename usage?
  A: This preference name often leads to confusion, and the answer for that question is no. You can always use it to create subfolder(s) with the suggested template like %(playlist)s/%(title)s, or with literal name like My media/%(title)s, even combining them…](https://t.me/ytdlnis/36055/66670)

**Comment by KamrulShahed** [comment]
It worked. Thanks
