### ISSUE TITLE
[youtube] Sign in to confirm you’re not a bot. This helps protect our community

### ISSUE THREAD

**Issue by zaednasr** [deniscerri/ytdlnis#559]
THIS IS A yt-dlp RELATED ISSUE.
Please follow this issue in their repository for latest development:
[https://github.com/yt-dlp/yt-dlp/issues/10128](https://github.com/yt-dlp/yt-dlp/issues/10128)

**Comment by mablue** [comment]
```
Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
ERROR: [youtube] 4zm45tQd8QI: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

```

**Comment by Zhuliyer** [comment]
I've also encountered this problem, how should I solve it? My phone model is the Samsung S24Ultra.

**Comment by Nusab19** [comment]
If the app had a sign-in option, then it could use the cookies directly and this error would not occur.

For example this is what the app SnapTube does. It works as a browser, so YouTube doesn't flag it as a bot.

**Comment by deniscerri** [comment]
@Nusab19 there is a cookies section, use that to sign in

**Comment by Nusab19** [comment]
> [@Nusab19](https://github.com/Nusab19) there is a cookies section, use that to sign in

I'm using that at the moment. It's working fine.

But from my previous experience with yt-dlp, the cookies expire pretty soon and need to be re-fetched.

So, if there was a way to make the cookies persistent, as the user is already signed-in, that would be more handy.


It works for now. But as always, there's always room for improvement. _(true for any app)_
