### ISSUE TITLE
[BUG] can't download playlists in 1.7.9.1

### ISSUE THREAD

**Issue by jeyjai** [deniscerri/ytdlnis#561]
**Describe the bug**
Can't download playlists in 1.7.9.1

**To Reproduce**
1. Paste the link to a playlist 
2. Nothing shows up

**Expected behavior**
Other versions, even 1.7.9, you paste the link and you get all the videos as result.

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.9.1
 - Other Device Information:

**Additional context**
1.7.9.1 is not marked as prerelease so its impossible to skip it with apps like obtainium

**Comment by zaednasr** [comment]
Go to general settings
General
Data fetching extractor

Select newpipe
Piped is broken i guess
The app was supposed to fall back to ytdlp but o guess an easy bug fix I'll do later

**Comment by jeyjai** [comment]
> Go to general settings General Data fetching extractor
> 
> Select newpipe Piped is broken i guess The app was supposed to fall back to ytdlp but o guess an easy bug fix I'll do later

My app already said ytdlp and newpipe in settings after updating, but it started working by itself by changing any setting whatsoever and restarting the app, even unrelated settings like "high contrast"

So my theory is that the app used the values from the old settings on something you've changed that either stayed the same when updating or gets changed back every time i restore a backup, possibly the extractor, and changing any setting whatsoever forces the app to adapt the choises the settings menu says its suppose to be using.

So if anyone else is having any issues, just have them change something minor, restart the app, and change it back

**Comment by error-reporting** [comment]
not a download issue rather is more of an ytdlnis gui do not show yt-dlp -f 9x mediaconnect format
