### ISSUE TITLE
[FEATURE REQUEST] Add Socket Timeout

### ISSUE THREAD

**Issue by Judas87Swiff** [deniscerri/ytdlnis#562]
**Is your feature request available in yt-dlp? 
No?

**Describe the solution you'd like**
A Download timeout (limited time for download attempt duration), for example if viewing any older vider from Iwara (MMD videos) you notice that 'waiting' for those videos would stop all other videos from being able to downloaded (if using this program) due to the servers not storing such old videos in quickly accessible storage.
So, roughly the same issue persists when '!attempting to download certain ancient Youtube videos (quite often old MMD videos) so a time limit for DLing then skipping to finish the queue then trying again (Try Again - Should be a Togglable Option).

**Describe alternatives you've considered**
Waiting for it to error out, doesn't work.

**Additional context**
To test the issue:

Try 'MMD Motion' then have Youtube sort by Date (oldest).
Or any older MMD video with less than 1K views, should see the issue.

![Example Video FINALLY loaded, whatever was slowing it down to nothing stopped... so I'm outta good 'really old' videos to point out, just try any really old video no one would ever watch I guess should be the same....?]!

[Example of lesser watched ancient MMD R18 Motion R-18]- 53K views but 11 Years Old
Kirino and KuroNeko on a HorseRiding Machine
[NSFW]
https://www.Youtube.com/watch?v=6clOYD1hx-s

**Comment by zaednasr** [comment]
@Judas87Swiff does yt-dlp have a timeout command?

**Comment by zaednasr** [comment]
you can set that as a command template and set it as extra command so it applies to your downloads every time

**Comment by zaednasr** [comment]
its added in the downloads settings

**Comment by zaednasr** [comment]
Please check out the latest release [1.8.0](https://github.com/deniscerri/ytdlnis/releases/tag/v1.8.0)
