### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Judas87Swiff** [deniscerri/ytdlnis#563]
**Is your feature request available in yt-dlp? Please describe.**
Accidently Deleting a video/file leads to not being able to Undelete it to restore it back.

**Describe the solution you'd like**
Add a Windows Trash/Recycle Bin option, On by Default.

**Comment by zaednasr** [comment]
The app already has a confirmation dialog for delete, also there is a 3 second window to bring the record back from the snackbar below.
Be careful next time

**Comment by zaednasr** [comment]
To delete you swipe left 
Then app asks you to confirm
Then app shows a snackbar that it was deleted with an undo button

It doesn't seem that easy to delete something
