### ISSUE TITLE
fastlane changelogs MUCH too long

### ISSUE THREAD

**Issue by IzzySoft** [deniscerri/ytdlnis#564]
Fastlane changelogs are limited to 500 characters, yours currently have almost 10 times the size. Can you please limit them to the most important changes? Those who want the full details could then be linked to the full changelog, which can be configured with the app's YAML here at IzzyOnDroid (currently pointing to the releases page, but I could change that to [point here](https://github.com/ArcaneChat/android/blob/main/CHANGELOG.md) instead).

**Comment by zaednasr** [comment]
"Suffering from success"
Alright ill make CHANGELOG.md file for you to point to and make fastlane shorter

**Comment by IzzySoft** [comment]
There already [is a Changelog.md](https://github.com/ArcaneChat/android/blob/main/CHANGELOG.md) I can link to. You only need to take care to keep the [per-release changelogs in Fastlane](https://github.com/deniscerri/ytdlnis/tree/main/fastlane/metadata/android/en-US/changelogs) at max 500 chars :wink:

**Comment by zaednasr** [comment]
Here is the changelog, and this latest fastlane might be the shortest ever 😉

[https://github.com/deniscerri/ytdlnis/blob/main/CHANGELOG.md](https://github.com/deniscerri/ytdlnis/blob/main/CHANGELOG.md)

**Comment by IzzySoft** [comment]
Thanks!

**Comment by IzzySoft** [comment]
Now the only problem is how to match the names. The arm64 APK has `versionCode: 107090204`. The corresponding Fastlane changelog would be `10792.txt`. No way to match that by a math equation. Even your universal APK comes as `107090200`. Fastlane's definition is `<versionCode>.txt` – none of your versionCodes match there. The most recent one should be `107090200.txt` (matching the universal APK). Then evaluating the name from the arm64 would be as simple as `<versionCode> -4`. As it's currently set up, none of those per-release changelogs would ever be matched by anything. Mind to adjust the names accordingly, starting with the latest one?

**Comment by zaednasr** [comment]
The 4 there is weird 🤔 but universal is correct.

**Comment by zaednasr** [comment]
10792 or 1070902?

**Comment by IzzySoft** [comment]
> The 4 there is weird

Not really. It's the ID of the ABI, here: `arm64-v8a`, [see here](https://github.com/deniscerri/ytdlnis/blob/main/app/build.gradle#L119) – number 4 in that list. You've [configured here](https://github.com/deniscerri/ytdlnis/blob/main/app/build.gradle#L89) to apply it that way :wink: 

> 10792 or 1070902?

It should match what you [calculated for the UniversalApk](https://github.com/deniscerri/ytdlnis/blob/main/app/build.gradle#L49). For IzzyOnDroid, 1070902 would work, too (I'd then adjust the calculation to `(<versionCode> -4)/100`) – but your calculation is:

    versionCode versionMajor * 1000000 + versionMinor * 10000 + versionPatch * 100 + versionBuild

That would currently be 1070902. But the APK shows 107090200 as you [multiply that by 100](https://github.com/deniscerri/ytdlnis/blob/main/app/build.gradle#L92).

So: ideally 107090200 (to match the UniversalApk and thus also valid for other places which might use it), but for IoD 1070902 would work as well as we can adjust that accordingly in this case. Just let me know which of the two it will be, so it's being fetched correctly with the next update :wink:

**Comment by zaednasr** [comment]
@IzzySoft Sorry for being so late, i have been busy.
All the changelogs are renamed like the 107090200 structure.

Also just a headsup, the new version has increased in size a bit due to demand to update to python 3.11 instead of 3.8 because it recently got deprecated by yt-dlp, and other libs got updated like aria2c, ffmpeg and mutagen.
Also with the support of Android 15, foreground services which the app uses to download need to be explicitly stated. So i did as such in the manifest:

```
 <service
            android:name="androidx.work.impl.foreground.SystemForegroundService"
            android:foregroundServiceType="specialUse"/>
```
and the permission that the service uses

```
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_SPECIAL_USE" />
```

Let me know when things are set for you so i can drop the release because its long overdue 😅

**Comment by zaednasr** [comment]
Please check out the latest release [1.8.0](https://github.com/deniscerri/ytdlnis/releases/tag/v1.8.0)

**Comment by IzzySoft** [comment]
Thanks! Adjusted the calculation to `<versionCode> -4` (i.e. `- versionBuild`, as IoD graps arm64 that is "4" – to get the "base code" from the ABI-specific one), and it seems to pull the changelog fine. Size (the original issue) is fine as well – so I'd say all done and close. Thanks a lot for your help there!

**Comment by IzzySoft** [comment]
@zaednasr our monthly quality check again reported:

```
! build/com.deniscerri.ytdl/metadata/en-US/changelogs/108040004.txt has 1000 chars
! build/com.deniscerri.ytdl/metadata/en-US/changelogs/108050004.txt has 3062 chars
! build/com.deniscerri.ytdl/metadata/en-US/changelogs/108060004.txt has 2249 chars
```

That's up to 6 times the permitted size. I thought we had that tackled?

**Comment by deniscerri** [comment]
Hello izzy. I pushed some changes shortening the changelogs. Thanks for letting me know.

Offtopic, since apps are required to support 16kb libraries, one of my dependencies FFmpeg has been built but increased the size considerably, causing the app to be 30+ mb higher.
I didnt update to the library for my latest release so i could consult with you first.
Current ffmpeg version works as intended so there is no urgency to update it.

**Comment by IzzySoft** [comment]
> I pushed some changes shortening the changelogs. Thanks for letting me know.

Thanks! Please keep within the limit for future ones, too, then 😉 

> causing the app to be 30+ mb higher.

Well, 45 MB is quite a bit beyond the limits indeed. And the usual work-arounds have been all applied already: it's per-ABI builds, and legacy compression is turned on. The big bummers are libffmpeg and libpython, yeah. But what shall I say there? Our size limit versus up-to-date libraries is not an equation that should be made, security-wise. And I'm not a dev, so I cannot tell what switches could be toggled to bring the size down a bit again (like, not including some encoders/decoders with libffmpeg, if that would help).

**Comment by deniscerri** [comment]
I will keep the old ffmpeg as long as i can. Hopefully in the future i could implement downloadable plugins and not include ffmpeg at all in the app, but install it on first boot.

**Comment by IzzySoft** [comment]
That sounds like a good approach, thanks! It would also uncouple FFMPeg from updates to the app itself (so no update to FFMPeg = smaller downloads with an app update). But then, please make sure the download is an action performed with informed consent (i.e. do not download it silently behind our backs, but clearly inform at the first download, also explaining where from the download will come, and that it bypasses additional screening by e.g. our repo), so it does not go against the [IzzyOnDroid App Inclusion Policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion-Policy), quote:

> [the app] must not download additional executable binary files (e.g. addons, auto-updates, etc.) without explicit user consent. Consent means it needs to be opt-in (it must not be harder to decline than to accept or presented in a way users are likely to press accept without reading) and structured in a way that clearly explains to users that they’re choosing to bypass the checks performed in this repo if they activate it.

(same policy, almost to the letter, at F-Droid, btw)

Thanks a lot! 🤗

**Comment by deniscerri** [comment]
@IzzySoft Sorry for the disturbance. Im just letting you know ahead of time.
Due to youtube's new restrictions yt-dlp requires external js library support. 
That has been added to the app through my fork of youtubedl-android since its maintainers havent merged the PR. 
Since im using the fork to include the jslib, i cant mix my fork and theirs for ffmpeg and others so i have to use all of mine, that means the app gets the latest ffmpeg and we hit the filesize problem.

I have to release this version because the app is unusable without it and yt-dlp pushed the external js lib in the stable version. If you won't release this version in your repo i understand, just letting you know.
I still will try to figure out if i can do downloadable plugins for the app but no luck so far.

**Comment by IzzySoft** [comment]
Thanks for letting me know in advance! We can make an exception for this release, and hope the maintainers there merge your PR before the next release.

However, the build for your app failed as well, not clearly telling why:

```
> Task :app:optimizeReleaseResources
> Task :app:packageRelease FAILED
  
FAILURE: Build failed with an exception.
  
* What went wrong:
Execution failed for task ':app:packageRelease'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
```

Do you have any clue? Any changes I should apply to our build recipe? Looking at your Github action didn't give me any idea, nor did the `build.gradle`.

**Comment by deniscerri** [comment]
Yeah my CI failed too at first, a retry got it working

**Comment by IzzySoft** [comment]
It ran here 4 times already, always with the same result.  Last run:

```
> Task :app:optimizeReleaseResources
> Task :app:packageRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable

```

So I'm afraid we'll have to pass it as failed then.

**Comment by deniscerri** [comment]
Alright thats fine, not sure why its failing.

**Comment by IzzySoft** [comment]
Maybe more luck with the next release 🤞 Unfortunately, it just says where it failed, not why…

**Comment by deniscerri** [comment]
@IzzySoft Hello again, can you retry the latest commit? Thanks

**Comment by IzzySoft** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > Java heap space
```

**Comment by deniscerri** [comment]
According to online sources you could try modifying your grade properties and at this line

org.gradle.jvmargs=-Xmx4608m

Increases jvm memory available to gradle

**Comment by IzzySoft** [comment]
Sure, can do. Was a bit in a hurry, so I just triggered a build – what you suggest would require modifying the build recipe as well. But if that option is needed, why not just update your `gradle.properties` accordingly, where it currently reads

```properties
org.gradle.jvmargs=-Xmx1536M -Dkotlin.daemon.jvm.options\="-Xmx2048M" -Dfile.encoding\=UTF-8
```

– which is much to be preferred over doing it in our build recipe, as having it with the app's source it helps everyone who tries to build it, right? 😉

Just to see if that helps, I've temporarily added a step with `sed -r s/Xmx1536M/Xmx4608m/ -i gradle.properties` to the recipe here. Wondering about that value, though: strange number, 4608. I had expected an exponent of 2, e.g. 4096 instead. Ah, I see: 4096+512. Still a bit unexpected 🙈

OK, that builds, thanks! So will you update that in your `gradle.properties` for the next release then?

**Comment by deniscerri** [comment]
From what i know gradle.properties is recommended out of version control that's why i don't include it. I dont know if other android devs do the same. If they include it i will too

**Comment by deniscerri** [comment]
Oh wait lol i already have it 😂.

**Comment by deniscerri** [comment]
Yeah I'll update it

**Comment by deniscerri** [comment]
commited it

**Comment by IzzySoft** [comment]
> From what i know gradle.properties is recommended out of version control

To my knowledge, what you describe _could_ match the gradle wrapper binary (`gradle/wrapper/gradle-wrapper.jar`), but not the properties. The latter are crucial to match builds.

> Oh wait lol i already have it 😂.

Yeah, how else could I have applied the `sed` to it 🤪 

> commited it

Thanks a lot! 🤗 So the next release should build fine then, and hopefully also be RB 🤞
