### ISSUE TITLE
[BUG] Unable to download video from 9gag site

### ISSUE THREAD

**Issue by mrtaxi** [deniscerri/ytdlnis#568]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
Unable to download video from 9gag site 

**To Reproduce**
http://9gag.com/gag/an7j7nB

**Expected behavior**
ERROR: [9gag] an7j7nB: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.9.2
 - Other Device Information: Oneplus 12

**Additional context**

**Comment by zaednasr** [comment]
Please report this to yt-dlp repository.
