### ISSUE TITLE
Explicit songs don't get downloaded from Youtube music album

### ISSUE THREAD

**Issue by Aditya137x** [deniscerri/ytdlnis#569]
**Describe the bug**
When I try to download all the songs from an youtube music album the explicit songs don't show up.

**To Reproduce**
1. Open any youtube music explicit album in browser. [Example](https://music.youtube.com/playlist?list=OLAK5uy_mClbGHSx2e0m4AWxGPEXhMcfEn_GNuc24&si=bF-eGfbRushCbXpn)
2. Share the link from the browser and select YTDLins app from the share menu.
3. Only non explicit songs show up in the list.

**Expected behavior**
All the songs in the album should show up and get downloaded including explicit songs.

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.9.2 (downloaded from Izzy repo)

**Additional context**
If I try to download the explicit song separately it gets downloaded

**Comment by zaednasr** [comment]
Can't reproduce
![image](https://github.com/user-attachments/assets/0d26b6fc-f7da-4805-8bb5-4e632831eeac)
![image](https://github.com/user-attachments/assets/864e5e52-782e-4d6a-b9ed-85f908508e1d)


Do the explicit links need you to be signed in to access them on youtube?
Also what data fetching extractor do you have set for youtube, newpipe or yt-dlp?
Either way both of them for me can get the explicit songs 🤔

**Comment by zaednasr** [comment]
Or do u quick download the playlist and the explicit songs get skipped?

**Comment by Aditya137x** [comment]
No I don't paste the link in the app. I press share button and then select the app from share menu.

![Screenshot_20240908-153204](https://github.com/user-attachments/assets/783725fa-1580-42db-9591-73f0d22c95c1)

I trird pasting the link in serch bar as well still dont see explicit songs.

![Screenshot_20240908-153852](https://github.com/user-attachments/assets/440c6664-c9de-486e-8429-812f1fd0b41f)

I am not signed in on youtube still I can play them in tbe browser

Data fetching extractor: Newpipe

It's a fresh install I have not changed any settings.

**Comment by zaednasr** [comment]
can you switch to yt-dlp and try again pls

**Comment by Aditya137x** [comment]
These are my settings.

![Screenshot_20240908-154607](https://github.com/user-attachments/assets/6f0d2905-cae1-484a-8b9c-296cfe6adbe6)

It's still same. No explicit songs.

**Comment by zaednasr** [comment]
Try this command in the terminal. See if it will list the explicit songs 🤔


`yt-dlp --flat-playlist --print "%(title)s" https://music.youtube.com/playlist?list=OLAK5uy_mClbGHSx2e0m4AWxGPEXhMcfEn_GNuc24&si=bF-eGfbRushCbXpn`

**Comment by Aditya137x** [comment]
Nope.

![Screenshot_20240908-160026](https://github.com/user-attachments/assets/82ea80e0-dcf4-45e1-915c-81ddfe70b196)

**Comment by zaednasr** [comment]
Not really. It might be your yt-dlp acting up. Or even might be a region thing. Terminal doesnt use any app settings. Its raw yt-dlp, apart from the download path and cookies if u try to download something there

My yt-dlp is this for the moment
![image](https://github.com/user-attachments/assets/7e25b765-15f3-4c8b-b1a2-2d4ef16d8e57)

install the master and try again hopefully its resolved

**Comment by Aditya137x** [comment]
Got it. It was an issue caused by my dns. Sorry for the trouble😅
