### ISSUE TITLE
Suggestion + Error

### ISSUE THREAD

**Issue by UserAccount123** [deniscerri/ytdlnis#571]
# Suggestion:
When opening a video (from YouTube for example) .. Add a button in the preview to only playing the audio with the images of the video (Audio only mode).

# Error (in the latest version 1.7.9.2):
This error appears when selecting downloading audio of YouTube video:

![pWX1EjQWxt1LY7UGOzF6NR9BbftDpkC3](https://github.com/user-attachments/assets/31a3a053-42c1-4fec-abe2-e356a1f9b44e)

**Comment by zaednasr** [comment]
For the error
Go to updating settings and update yt-dlp

**Comment by zaednasr** [comment]
@UserAccount123 can you explain the feature request more in depth

**Comment by zaednasr** [comment]
Why tho? The app is not meant to be a player. It's just a preview if you want to download that video or not

**Comment by teddysulaimanGL** [comment]
Let's not do bloat this app any further, shall we?
