### ISSUE TITLE
[BUG] Allow YTDLnis to access files in ...

### ISSUE THREAD

**Issue by alabotski** [deniscerri/ytdlnis#574]
Why do I constantly get this window when I try to change the directory?

[Screenshot_20240920-235653](https://github.com/user-attachments/assets/6dd03e05-99d0-4c93-baaf-254ad3ad8376)
[Screenshot_20240920-234828](https://github.com/user-attachments/assets/5227983c-a058-497f-a89a-76be3982ee1f)

I give all permission 
Version 1.7.9.2

**Comment by zaednasr** [comment]
That's more of an Android thing
