### ISSUE TITLE
[BUG] Mp3 conversion audio

### ISSUE THREAD

**Issue by CobalTitan** [deniscerri/ytdlnis#575]
Describe the bug**
All attempts to download videos in Mp3 format end with a quality of only 32 Kbps, despite having previously selected a higher quality possible.

**Expected behavior**
Have the ability to download videos and convert to Mp3 320kbps quality.

**Screenshots / Video Recording**
![Screenshot_20240922_162825](https://github.com/user-attachments/assets/61cb3272-d7c7-496f-a48e-f2b004c8d0b3)

**(please complete the following information):**
 - Android Version: 10
 - App Version: v1.7.9.2
 - Other Device Information: Samsung Galaxy Note 9

**Comment by zaednasr** [comment]
Please go to download history and send the command of the downloaded item.

**Comment by deniscerri** [comment]
Youtube doesnt provide 320kbps audio, so you are just making the audio worse trying to change it. Leave it as is, it will sound best that way. Just get the OPUS 251 audio format or the M4A 140 format.
If you have youtube music premium and pass cookies to the app u can access high bitrate 256kbps audio with format id 141, just download that raw without conversion.
