### ISSUE TITLE
Minor optional additions to app

### ISSUE THREAD

**Issue by MrBKA95** [deniscerri/ytdlnis#577]
Hello,

I would like to suggest two additions for the app just purely for minor time-saving.

1. Add an additional checkbox in the Sponsorblock section to SELECT/DESELECT all options

2. In the DOWNLOAD QUEUE section when you select the drop down menu top right can you add the option to 'Clear All' in addition to clearing individual menus.

Hopefully you will take these suggestions into consideration.

Thank you.

**Comment by deniscerri** [comment]
Sorry as i didnt even see this issue lol. I added point 2. For point 1 im too lazy to add it, cant you just select them yourself, they are like 7-8 of them 😁
Please wait for the next release

**Comment by MrBKA95** [comment]
> Sorry as i didnt even see this issue lol. I added point 2. For point 1 im too lazy to add it, cant you just select them yourself, they are like 7-8 of them 😁
> Please wait for the next release

Ok fair enough at least your honest. Thanks anyway 😁

**Comment by zaednasr** [comment]
Please check out the latest release [1.8.0](https://github.com/deniscerri/ytdlnis/releases/tag/v1.8.0)
