### ISSUE TITLE
[BUG] python 

### ISSUE THREAD

**Issue by chakri2596** [deniscerri/ytdlnis#578]
Downloading:
Title: The Black Eyed Peas - My Humps
URL: https://www.youtube.com/watch?v=iEe_eraFWWs
Type: video
Command: 
 -N "3" --trim-filenames "184" --no-mtime --sponsorblock-remove "music_offtopic" --extractor-args "youtube:player_client=default,mediaconnect" --sponsorblock-mark "all" --embed-chapters -f "616+251/616+ba/616/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/1" -o "%(uploader).30B - %(title).170B.%(ext)s" --replace-in-metadata "title" ".+" "The Black Eyed Peas - My Humps" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "Black Eyed Peas" --parse-metadata "%(uploader)s:%(artist)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://www.youtube.com/watch?v=iEe_eraFWWs" 

Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
WARNING: Only WebVTT subtitles can be embedded in webm files
ERROR: Postprocessing: file:/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/1/Black Eyed Peas - The Black Eyed Peas - My Humps.en-nP7-2PuUl7o.temp.srt.concat: Math result not representable

**Comment by zaednasr** [comment]
Ignore the python error
The actual error is the one below it
Self explanatory

**Comment by maytham1988** [comment]
You can install it via pip on termux , which is Python's package manager. Here's how you can do it:

1. Ensure pip is installed:

pkg install python-pip


2. Install yt-dlp using pip:

pip install yt-dlp


3. To confirm the installation, check the version:

yt-dlp --version



If you encounter any issues with permissions, you may need to use --user flag:

pip install --user yt-dlp

This should properly install yt-dlp on Termux via pip.

These steps will update Python and yt-dlp to their latest versions in Termux.

NOW Any variant of Python that is installed in Thermox is in fact the same Varigen Sabel used in

**Comment by zaednasr** [comment]
Buddy that's not how python works in this context. Python is compiled and embedded in the app. There is no pip

**Comment by Axyl07** [comment]
As @zaednasr mentioned I think python on the app's backend needs to be updated to version 3.9 as v3.8 is deprecated

**Comment by zaednasr** [comment]
@Axyl07 for how the deprecation won't affect downloading

**Comment by Axyl07** [comment]
@zaednasr I just took a guess, but you are right as even after deprecation that version should work properly.
After looking at the Error log that @chakri2596 provided 
```
WARNING: Only WebVTT subtitles can be embedded in webm files
ERROR: Postprocessing: file:/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/1/Black Eyed Peas - The Black Eyed Peas - My Humps.en-nP7-2PuUl7o.temp.srt.concat: Math result not representable
```
I think the error happened during postprocessing while doing something with the subtitles?
I am not sure what causes this error as I also faced the same on a video that did not even have subtitles.

**Comment by teddysulaimanGL** [comment]
As it says. You're trying to embed SRT subs and choosing the WebM container, and it can't be done. Find the settings to change it in Processing settings

**Comment by chakri2596** [comment]
I just turned off embed subtitles and it downloads just fine

**Comment by Axyl07** [comment]
@chakri2596 that was the actual issue, few days ago I also turned this option and now I've disabled it.
