### ISSUE TITLE
[BUG] Can't Download from TikTok

### ISSUE THREAD

**Issue by i0x404** [deniscerri/ytdlnis#579]
**Error Log:** `Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
ERROR: [vm.tiktok] ZMhrCD3hK: Unable to download webpage: The read operation timed out (caused by TransportError('The read operation timed out'))`

**Describe the bug**
Can't download from TikTok Links

**To Reproduce**
Paste a link and navigate to it.

**(please complete the following information):**
 - Android Version: 11
 - App Version: 1.7.92
 - Other Device Information: Yt-Dlp 30-09-2024

**Comment by zaednasr** [comment]
Please check out the latest release [1.8.0](https://github.com/deniscerri/ytdlnis/releases/tag/v1.8.0)
