### ISSUE TITLE
[BUG]tiktoks ain't downloading 

### ISSUE THREAD

**Issue by Tigger-S** [deniscerri/ytdlnis#583]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed 

It's upto date

**Describe the bug**

Downloading:
Title: #fypシ #avatarthelastairbender #legendofkorra #aang #korra #animegagster 
URL: https://vm.tiktok.com/ZMhkoNTPL/
Type: video
Command: 
 -N "3" --trim-filenames "181" --no-mtime --sponsorblock-remove "music_offtopic" --sponsorblock-mark "all" --embed-chapters --merge-output-format "mp4" --convert-thumbnails "jpg" -S "+hasaud,vext:mp4,aext:m4a" -f "bytevc1_540p_146239-1+ba/bytevc1_540p_146239-1+ba/bytevc1_540p_146239-1/b" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/2496" -o "%(uploader)s - %(title)s.%(ext)s" --replace-in-metadata "title" ".+" "#fypシ #avatarthelastairbender #legendofkorra #aang #korra #animegagster " --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "LRVision7" --parse-metadata "%(uploader)s:%(artist)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --embed-thumbnail "https://vm.tiktok.com/ZMhkoNTPL/" 

Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
ERROR: [vm.tiktok] ZMhkoNTPL: Unable to download webpage: The read operation timed out (caused by TransportError('The read operation timed out'))

**To Reproduce**
Steps to reproduce the behavior: try downloading tiktoks, any tiktok 

**Expected behavior**

Error message 

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 9
 - App Version: latest 
 - Other Device Information: oppo a13

**Additional context**

**Comment by zaednasr** [comment]
Delegate this issue to yt-dlp repository
