### ISSUE TITLE
[BUG]vimeo - download error

### ISSUE THREAD

**Issue by rarspace01** [deniscerri/ytdlnis#584]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
When trying to download a vimeo video, I'm getting:
Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
WARNING: [vimeo] The extractor is attempting impersonation, but no impersonate target is available; if you encounter errors, then see  https://github.com/yt-dlp/yt-dlp#impersonation  for information on installing the required dependencies
ERROR: [vimeo] 681371235: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>)

**To Reproduce**
Download:
https://player.vimeo.com/video/681371235?autoplay=0&title=0&byline=0&wmode=transparent&autopause=0#__youtubedl_smuggle=%7B%22referer%22%3A+%22https%3A%2F%2Fwww.moneytree.consulting%2F5-step-guide%22%7D

**Expected behavior**
No error message, download works

**Screenshots / Video Recording**

**(please complete the following information):**
 - Android Version: 14
 - App Version: 1.7.9.2
 - Other Device Information:

**Additional context**

**Comment by error-reporting** [comment]
separate both into separate issue

**Comment by rarspace01** [comment]
I removed python in the title, this ticket should be a vimeo problem then.

**Comment by error-reporting** [comment]
put Python outdated problem into a separate issue

**Comment by error-reporting** [comment]
lf impersonation is needed the you need a pc with yt-dlp and the required impersonation dependencies

**Comment by rarspace01** [comment]
Okay, so the above mentioned URL can't be downloaded via the app only via yt-dlnp on a pic. Correct?

**Comment by error-reporting** [comment]
any video which requires impersonation can only be downloaded via yt-dlp on pc with the required impersonation dependencies

**Comment by zaednasr** [comment]
@error-reporting python issue isnt a problem. It will eventually be updated as soon as the library does, its not up to the app.

**Comment by error-reporting** [comment]
i managed to download the vimeo video in the link but you need to strip that url down to like this: https://player.vimeo.com/video/681371235?autoplay=0&title=0&byline=0&wmode=transparent&autopause=0
