### ISSUE TITLE
[BUG] ytdlnis do not show mediaconnect format in download card

### ISSUE THREAD

**Issue by error-reporting** [deniscerri/ytdlnis#585]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
the app do not show yt-dlp itag 9x mediaconnect format in download card

**To Reproduce**

**Expected behavior**
the app shows mediaconnect format in download card
**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: 10
 - App Version: 1.7.9.2
 - Other Device Information: hades rom v3.x

**Additional context**
video in this link has the mediaconnect format i was taiking about https://m.youtube.com/watch?v=RQFsDyyxhDA

**Comment by zaednasr** [comment]
Double check if are using yt-dlp formats and not newpipe formats
Also the app includes mediaconnect extractor args
![image](https://github.com/user-attachments/assets/e67d02b2-81ac-4a75-8f28-ea77cdbca374)
So even if that doesnt help, then it is a yt-dlp issue

**Comment by error-reporting** [comment]
it seems to be a random cookie dependent thing
about whether mediaconnect formats appears or not

**Comment by error-reporting** [comment]
mediaconnect extractor args in the app seems to be only active when user-agent header is enabled in ytdlnis cookie settings

**Comment by zaednasr** [comment]
Observe the extra commands button
Media connect always is added. Whether it works with header or not, u have to consult with ytdlp team

**Comment by error-reporting** [comment]
do your app pass mediaconnect extractor args while the app is passing -j --flat-playlist

**Comment by zaednasr** [comment]
Yes. Although thatt wont make a difference because formats are not extracted when fetch8ng playlist
