### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by UserAccount123** [deniscerri/ytdlnis#586]
# Suggestions:
1. Enable inserting links of multiple playlists.
2. Enable auto creating folder for each downloaded playlist.
3. Enable selecting many items from playlist to download.
4. Enable adding incremental numbering to playlist items.
5. Enable to select multiple videos from a channel to download.

**Comment by zaednasr** [comment]
1. in home page, tap search and insert the playlist link and press plus and then do the other ..... and then press search icon
2. u need to configure filename template for that. Go to folder settings u can see the default filename template is uploader - title, u need to add %(playlist)s/ in front to make the items go into playlist folder, u can also do this in the multiple download card if its temporary cuz u cant be downloading playlists all the time

3. Long press a result card in the home screen and then tap the rest, press download button on top
4. same idea

**Comment by zaednasr** [comment]
> > 1. in home page, tap search and insert the playlist link and press plus and then do the other ..... and then press search icon
> > 2. u need to configure filename template for that. Go to folder settings u can see the default filename template is uploader - title, u need to add %(playlist)s/ in front to make the items go into playlist folder, u can also do this in the multiple download card if its temporary cuz u cant be downloading playlists all the time
> > 3. Long press a result card in the home screen and then tap the rest, press download button on top
> > 4. same idea
> 
> And number 5 ??

Sorry, edited my message, i missed it
