### ISSUE TITLE
[BUG] Can't download due to python version error

### ISSUE THREAD

**Issue by introkun** [deniscerri/ytdlnis#589]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
Not able to download yt videos.

**To Reproduce**
Command: 
 -N "3" --trim-filenames "184" --no-mtime --sponsorblock-remove "music_offtopic" --extractor-args "youtube:player_client=default,mediaconnect" --sponsorblock-mark "all" --embed-chapters -f "399+251/399+ba/399/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6" -o "%(uploader).30B - %(title).170B.%(ext)s" --replace-in-metadata "title" ".+" "video name" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "Илья Соболев" --parse-metadata "%(uploader)s:%(artist)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://youtu.be/mXTi4SN8b_8?si=Yl7bFG4UPuE_Xd_J" 

Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
ERROR: [youtube] mXTi4SN8b_8: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

**Expected behavior**
Should be downloaded

**(please complete the following information):**
 - Android Version: 12.0
 - App Version: 2024.10.07
 - Other Device Information: Samsung Tablet

**Additional context**

**Comment by deniscerri** [comment]
This is the actual error

ERROR: [youtube] mXTi4SN8b_8: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

Python is just a warning, it will be removed soon. To get rid of this error, try using cookies

**Comment by introkun** [comment]
Cookies helped, thanks
