### ISSUE TITLE
[FEATURE REQUEST] Update Python to >3.9

### ISSUE THREAD

**Issue by Grub4K** [deniscerri/ytdlnis#590]
**Is your feature request available in yt-dlp? Please describe.**
yt-dlp maintainer here: We plan on removing support for Python 3.8 after the next release

**Describe the solution you'd like**
Preferably the Python version would be updated so that this app wouldn't break. We don't want to move too slowly and run into problems with dependencies dropping 3.8 support before we do.

**Additional context**
- https://github.com/yt-dlp/yt-dlp/issues/10086
- https://github.com/deniscerri/ytdlnis/issues/589

**Comment by zaednasr** [comment]
Yes i am aware and the youtubedl android library recently pushed a beta release with python 11. Will test it and update the app. 👍

**Comment by zaednasr** [comment]
The downside is the drop of support for Android 6

**Comment by zaednasr** [comment]
Please check out the latest release [1.8.0](https://github.com/deniscerri/ytdlnis/releases/tag/v1.8.0)
