### ISSUE TITLE
[Bug] Cannot download from Weverse 

### ISSUE THREAD

**Issue by DoctorDovely** [deniscerri/ytdlnis#594]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

ERROR: [Weverse] 4-180431572: 4-180431572: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)"));

### Expected behavior

Expected the video to just begin downloading as usual, giving me quality choices,etc 

### Steps to reproduce

1. Copy any Weverse Live link 
2. Paste in YTDLnis 
3.click download
4. Get error

### Device information

S10e; Android 

### Screenshots / Recordings

![Screenshot_20241021_014538](https://github.com/user-attachments/assets/90384fc4-9b29-47c8-9790-bb322b668671)

**Comment by zaednasr** [comment]
Report this to yt-dlp

**Comment by bashonly** [comment]
this was fixed in yt-dlp 2024.10.22: https://github.com/yt-dlp/yt-dlp/commit/5310fa87f6cb7f66bf42e2520878952fbf6b1652

**Comment by DoctorDovely** [comment]
Thank you
