### ISSUE TITLE
[Bug] Downloads music videos instead of just the music when given a YT Music playlist

### ISSUE THREAD

**Issue by writeblankspace** [deniscerri/ytdlnis#595]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

I want to download lots of songs with the app. One of those songs which has the issue is Pink Pony Club by Chappell Roan. When I copy its individual song link, I am able to download just the music, which gives me the metadata I need.

However, when I download the whole playlist using its link, Pink Pony Club shows up as "Chappell Roan - Pink Pony Club (Official Music Video) which is not what I want.

### Expected behavior

Downloading a playlist downloads just the music, not the music videos. Basically should have the same effect as downloading the music directly from its individual URL.

### Steps to reproduce

1. Make a YT Music playlist containing songs (not the music videos)
2. Copy its link
3. Download it on YTDLnis

### Device information

Device: Galaxy S23 Ultra SM-S918B/DS
System: Android version 14

### Screenshots / Recordings

Playlist download:
![image](https://github.com/user-attachments/assets/01adeddf-d456-4cc1-8e58-7721b0940a72)

Individual song download (what I want):
![image](https://github.com/user-attachments/assets/ddf62429-c14f-4a99-8bbd-c75221fd3c23)

**Comment by zaednasr** [comment]
Send the link pls

**Comment by writeblankspace** [comment]
Playlist: https://music.youtube.com/playlist?list=PLH8ay7GB4jTr5L3a2xrzPxNkXu4XPbizF&si=hzXwhOeMBDVg_Abc

Song: https://music.youtube.com/watch?v=R_iTpfSCIVk&si=TFHM79rjOYYEFVAL

**Comment by teddysulaimanGL** [comment]
Well, the creator of this playlist does append the MV, that should be expected. Unless it's yours, I suggest you to actually append the audio-only instead

**Comment by writeblankspace** [comment]
Hmm, within YT Music it's an audio-only file; viewing it from YouTube gives me the music video.

Ugh.

**Comment by zaednasr** [comment]
This is more of youtube's internal issues how they present content. Thats how the extractor is getting the information, its not really the app's issue.

**Comment by zaednasr** [comment]
@writeblankspace i suggest you present this issue to yt-dlp developers and see what they could tell you. Let me know
