### ISSUE TITLE
[Feature] Mass re-download

### ISSUE THREAD

**Issue by clairecrichton** [deniscerri/ytdlnis#598]
### Describe the feature

In the downloads menu where all your past downloads are, you should be able to select a large group of them and redownload

### Reason for adding

i download a lot of music and i downloaded a batch of ~5000 songs recently, but i accidently permanently deleted all of them from my computer while trying to download lyrics 😬(dont ask) and i dont want to go through the process of downloading all the albums individually again.

### Additional context

it hopefully wouldnt be too hard to implement as you can already redownload songs one at a time... but i also dont know how any of this stuff works lol

**Comment by zaednasr** [comment]
noted

**Comment by deniscerri** [comment]
Added in [1.8.1](https://github.com/deniscerri/ytdlnis/releases/tag/v1.8.1)
