### ISSUE TITLE
[Bug] Facebook video download error 

### ISSUE THREAD

**Issue by hafizsaadkhb** [deniscerri/ytdlnis#599]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

ERROR: [facebook] 2426067677600828: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Steps to reproduce

?

### Device information

Sony Xperia 5 II

**Comment by zaednasr** [comment]
Report the issue to yt-dlp
[ https://github.com/yt-dlp/yt-dlp/issues?q=]( https://github.com/yt-dlp/yt-dlp/issues?q=)
