### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Rebornjiang** [deniscerri/ytdlnis#600]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

Downloading:
Title: English Conversation 05 | English For Travel and Tourism
URL: https://youtu.be/JYQir4QzIjA?si=8QRUpL1NHg5dH1gK
Type: video
Command: 
 -N "3" --trim-filenames "183" --no-mtime --sponsorblock-remove "music_offtopic" --extractor-args "youtube:player_client=default,mediaconnect" --sponsorblock-mark "all" --embed-chapters -f "616+251/616+ba/616/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/30" -o "%(uploader).30B - %(title).170B.%(ext)s" --replace-in-metadata "title" ".+" "English Conversation 05 | English For Travel and Tourism" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "English Conversation" --parse-metadata "%(uploader)s:%(artist)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://youtu.be/JYQir4QzIjA?si=8QRUpL1NHg5dH1gK" 

WARNING: [youtube] Unable to download webpage: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
WARNING: [youtube] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006). Retrying (1/3)...
WARNING: [youtube] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006). Retrying (2/3)...
WARNING: [youtube] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006). Retrying (3/3)...
WARNING: [youtube] Unable to download API page: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006) (caused by SSLError('[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Unable to download webpage: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
WARNING: [youtube] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006). Retrying (1/3)...
WARNING: [youtube] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006). Retrying (2/3)...
WARNING: [youtube] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006). Retrying (3/3)...
WARNING: [youtube] Unable to download API page: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006) (caused by SSLError('[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006). Retrying (1/3)...
WARNING: [youtube] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006). Retrying (2/3)...
WARNING: [youtube] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006). Retrying (3/3)...
WARNING: [youtube] Unable to download API page: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006) (caused by SSLError('[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] JYQir4QzIjA: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Steps to reproduce

Any video on YouTube cannot be downloaded.

### Device information

Android 14；
Phone：XiaoMi14

**Comment by zaednasr** [comment]
The error told you to report to yt-dlp 4 times. Do that please
