### ISSUE TITLE
[IMPORTANT] Add Pagination in History 

### ISSUE THREAD

**Issue by ZiadEl-kashif** [deniscerri/ytdlnis#605]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

The app crashes when trying to access the Downloads tab and any running downloads enter a sort of suspension as in the download notification is still up yet nothing happens it just hangs and i would have to go into the download queue to manually pause the download and then start it again in order for it to resume.
All other tabs work fine and the app in general is fine as long as i don't go near the Downloads tab 

LOGS
'''
Failed to allocate a 200 byte allocation with 2076976 free bytes and 2028KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.

java.lang.StringFactory.newStringFromChars(StringFactory.java:124)
com.google.gson.stream.JsonReader.nextQuotedValue(Unknown Source:28)
com.google.gson.stream.JsonReader.nextString(Unknown Source:23)
com.google.gson.internal.bind.TypeAdapters$15.read(SourceFile:2)
com.google.gson.internal.bind.TypeAdapters$15.read(SourceFile:1)
com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(Unknown Source:2)
com.google.gson.internal.bind.ArrayTypeAdapter.read(Unknown Source:29)
com.google.gson.Gson.fromJson(SourceFile:4)
com.google.gson.Gson.fromJson(SourceFile:6)
com.google.gson.Gson.fromJson(SourceFile:9)
com.google.gson.Gson.fromJson(SourceFile:10)
com.deniscerri.ytdl.database.Converters.stringToListOfStrings(Unknown Source:13)
com.deniscerri.ytdl.database.dao.HistoryDao_Impl$11.call(SourceFile:2)
com.deniscerri.ytdl.database.dao.HistoryDao_Impl$11.call(SourceFile:1)
androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(SourceFile:83)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
java.lang.Thread.run(Thread.java:1012)
'''

### Expected behavior

For the app not to crash while viewing the list of successful downloads

### Steps to reproduce

1. Open the app
2. Open the Downloads tab 
3. Wait foe 1 to 2 seconds
4. The app crashes in the fashion described above

### Device information

Galaxy S20 Plus 
One UI 5.1
Android 13

**Comment by zaednasr** [comment]
Do you have a large list of downloaded items?

**Comment by ZiadEl-kashif** [comment]
> Do you have a large list of downloaded items?

Yes, I do 
I use the app frequently even though I can't go in there and count. I can say I have a long list.

**Comment by zaednasr** [comment]
For the time being go to general settings and move around the downloads tab. Add download queue in the bottom navigation.
Or go to more tab and access the queue there.

Ill try as soon as i find free time

**Comment by ZiadEl-kashif** [comment]
> Or go to more tab and access the queue there.

I resorted to doing that for the time being. Hopefully, you will come around to this soon. Again, thanks for the quick response

**Comment by deniscerri** [comment]
@ZiadEl-kashif can you reach me in telegram so i can give you a sample apk. I hope it resolves the issue

**Comment by deniscerri** [comment]
Added in [1.8.1](https://github.com/deniscerri/ytdlnis/releases/tag/v1.8.1)
