### ISSUE TITLE
[Bug] data added to comment field is truncated 

### ISSUE THREAD

**Issue by fal628** [deniscerri/ytdlnis#607]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

[https://www.youtube.com/watch?v=lI5w2QwdYik](https://www.youtube.com/watch?v=lI5w2QwdYik)

by default the video url is embedded in the comment field  

but in my music player **Musicolet** and **Windows** the link was truncated,
Windows properties screenshot:
![image](https://github.com/user-attachments/assets/fd486eac-7437-4708-9b48-0406c6d9e24c)

However, with mp3tag I was able to view the full link in the comment field:
mp3tag screenshot:
![image](https://github.com/user-attachments/assets/2a7ce703-38c6-4421-bced-e58000cc1cc3)
 

1. If I saved the file again with mp3tag it fixes the problem, so I think the problem is with how yt-dlp or YTDLnis handle this:

2. In windows If I added `test ` before http and then saved it 
 
![image](https://github.com/user-attachments/assets/ca3ef6f2-b243-4167-a550-7fc0c125bded)

and then open it with mp3tag then it would show this `omment\\test https://www.youtube.com/watch?`
mp3tag screenshot:
![image](https://github.com/user-attachments/assets/cdca98b8-f173-43f6-93d0-e635e75ffe58)

and that to me indicate that the issue is from yt-dlp or YTDLnis

### Another unrelated issue : 

Also there is CC/subtitle for the same video: 
![image](https://github.com/user-attachments/assets/002cc83d-f226-4a85-bb39-7d71a01b4469)

and, I chose to `Embed Subtitles `and `save subtitles `and chose` all` for subtitle languages (check the screenshot below):
![image](https://github.com/user-attachments/assets/7591ba7b-1828-40da-a205-408312519892)

But no .lrc file was downloaded and no subtitle were embedded, check the screenshot from mp3tag
![image](https://github.com/user-attachments/assets/84fd6ce0-a688-487e-b78b-4ad810ac4781)

I also check the extended tags as well. 

### Lastly:

I wonder if I could hire you to write me  a custom yt-dlp command, I am sorry to ask this here, but I don't know how to hire someone to do this, I am willing to pay for your time:

 I need a code to download in mp3 format at highest quality available, and embed the video thumbnail as album art,

and the video title as music title and the channel name as Artist name

And add the following data to the comment field:

1. Video Title
2. Video URL
3. Channel URL
4. Channel name `%(uploader_id)s`
5. Video description
6. Chapters
7. And all available subtitles/captions including the auto generated English caption

**I need it in the following format:**

```
Video Title:
Bo Burnham: Inside - Jeff Bezos

Video URL:
https://www.youtube.com/watch?v=lI5w2QwdYik

Channel URL:
https://www.youtube.com/@darthlordvader.

Uploader Name:
Lord Vader

Video Description:
MASTERPIECE.....

Chapters:
[00.11.87] start to sing

Timed video Subtitles language English: 
[00.11.87]Bezos

video Subtitles language Y: 
[00.11.87]Bezos

video Subtitles language Z: Video Title:
Bo Burnham: Inside - Jeff Bezos

Video URL:
https://www.youtube.com/watch?v=lI5w2QwdYik

Channel URL:
https://www.youtube.com/@darthlordvader.

Uploader Name:
Lord Vader

Video Description:
MASTERPIECE.....
etc.

Chapters:
[00.11.87] start to sing
etc.

Timed video Subtitles language English:
[00.11.87]Bezos
etc.

Timed video Subtitles language English auto-generated : 
[00.11.87]Bezos
etc.

Timed video Subtitles language X: 
[00.11.87]Bezos
etc.

Timed video Subtitles language Y: 
[00.11.87]Bezos
etc.
```

### Expected behavior

given 

### Steps to reproduce

-

### Device information

Samsung A54

**Comment by deniscerri** [comment]
Issue 1
Mention this issue to yt-dlp because the url is added by default by the tool and not YTDLnis
Issue 2
Please send me the url. If you have downloaded the video, go to the downloads section, tap the card, tap the command button in the bottom and send the command to me. Ill try to execute the same download on my end and let you know

**Comment by deniscerri** [comment]
For issue 3, YTDLnis already does them by itself. Just set the container to mp3 for the mp3 thing and you are set.
For the description think you need a command there, you can use as extra command. You can join our telegram group and ask there if anyone can help you out with a command

**Comment by fal628** [comment]
> Issue 1 Mention this issue to yt-dlp because the url is added by default by the tool and not YTDLnis Issue 2 Please send me the url. If you have downloaded the video, go to the downloads section, tap the card, tap the command button in the bottom and send the command to me. Ill try to execute the same download on my end and let you know

https://www.youtube.com/watch?v=lI5w2QwdYik
