### ISSUE TITLE
[Bug] Auto-update not tracking version properly

### ISSUE THREAD

**Issue by Soggytoast111** [deniscerri/ytdlnis#609]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

For the past few weeks, the app had been crashing for me.  When I tried to search for videos I would get a "Python version outdated" error. 

I tried to update in settings but it said I was on the latest build from 2024.11.4.

I just reinstalled from the apk here and it is working now. So for some reason the auto update did not properly update to the current release.

![Screenshot_20241109-085423~2](https://github.com/user-attachments/assets/a0d95be6-5398-4351-8fb1-de099c23b78b)

### Expected behavior

App should have been able to auto update itself properly.  After the recent version release, my app broke and had to be reinstalled. 

### Steps to reproduce

Unsure, app just stopped working one day on its own. 

### Device information

Pixel 6 Pro, Android 14.

**Comment by deniscerri** [comment]
That is the yt-dlp updater, not the app updater. Scroll to the bottom to update the app

**Comment by deniscerri** [comment]
I decided to put the app version on top so people won't get confused

![image](https://github.com/user-attachments/assets/425523e9-6204-414b-badf-b8bc758cf2de)

**Comment by Soggytoast111** [comment]
You're saying the version button at the bottom of that menu?  I did that but it still said I was on the latest version.

**Comment by deniscerri** [comment]
What version you are in?

**Comment by Soggytoast111** [comment]
Now I'm on 1.8.0 because I uninstalled and reinstalled with the latest apk I downloaded here.  But before I was stuck on 1.7.[something].

**Comment by deniscerri** [comment]
Where did you get the apk from? Always get the apk from here github or fdroid

**Comment by teddysulaimanGL** [comment]
Oh, well, then I assume you pressed the Version after reinstall

**Comment by teddysulaimanGL** [comment]
These people that stuck on this version number definitely get the APK from \*that\* site

**Comment by Soggytoast111** [comment]
I don't remember where I originally installed the apk from, but I'm pretty sure it was here because I know it's unsafe to download apks from sites like that.

Sorry I don't have full information about what exactly happened here.  But I just wanted to report that my app became broken and I couldn't auto update.  And I had to come back here, uninstall/reinstall to fix it.

**Comment by teddysulaimanGL** [comment]
Refer to https://github.com/deniscerri/ytdlnis/issues/609#issuecomment-2466232361 again to understand why, because there's not even the problem from the app itself

**Comment by Soggytoast111** [comment]
I'm saying I did scroll to the bottom and press the button though.  I pressed every button but it still said I was on the latest version.  The app is actually supposed to update itself right?

**Comment by deniscerri** [comment]
@Soggytoast111 Not sure why that might have happened, hopefully it wont happen again.
Since you fresh installed you already have checking for update enabled.
That doesnt mean the app will just update by itself on its own. That means that when you enter the app you will get a popup of a new update if there is any

**Comment by deniscerri** [comment]
Or i wonder if the app thought version 1720 was bigger than 1800 and said hey ur in latest version, but i doubt it.

**Comment by teddysulaimanGL** [comment]
The app doesn't update itself. No matter if you manually update or set the app to alert the latest release, it'll show you a confirmation dialog. You might be thinking of yt-dlp update, which absolutely updates itself

**Comment by teddysulaimanGL** [comment]
Like, the app doesn't give you this? What does it say in the first place? Or does it even say anything?

https://github.com/user-attachments/assets/a1664c9d-ff35-47ea-b309-7d795582204f

**Comment by Soggytoast111** [comment]
Correct, that did not happen.  When pressing that button I only got the toast that said "latest version".

**Comment by deniscerri** [comment]
@Soggytoast111 welp, download from the repository on your own then
