### ISSUE TITLE
[Bug] Python Version 

### ISSUE THREAD

**Issue by Julius135** [deniscerri/ytdlnis#610]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

No download work anymore.
In protocol:

ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

### Expected behavior

Download works 

### Steps to reproduce

Enter any YouTube link
Download stops immediately

### Device information

Samsung
Android 12

**Comment by teddysulaimanGL** [comment]
*Outdated app version.* Please update manually with the built-in functionality.
>_More, Settings, Updating, scroll down a bit and find the App section (and not Source), press Version_

This site (`https://ytdlnis.com`) is shady and should never be trusted. I get it, it's the top result, but that doesn't mean it's the official website. So please, let's stick to the official sources
[Updates Telegram channel](buttonurl://t.me/ytdlnisupdates) {user} {protect} {nonotif} {replytag}
