### ISSUE TITLE
[Bug] Preprocessing: ffmpeg not found

### ISSUE THREAD

**Issue by Fynexfif** [deniscerri/ytdlnis#612]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location

### Steps to reproduce

1. Copy youtube link
2. Paste it in the app 
3. Tap on download button 

### Device information

OnePlus 12
Android 15 OxygenOS 15

### Screenshots / Recordings

![IMG_20241110_232554](https://github.com/user-attachments/assets/6c72a6a3-df17-44d3-b02c-8f4e4401eb51)

### Additional context

Downloading:
Title: Follow for more music inspirations ☺️ #michaeljackson #singer #music
URL: https://m.youtube.com/shorts/lrYbkgaW8xI
Type: video
Command: 
 -N "3" --trim-filenames "183" --no-mtime --sponsorblock-remove "music_offtopic" --extractor-args "youtube:player_client=default,mediaconnect;lang=en" --merge-output-format "mp4" --convert-thumbnails "jpg" -S "+hasaud,vext:mp4" -f "399+251/399+ba/399/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/10/Android/data/com.deniscerri.ytdl/files/downloads/1" -o "%(uploader).30B - %(title).170B.%(ext)s" --replace-in-metadata "title" ".+" "Follow for more music inspirations ☺️ #michaeljackson #singer #music" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "Maryna Aksenov" --parse-metadata "%(uploader)s:%(artist)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --embed-thumbnail "https://m.youtube.com/shorts/lrYbkgaW8xI" 

ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged
ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
ERROR: Postprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location

**Comment by deniscerri** [comment]
Ur the same guy from telegram?
If not, he faced this issue from the new oneplus update. Feel free to try the other old versions of the app and they wont work as well. Looks like the update corrupted the file system somehow as he mentioned other apps stopped working aswell. So wait for a new update

**Comment by Fynexfif** [comment]
I don't use telegram, maybe other users of OnePlus are facing same issue. For me, all apps are working fine, it's only the one that use ffmpeg aren't working, that includes Newpipe app and Seal too, basically all youtube downloaders apps, but you maybe right, something is wrong with OnePlus update.

**Comment by Fynexfif** [comment]
Recently I read this Android 15 page size, I think many apps gonna have compatibility issue with Android 15, This is not OnePlus issue but Android 15 issue, I think so.
https://developer.android.google.cn/about/versions/15/behavior-changes-all#16-kb
![Screenshot_2024-11-12-11-43-37-11_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/8b6f4761-36a7-49d1-89c7-e601481ccd32)
