### ISSUE TITLE
Stuck download

### ISSUE THREAD

**Issue by GodLokiGP** [deniscerri/ytdlnis#613]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

My downloads get stuck at this state
![IMG_20241110_232856](https://github.com/user-attachments/assets/87fffe63-b568-48c5-b7b4-7c957cf2a307)
When I go to this destination I see files with no change in their size, after a minute the download notification disappears and download won't finish
After a few minutes when I pause and resume the download, the download immediately finishes and I see two uncompleted files
I can't find any logs

### Expected behavior

Not get stuck, and download normally and completely

### Steps to reproduce

1. Use a long video link from youtube(i.e. 8 hrs)
2. Choose either audio or video to download
3. Use cut feature and cut a portion of your download 
4. After clicking download, check downloads
5. Download is stuck
6. Wait a few minutes
7. Pause then resmue
8. Download immediately finishes with uncompleted files

### Device information

Device: Xiaomi Note 9 pro 5g
Android: 13
Rom: Lineage os

**Comment by deniscerri** [comment]
Download is in fact not stuck, its actually cutting with ffmpeg. Since its 8hrs long it takes a long time to cut, especially if u have enforce keyframes enabled. Since this is a post processor, yt-dlp has finished its job so you trying to pause and resume disrupted the process, so im not surprised it yt-dlp thought it was finished and just gave you the unfinished files instead.

So, just wait leave it alone it will finish.

**Comment by GodLokiGP** [comment]
Alright, I'll update this issue if anything happens

**Comment by GodLokiGP** [comment]
Okay, so I let the app do it's work, it finishes downloading but the downloaded file is incomplete. Like, I cut 2 hours from 8 hours, but the file is 2 minutes at most. And enforce keyframes is disabled.

**Comment by deniscerri** [comment]
in the downloaded card, tap it and then find the command button and send it to me. ill test it out

**Comment by GodLokiGP** [comment]
`-N "3" --trim-filenames "184" --no-mtime --sponsorblock-remove "music_offtopic" --download-sections "*4:17:30-5:55:00" --extractor-args "youtube:player_client=default,mediaconnect;lang=en" -f "139/ba/b" -x -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/3" -S "hasaud,size" -o "%(autonumber)d. %(section_title&{} |)s %(uploader).30B - %(title).170B [%(section_start>%H∶%M∶%S)s].%(ext)s" --replace-in-metadata "title" ".+" "جرجندی ۲" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "جرجندی ۲" --parse-metadata "%(uploader)s:%(artist)s" --parse-metadata "%(uploader,artist,channel,creator|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --embed-metadata --parse-metadata "%(playlist_uploader,artist|)s:^(?P<first_artist>.*?)(?:(?=,\s+)|$)" --parse-metadata "description:(?:Released on: )(?P<dscrptn_year>\d{4})" --parse-metadata "%(dscrptn_year,release_year,release_date>%Y,upload_date>%Y)s:(?P<meta_date>\d+)" --parse-metadata "%(album_artist,first_artist|)s:%(album_artist)s" --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1" "https://www.youtube.com/live/vENX0wvnTyI"`

**Comment by deniscerri** [comment]
Its taking long, ill get back at you tomorrow

**Comment by GodLokiGP** [comment]
Thanks

**Comment by deniscerri** [comment]
I tried two times and it downloaded fine. The final file is a m4a audio with 01:37:30 in length

**Comment by deniscerri** [comment]
my current yt-dlp version is 2024.08.26.232811.
Check what do you have and update if you have to.

**Comment by GodLokiGP** [comment]
I checked, it says 2024.11.04

**Comment by deniscerri** [comment]
try nightly or master yt-dlp version

**Comment by GodLokiGP** [comment]
I tried both, but the problem persists.

**Comment by deniscerri** [comment]
i dont know what to say, turn on keyframes i guess

**Comment by GodLokiGP** [comment]
Keyframes didn't help. 
I tampered with some settings and the downloaded file is now about 8 minutes long instead of 1:30.
I turned off fragment downloads, turned on quick download.

**Comment by deniscerri** [comment]
quick download is irrelevant in this case.
What if you try to change the timespan a little?

**Comment by GodLokiGP** [comment]
It doesn't have any impact on it. 

Now the file length is random. Last try gave 28 seconds.

**Comment by deniscerri** [comment]
I guess, you have to take this to yt-dlp and make an issue there, hopefully they will help you. Since we are dealing with yt-dlp processes and not really app's usage.

**Comment by GodLokiGP** [comment]
Alright. Thank you for your attention.🔥
