### ISSUE TITLE
[Bug] Error Unable to download video links from text file

### ISSUE THREAD

**Issue by Turkialh14** [deniscerri/ytdlnis#616]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

This was previously a feature request and was implemented but now after several updates it no longer works so I am marking it as a bug not a feature request.

### Steps to reproduce

The text file is shared with the program but it only gets the first link.

### Device information

Galaxy A54 5G
Android:14

**Comment by zaednasr** [comment]
Do you know which version broke it?

**Comment by Turkialh14** [comment]
Previously, you could download a playlist of 4000 videos without it logging you out of the app due to the large number of videos. As I mentioned in the channel download problem, when you download only 3 videos, it seems that in the log there are about 6 or 5 being downloaded. I know the reason for your request from me in any update that no longer works because you can track the solution to the problem, but unfortunately I do not know and I will try to help you as much as possible in anything else

**Comment by zaednasr** [comment]
Dm me on telegram with all the issues u have. Ill sort them out

**Comment by Turkialh14** [comment]
Ok thank you very much

**Comment by zaednasr** [comment]
I have found the issue. Easy fix

**Comment by Turkialh14** [comment]
Thanks, so I think this will partially solve the issue #615 for YouTube channel where I can write a python code that extracts the url of the videos from the channels and puts them in a text file where the program will not treat the text file as a playlist and load the first two videos

**Comment by deniscerri** [comment]
Fixed in [1.8.1](https://github.com/deniscerri/ytdlnis/releases/tag/v1.8.1)
