### ISSUE TITLE
[Bug] Selecting video format requires 2 taps

### ISSUE THREAD

**Issue by jroovy** [deniscerri/ytdlnis#617]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

Selecting a video format requires 2 taps for some reason.
However, when selecting an audio format, it only requires 1 tap.

### Expected behavior

Selecting video format only requires 1 tap, like when selecting the audio format.

### Steps to reproduce

1. Paste a url
2. Select a video format to download

### Device information

Device: Motorola G5s Plus
System: Android 11 (crdroid)
App version: 1.8.0

### Screenshots / Recordings

https://github.com/user-attachments/assets/9a657158-8c78-41e7-81ce-57ac0949ec3c

**Comment by teddysulaimanGL** [comment]
For the video download type, that's by design. Because if you scroll down quite a bit, the app lets you select multiple audio streams, which is useful for multiple language dubs

**Comment by jroovy** [comment]
> For the video download type, that's by design. Because if you scroll down quite a bit, the app lets you select multiple audio streams, which is useful for multiple language dubs

I see...
I didn't realize there was audio down there in the video section :sweat_smile: 
Thanks for the explanation. I'll close the bug report now.
