### ISSUE TITLE
[Feature] For each application setting, display their current value

### ISSUE THREAD

**Issue by Korb** [deniscerri/ytdlnis#618]
### Describe the feature

In YTDLnis 1.8.0 (f-droid) some settings display the current value, but some do not (and to view the current value of a setting, you must enter the mode for selecting its value).

For example, the following settings in the general list currently **do not display their values**:

- Preferred Download Type (default tab the download card will open to)
- Limit Rate (maximum download rate (in bytes per second), e.g. 50K or 4.2M)
- Buffer Size (size of download buffer, e.g. 1024 or 16K (default is 1024))
- Socket Timeout (time to wait before giving up, in seconds)

Perhaps it would be enough for settings that require a description to have a round question mark icon with a tooltip. Or to move the setting description to the value selection screen. In any case, this is not a text that needs to be reread many times.

### Reason for adding

This violates the unified logic and complicates checking the correctness of the settings.

**Comment by zaednasr** [comment]
Noted
