### ISSUE TITLE
Stop the video download process.

### ISSUE THREAD

**Issue by Qaz-7** [deniscerri/ytdlnis#63]
Pause and resume the download process while downloading a video.Also option to stop all when downloading multiple videos.This is not supported in yt-dlp. But it would be great if it could be done on Android

**Comment by deniscerri** [comment]
U can stop a downloading video in the download queue screen and it will move to the cancelled tab. U can redownload it there. In the top menu u can cancel all downloads.

**Comment by soymadip** [comment]
> This cancels the download, not stops it.

Join discord bro, it's easier to communicate there

**Comment by soymadip** [comment]
> This cancels the download, not stops it.

It does cancel but the cache remains.

**Comment by soymadip** [comment]
So next time if you re start it from cancelled tab, it will start download form the point it was cancelled before

**Comment by deniscerri** [comment]
Why? Its convenient. Just dont clear cache from the settings and it will continue where you left it off

**Comment by soymadip** [comment]
> > So next time if you re start it from cancelled tab, it will start download form the point it was cancelled before
> 
> This is annoying.

So take this like this:- 

This should be a yt-dlp feature, go and open issue in their repo.

@deniscerri am i correct? 

If I am please close this issue

**Comment by deniscerri** [comment]
> I didn't clear the cache. It started again.

wdym it started again?
