### ISSUE TITLE
[Bug] Format selection menu doesn't show all formats

### ISSUE THREAD

**Issue by bibsp** [deniscerri/ytdlnis#631]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

As mentioned, it doesn't list all the formats.
![Screenshot_2024-11-22-17-31-04-555_com deniscerri ytdl](https://github.com/user-attachments/assets/58952008-146a-44a0-b61d-3bc288c33a15)

Additionally is doesn't show resolution.
Doesn't show which is video only, which is video audio combined. These informations are very important to know which one to download. Please fix it.

### Expected behavior

It should list all these formats.
![Screenshot_2024-11-22-17-32-03-510_com deniscerri ytdl](https://github.com/user-attachments/assets/1e0b5b2d-8faf-4dbf-b744-f61012fef56c)

### Steps to reproduce

Test URL: https://www.facebook.com/share/v/1D7f8ZZ4b6/

You can clearly see **sd** and **hd** is missing in this list.
Resolution info is missing.
It doesn't show which is video only and which is video audio combined.
Please update this...

### Device information

Redmi Note 7S
Android 10

### Screenshots / Recordings

Already provided.

### Additional context

Nothing.

**Comment by deniscerri** [comment]
Added resolution in the format label in ver [1.8.1](https://github.com/deniscerri/ytdlnis/releases/tag/v1.8.1)
