### ISSUE TITLE
[Feature] Bring back support for Android 6.0 (Marshmallow)

### ISSUE THREAD

**Issue by highbaser** [deniscerri/ytdlnis#632]
### Describe the feature

Please bring back support for Android 6.0 (Marshmallow)

### Reason for adding

Android 6.0 is still in use by tens of millions of people from all over the world. According to [StatCounter](https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide) the market share is 2.74% (2024 October) which translates to **90 million** devices.

Unfortunately, smartphones don't have official Android major version updates after their software support is cut. While old PC users can install a fully operational Linux desktop with a few clicks and also have some yt-dlp frontend on it, it's much harder for an Android 6.0 user to have a full-featured and properly working alternative (LineageOS, postmarketOS, etc.) that supports all functions of the device (calls, GPS, mobile network, WiFi, bluetooth, sensors, etc.) mostly operated by compartments of proprietary fimrware, never released to FOSS communities. Moreover, manufacturers make it even harder to upgrade to an open-source firmware (e.g. Samsung's Knox hardware fuse that "blows" upon unlocking the bootloader).

The older a device gets, the more it needs alternative software like YTDLnis. Official apps become incompatible, unstable, bloated, deprecated on older OSes, so a user on Android 6.0 would prefer YTDLnis to installing TikTok, Youtube, Facebook, etc. apps if they can download videos from there and play it even with a native player, fast and smooth.

**Comment by deniscerri** [comment]
I didnt want to remove support for android 6, but yt-dlp doesnt work anymore on android 6. Go and try the previous version of the app, its not usable anymore because it uses python 3.8. yt-dlp dropped support for 3.8. Android 6 only supports up to python 3.8.
So either i had to drop android 6 or the app becomes unusable for everyone. If it wasnt for this i wouldnt have dropped android 6. I hope you understand

**Comment by highbaser** [comment]
@deniscerri Tried it and have run into https://github.com/deniscerri/ytdlnis/issues/611. It may work for those who have it already installed, have an older release of yt-dlp downloaded and disabled updates. However, all new installs are broken. I created a feature request to cover this one: https://github.com/deniscerri/ytdlnis/issues/633
