### ISSUE TITLE
[Feature] Release a 1.7.9.3 with yt-dlp version compatible with Python 3.8

### ISSUE THREAD

**Issue by highbaser** [deniscerri/ytdlnis#633]
### Describe the feature

Please release a 1.7.9.3 version that still supports Android 6.0 and which would download the last yt-dlp version compatible with Python 3.8.

### Reason for adding

New installs on Android 6.0 are **completely broken** as YTDLnis 1.7.9.2 (last version for Android 6.0) tends to download a too recent version of yt-dlp that has already deprecated Python 3.8. This means that **all new installations before 1.8.0 become unusable** because the Settings menu doesn't allow downloading a fixed version of yt-dlp, only stable/master/nightly channels.

There are already bug reports about this, see https://github.com/deniscerri/ytdlnis/issues/611

The last yt-dlp that supports Python 3.8 seems to be [2024.10.22](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.10.22). This should be fixed into a new release (1.7.9.3) so it remains usable for a while, especially for sites that don't change a lot.

**Comment by seproDev** [comment]
Here is a possible workaround:
- Download the [1.7.9.2 APK](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.9.2)
- Turn off internet on your phone
- Install the APK
- Launch ytdlnis and disable auto-updates for yt-dlp (Settings > Updating > Auto-Update yt-dlp)
- Turn internet back on
- Go to the built-in terminal in ytdlnis and run `yt-dlp -U`. This will use yt-dlp's built in updater and not the one from youtubedl-android. yt-dlp uses a lock file format to prevent updating past an incompatible python version.

Now you should have ytdlnis v1.7.9.2 with yt-dlp 2024.10.22 installed

Long term youtubedl-android should probably be updated to either just use the built in yt-dlp updater or support the lock file format yt-dlp uses.

**Comment by deniscerri** [comment]
```
yt-dlp --update-to stable@2024.10.22
```
this worked

**Comment by seproDev** [comment]
Yes, yt-dlp uses the `_update_spec` file from releases to determine the last compatible version.

**Comment by deniscerri** [comment]
Ill close this issue and make a new one and pin it for easy access

**Comment by deniscerri** [comment]
@seproDev i dont understand why they use custom url sources for updating yt-dlp instead of the built in updater. At least they shouldve made the sources public so i could implement a source editor for users. People could have their own modded yt-dlp repo and update it from the app. Oh well...
Gotta make this an issue

**Comment by deniscerri** [comment]
Now that i think about it
I can just run the command myself
yt-dlp --update-to nightly@latest
yt-dlp --update-to master@latest
yt-dlp --update-to nicolaasjan/yt-dlp@latest

definitely noting this for the next feature

**Comment by seproDev** [comment]
I looked at the custom updater logic briefly, I think it already existed before the yt-dlp updater existed and was originally built for youtube-dl.

The `nicolaasjan` repo is only applicable for Windows. It works by using a modded Python 3.12 runtime that was compiled for Windows XP/7. Since ytdlnis uses the zipimport library, this doesn't help with the Python compatibility issue. Being able to update to custom branches could still be useful to test out PRs or other experimental features.

Running `yt-dlp --update-to stable@latest` with Python 3.8 would result in an error message, since you can't update to 2024.11.18.
Running `yt-dlp --update-to stable` should work. Or you just run `yt-dlp -U` to update to the latest compatible version of your current branch.

**Comment by deniscerri** [comment]
yeah i just used it as an example ofc.

**Comment by bashonly** [comment]
Maybe this will help to clarify something:

`CHANNEL@latest` is typically used to force switching channels even if latest version on `CHANNEL` is older than the current version of the binary

e.g. if you're on `nightly@2024.11.24.123456` and you want to downgrade to `stable`: using `--update-to stable` won't work, because the latest stable `2024.11.18` is older than `2024.11.24.123456`. But you don't want to have to manually type in a version number, so you can specify the tag `--update-to stable@latest`, and force the channel switch/downgrade to stable

**Comment by deniscerri** [comment]
I guess in the app's usecase @latest needs to be used always. Because otherwise i cant downgrade to stable from nightly

**Comment by bashonly** [comment]
Yeah. The downside is, by specifying any `@TAG` you are bypassing any potential version recommendation per the lockfile, and the update will fail if the lockfile's requirements are not met

**Comment by highbaser** [comment]
The workaround suggested by @seproDev doesn't work on Android 6.0, at least on armeabi-v7. yt-dlp won't even launch.
```~ $ yt-dlp 
Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 18, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/aes.py", line 5, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/__init__.py", line 69, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/Cryptodome.py", line 17, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/__init__.py", line 28, in <module>
    from Cryptodome.Cipher._mode_cbc import _create_cbc_cipher
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 45, in <module>
    raw_cbc_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_cbc", """
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_cbc': Not found '_raw_cbc.cpython-38.so', Cannot load '_raw_cbc.abi3.so': dlopen failed: cannot locate symbol "__aeabi_memcpy4" referenced by "/data/data/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_raw_cbc.abi3.so"..., Not found '_raw_cbc.so'```
There should be at least a **working** copy of yt-dlp to be able to update itself but there isn't any.

@deniscerri Why can't you just release an 1.7.9.3 which has the latest working yt-dlp bundled in or can download stable@2024.10.22? Would be much more simple for everyone.

**Comment by error-reporting** [comment]
> The workaround suggested by [@seproDev](https://github.com/seproDev) doesn't work on Android 6.0, at least on armeabi-v7. yt-dlp won't even launch after the fresh install of YTDLnis.
> 
> ```
> Traceback (most recent call last):
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 18, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/aes.py", line 5, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/__init__.py", line 69, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/Cryptodome.py", line 17, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/__init__.py", line 28, in <module>
>     from Cryptodome.Cipher._mode_cbc import _create_cbc_cipher
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 45, in <module>
>     raw_cbc_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_cbc", """
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
>     raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
> OSError: Cannot load native module 'Cryptodome.Cipher._raw_cbc': Not found '_raw_cbc.cpython-38.so', Cannot load '_raw_cbc.abi3.so': dlopen failed: cannot locate symbol "__aeabi_memcpy4" referenced by "/data/data/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_raw_cbc.abi3.so"..., Not found '_raw_cbc.so'```
> ```
> 
> There should be at least a **working** copy of yt-dlp to be able to update itself but there isn't any.
> 
> [@deniscerri](https://github.com/deniscerri) Why can't you just release an 1.7.9.3 which has the last Python38-compatible and working yt-dlp bundled in or can download stable@2024.10.22? Would be much more simple for everyone.

i think your proposed 1.7.9.3 would have to omit cryptodome
