### ISSUE TITLE
[Bug] Issue in Downloads tab

### ISSUE THREAD

**Issue by Turkialh14** [deniscerri/ytdlnis#636]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

I have the same problem with issue number #605 But in addition to that I can't pause the download, There is a screen recording that I will attach with the video names blurred for privacy reasons.

https://github.com/user-attachments/assets/01c8ffbe-fc31-41a1-b65a-c5c6de213c2d

There is also a problem that I think was mentioned when I download a large channel such as 900 videos and above, the application crashes as shown in the screenshot and the output, Previously, I could handle 6,000+ videos seamlessly by downloading multiple large playlists without having to worry about crushing the app. The reason I mentioned this is that they are interconnected problems.

![Screenshot_٢٠٢٤١١٢٣_١٠٥٠٤١](https://github.com/user-attachments/assets/c6fdb399-6763-4ab8-ba39-ef4d70b27184)

Note: the number of videos in the queue does not matter. I have tried it with channels that contain less than 100 videos and channels that contain more than 2000 videos.

### Steps to reproduce

.

### Device information

.

### Additional context

crash log:

Data cannot occupy more than 10240 bytes when serialized

androidx.work.Data.toByteArrayInternal(SourceFile:103)
com.deniscerri.ytdl.database.repository.DownloadRepository.startDownloadWorker-0E7RQCE(SourceFile:357)
com.deniscerri.ytdl.database.repository.DownloadRepository.startDownloadWorker-0E7RQCE$default(Unknown Source:5)
com.deniscerri.ytdl.database.viewmodel.DownloadViewModel.queueDownloads(SourceFile:33)
com.deniscerri.ytdl.database.viewmodel.DownloadViewModel$queueDownloads$1.invokeSuspend(Unknown Source:13)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
androidx.work.Worker$2.run(SourceFile:37)
kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)

**Comment by deniscerri** [comment]
@Turkialh14 i believe the crash log is when you try to re-queue the paused items
or even trying to queue them in the beginning?
Dont worry mate, i have resolved this

**Comment by Turkialh14** [comment]
Thanks and there is another small problem when the video starts downloading and when I pause it and then exit the application and return to it and then make it start downloading again from where it stopped, it restarts the download completely and creates a new download record for the video but in the same temporary folder where it was downloaded from the beginning, but it does not restart the download but starts from where it stopped because of the previous temporary files that were in it

**Comment by Turkialh14** [comment]
I will send the problem and video to @zaednasr because of the video size

**Comment by deniscerri** [comment]
> > @Turkialh14 i believe the crash log is when you try to re-queue the paused items or even trying to queue them in the beginning? Dont worry mate, i have resolved this
> 
> Thanks and there is another small problem when the video starts downloading and when I pause it and then exit the application and return to it and then make it start downloading again from where it stopped, it restarts the download completely and creates a new download record for the video but in the same temporary folder where it was downloaded from the beginning, but it does not restart the download but starts from where it stopped because of the previous temporary files that were in it

This isnt really a new download item. What is happening is the paused download item that is in the active page temporarily is moved to the queued list. Then the download worker starts running and grabs the queued items constantly until the list is depleted.

Can you expand on this, if im wrong?

**Comment by Turkialh14** [comment]
I agree with you but there are two problems, the first is that it creates another record, although it is not a big problem, and the second is that it starts uploading some information again and may cause me to be banned by YouTube

**Comment by deniscerri** [comment]
Its just a log record, i dont think thats a big deal. Also i think its fine to have separate logs for each download run. Its clearer.
Also for the 2nd thing, all the phone is doing is running the yt-dlp command. So it will do the exact same command again if you resume it. But since its referencing the same folder with temporary files in it, it resumes where you left off.

**Comment by Turkialh14** [comment]
You are the expert, I will not argue with you because I do not know programming. But as you know, I see in the output log repeating the same load command.

[youtube] gd7BXuUQ91w: Downloading webpage
[youtube] gd7BXuUQ91w: Downloading ios player API JSON
[youtube] gd7BXuUQ91w: Downloading mweb player API JSON
[youtube] gd7BXuUQ91w: Downloading mediaconnect player API JSON
[youtube] gd7BXuUQ91w: Downloading android player API JSON
[youtube] gd7BXuUQ91w: Downloading player 89dfc5b3
[youtube] gd7BXuUQ91w: Downloading m3u8 information


https://github.com/user-attachments/assets/5c7f7b3b-cb0f-4c86-86be-81296d73c38f

**Comment by deniscerri** [comment]
Yes, unfortunately there is nothing you can do about that. That's how yt-dlp works. Unless there is a way to store this information and rush off to the download and fetch the data stored somewhere in the filesystem, but i am not aware of it or even think yt-dlp can even do such a thing.

Maybe you should make an issue to them and hopefully they have a solution ,or will code one in. Let me know

**Comment by Turkialh14** [comment]
I'm sure it will excite them.

**Comment by deniscerri** [comment]
@Turkialh14 actually i found out how to do this. there was a command called --write-info-json to load data in a file and then reference it later.
Its awesome, the downloads start immediately now.

The new release will include this in its advanced settings section as a toggle.

**Comment by Turkialh14** [comment]
Good idea, will the json file be among the temporary files that can be deleted in the settings in the folders tab in the last option?

**Comment by deniscerri** [comment]
Yes the json file will be stored in the same place as the other temp files in the download process. 
But if you have turned caching off, those temporary files cannot be deleted for obvious reasons, the app cant know where they are at.

**Comment by Turkialh14** [comment]
What do you think of making it a default argument that is added automatically? It will be better for download management. Instead, add an option to cancel it and write in parentheses that it is not recommended. Advanced people will understand the matter, but for those who do not have programming experience, it will be better for them and they can at any time clear the temporary files and re-download if a problem occurs.

**Comment by deniscerri** [comment]
@Turkialh14 Yeah thats a good thought. Ill consider the use cases

**Comment by deniscerri** [comment]
I coded it be available for the next 5 hours. Considering formats tend to expire on some extractors, i dont want the download to be unusable. This is a rare use case, one of them being you starting a download, it saves the info json and you cancel it and you remember to start it again, maybe tomorrow lol. Formats most likely expired, download item is useless. So in that case it will redownload the the webpage and player clients again, and it will save a new info file aswell no problem

**Comment by Turkialh14** [comment]
There is a problem with the argument, I saw that it was closed without being resolved.

https://github.com/yt-dlp/yt-dlp/issues/6594

**Comment by Turkialh14** [comment]
But I don't think it's really a big problem because the app automatically adds the argument` -o`

**Comment by Turkialh14** [comment]
You are right because you will treat them as temporary files.
