### ISSUE TITLE
[not technically a bug] How can i change the codec to stay on H264 only

### ISSUE THREAD

**Issue by freakingdan** [deniscerri/ytdlnis#644]
### ⠀

- [x] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

when i change the prefered codec to avc h264 and download something in example instagram and when i try to play it, it doesn't change to the codec i want..

### Expected behavior

its just changed the codec to vp9 which isn't the codec i want

### Steps to reproduce

# 1
https://github.com/user-attachments/assets/f854e22c-d8bf-4890-9c70-1f821c8b1849

# 2
https://github.com/user-attachments/assets/770b1716-e12c-44bb-83b4-66387b5e5bc7

# 3
https://github.com/user-attachments/assets/33de3eee-b52f-4d2b-bc4c-7f28f71767b9

### Device information

Device: realme rmx3231
System: Android 11 Go

**Comment by teddysulaimanGL** [comment]
Okay, after looking at the format list, Instagram doesn't provide the AVC formats. Therefore, most likely the case is the same as yours. My suggestion would be to check the "Recode Video" chip, maybe only when downloading from Instagram, 'cause it takes some time to finish, just like how you usually convert any files

**Comment by freakingdan** [comment]
maybe i try that...
i will edit this comment as soon as i finish this and check if theres some codec change

**Comment by freakingdan** [comment]
> nope it doesn't work...
> maybe there's a problem on my end and doesn't change the codec
> tried to download another video on instagram and the codec stays the same ;(

and yeah it only happened on instagram not other platforms...

**Comment by teddysulaimanGL** [comment]
> [4. Wrong configuration and/or other reasons
   You need to enable Log Downloads (𝘔𝘰𝘳𝘦 ➔ 𝘚𝘦𝘵𝘵𝘪𝘯𝘨𝘴 ➔ 𝘋𝘰𝘸𝘯𝘭𝘰𝘢𝘥𝘴 ➔ 𝘓𝘰𝘨 𝘋𝘰𝘸𝘯𝘭𝘰𝘢𝘥𝘴), then try downloading again
   If you already enabled it (and downloaded the item), go to More ➔ Logs, then find your failed download log, press "Copy log" button, then send it to the group. We'll figure out what could be wrong with your configuration and fix it if there's actually something wrong with it](https://t.me/ytdlnis)

Send me the full log, please

**Comment by freakingdan** [comment]
> ok wait...
i will edit this again later

**Comment by freakingdan** [comment]
> tried to download another video and maybe you can see it here
> 
> Full log
> 
> ```
> Downloading:
> Title: 
> URL: https://www.instagram.com/reel/DAy2ZvqhqvD/?igsh=bGUzNnBqc3A2czc3
> Type: video
> Command: 
>  --downloader "libaria2c.so" --external-downloader-args "aria2c:"--summary-interval=1" " -N "15" --retries "10" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --no-part --trim-filenames "184" --no-mtime --audio-quality "0" --write-info-json --no-clean-info-json -o "infojson:/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/33bf18ca36f4932703c3658760f48f77" -o "%(title).200B.%(ext)s" --embed-chapters --recode-video "mp4" --convert-thumbnails "jpg" -S "+hasaud,res:1080,vcodec:h264,vext:mp4,aext:mp3" -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6" --parse-metadata "%(uploader,channel,creator|null)l:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --embed-thumbnail "https://www.instagram.com/reel/DAy2ZvqhqvD/?igsh=bGUzNnBqc3A2czc3" 
> 
> 
> [Instagram] Extracting URL: https://www.instagram.com/reel/DAy2ZvqhqvD/?igsh=bGUzNnBqc3A2czc3
> [Instagram] DAy2ZvqhqvD: Downloading video info
> [MetadataParser] Parsed uploader from '%(uploader,channel,creator|null)l': 'nzeeeeeeeeeeee ☠️'
> [info] DAy2ZvqhqvD: Downloading 1 format(s): dash-1582708339123154v+dash-876421157503002ad
> [info] There are no subtitles for the requested languages
> [info] Downloading video thumbnail 1 ...
> [info] Writing video thumbnail 1 to: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6/Video by nzee_meme.jpg
> [info] Writing video metadata as JSON to: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/33bf18ca36f4932703c3658760f48f77.info.json
> [SubtitlesConvertor] There aren't any subtitles to convert
> [ThumbnailsConvertor] Not converting thumbnail "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6/Video by nzee_meme.jpg"; already is in target format jpg
> [download] Destination: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6/Video by nzee_meme.fdash-1582708339123154v.mp4
> [#f85400 512KiB/2.1MiB(23%) CN:3 DL:1.1MiB ETA:1s]
> [#f85400 1.6MiB/2.1MiB(79%) CN:1 DL:1.1MiB]
> [#f85400 2.0MiB/2.1MiB(94%) CN:1 DL:851KiB]
> 
> [download] 100% of    2.14MiB in 00:00:03 at 656.57KiB/s
> [download] Destination: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6/Video by nzee_meme.fdash-876421157503002ad.m4a
> 
> [download] 100% of  110.05KiB in 00:00:01 at 77.67KiB/s
> [Merger] Merging formats into "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6/Video by nzee_meme.mp4"
> Deleting original file /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6/Video by nzee_meme.fdash-876421157503002ad.m4a (pass -k to keep)
> Deleting original file /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6/Video by nzee_meme.fdash-1582708339123154v.mp4 (pass -k to keep)
> [VideoConvertor] Not converting media file "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6/Video by nzee_meme.mp4"; already is in target format mp4
> [EmbedSubtitle] There aren't any subtitles to embed
> [Metadata] There isn't any metadata to add
> [EmbedThumbnail] mutagen: Adding thumbnail to "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/6/Video by nzee_meme.mp4"
> 
> ```
it stays on vp9 ;(

**Comment by teddysulaimanGL** [comment]
I understand now. Because the format is already MP4, it skips the recode process in the first place. But you can try this workaround for now.

> ["--use-postprocessor FFmpegCopyStream --ppa CopyStream:"-c:v libx264 -c:a aac -f mp4" recodes to h264+aac in mp4"](https://github.com/yt-dlp/yt-dlp/issues/7607#issuecomment-1636960750)

Use these command-lines as the Extra Command, the chip may be visible and accessible if you scroll the download card down a bit (you can add them in the Command Template so you can quickly append it in the future). We'll make sure to note this down and fix it later. Sorry for the inconvenience

**Comment by freakingdan** [comment]
> its okay i will try it when i found another video to test it out
> thanks ;)

heyyy its working now... the workaround works
thanks again

PS: hope it fixes this problem now

**Comment by freakingdan** [comment]
> heyyy its working now... the workaround works

after i update to 1.8.1.1 and installed the latest nightly version of yt-dlp... The workaround doesn't work anymore.. it says in the log:

```
Downloading:
Title: 
URL: https://www.instagram.com/reel/C9AEPU2pDOs/?igsh=MWlwYXplajZzdGZ2
Type: video
Command: 
 --downloader "libaria2c.so" --external-downloader-args "aria2c:"--summary-interval=1" " -N "10" --retries "10" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --no-part --trim-filenames "183" --no-mtime --audio-quality "0" --embed-chapters --merge-output-format "mp4" --convert-thumbnails "jpg" -S "+hasaud,res:1080,vcodec:h264,acodec:aac,vext:mp4,aext:mp3" -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/47" -o "%(title).200B.%(ext)s" --print-to-file "video:%()#j" "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/3c8beed358853f952109bbfff34374ab.info.json" --parse-metadata "%(uploader,channel,creator|null)l:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --embed-thumbnail --use-postprocessor "FFmpegCopyStream" --ppa "CopyStream:"-c:v" "libx264" -c:a "aac" -f "mp4" " "https://www.instagram.com/reel/C9AEPU2pDOs/?igsh=MWlwYXplajZzdGZ2" 

Usage: yt-dlp [OPTIONS] URL [URL...]
yt-dlp: error: wrong --ppa formatting; No closing quotation
```

**Comment by zaednasr** [comment]
Sorry man I'll try to find time to fix this

**Comment by deniscerri** [comment]
@freakingdan can you send me the extra command only?

**Comment by deniscerri** [comment]
nvm lol

**Comment by freakingdan** [comment]
> @freakingdan can you send me the extra command only?

but how??

**Comment by error-reporting** [comment]
> > heyyy its working now... the workaround works
> 
> after i update to 1.8.1.1 and installed the latest nightly version of yt-dlp... The workaround doesn't work anymore.. it says in the log:
> 
> ```
> Downloading:
> Title: 
> URL: https://www.instagram.com/reel/C9AEPU2pDOs/?igsh=MWlwYXplajZzdGZ2
> Type: video
> Command: 
>  --downloader "libaria2c.so" --external-downloader-args "aria2c:"--summary-interval=1" " -N "10" --retries "10" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --no-part --trim-filenames "183" --no-mtime --audio-quality "0" --embed-chapters --merge-output-format "mp4" --convert-thumbnails "jpg" -S "+hasaud,res:1080,vcodec:h264,acodec:aac,vext:mp4,aext:mp3" -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/47" -o "%(title).200B.%(ext)s" --print-to-file "video:%()#j" "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/3c8beed358853f952109bbfff34374ab.info.json" --parse-metadata "%(uploader,channel,creator|null)l:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --embed-thumbnail --use-postprocessor "FFmpegCopyStream" --ppa "CopyStream:"-c:v" "libx264" -c:a "aac" -f "mp4" " "https://www.instagram.com/reel/C9AEPU2pDOs/?igsh=MWlwYXplajZzdGZ2" 
> 
> Usage: yt-dlp [OPTIONS] URL [URL...]
> yt-dlp: error: wrong --ppa formatting; No closing quotation
> ```

ytdlnis 1.8.1.1 currently have auto quoting issues with argument in extra command that turn extra command with additional argument 
an example below the app changed a command from this:
--print-to-file "%(filename)#j" "%(title).120B %(id).70B %(uploader).29B %(availability)s %(upload_date>%d/%m/%Y)s.json"
--print-to-file "%(formats_table)#j" "%(title).120B %(id).70B %(uploader).29B %(availability)s %(upload_date>%d/%m/%Y)s.json"
--print-to-file "after_filter:%(comments)#j" "%(title).120B %(id).70B %(uploader).29B %(availability)s %(upload_date>%d/%m/%Y)s.json" 
to this:
--print-to-file "%(filename)#j" "%(title).120B" "%(id).70B" "%(uploader).29B" "%(availability)s" "%(upload_date>%d/%m/%Y)s.json" --print-to-file "%(formats_table)#j" "%(title).120B" "%(id).70B" "%(uploader).29B" "%(availability)s" "%(upload_date>%d/%m/%Y)s.json" --print-to-file "after_filter:%(comments)#j" "%(title).120B" "%(id).70B" "%(uploader).29B" "%(availability)s" "%(upload_date>%d/%m/%Y)s.json"

**Comment by deniscerri** [comment]
I'll try to push a quick update either today or tomorrow for this

**Comment by freakingdan** [comment]
> I'll try to push a quick update either today or tomorrow for this

nice ;)
thank you though
