### ISSUE TITLE
[Feature] Make YTDLnis remember the parameters

### ISSUE THREAD

**Issue by sinancetinkaya** [deniscerri/ytdlnis#650]
### Describe the feature

When the download is unsuccessful for any reason, I have to set the parameters all over again and again. Please make YTDLnis to remember video parameters on this screen 
![Untitled](https://github.com/user-attachments/assets/2a073bbe-5616-4ac5-ae21-03032431878b)

### Reason for adding

It'll save a lot of time

**Comment by deniscerri** [comment]
In the errored section, tap the errored download, in the bottom sheet long press the redownload button. It will remember all of your parameters so u can edit it

**Comment by sinancetinkaya** [comment]
Unbelievable! Why isn't this the default action rather than requiring a long press?

**Comment by deniscerri** [comment]
😅 Perhaps i thought u wanted to retry quickly, but you are right on errored downloads it makes more sense to show the download card.

**Comment by deniscerri** [comment]
Alright so i made the changes. Oh i forgot, u can also swipe the card to the right to redownload, that will open the download card aswell now 🙂

**Comment by sinancetinkaya** [comment]
Thank You! 🙂
