### ISSUE TITLE
[Bug] Mass Re-download doesn't save songs properly

### ISSUE THREAD

**Issue by clairecrichton** [deniscerri/ytdlnis#652]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

Mass re-download doesn't seem to save songs at all. Let alone the correct location. (Downloading songs normally does though, and I tested it with 2 albums that I previously downloaded too.)

### Expected behavior

Mass re-download downloads songs to my set audio folder, or maybe my set commands folder. Both in SD Card/Download/Audio(or Commands)

### Steps to reproduce

1. Select all previously downloaded songs (or even just 2, doesn't happen with just one)
2. Re-download
3. Check my set folders, songs are not there. Check Internal/Download/YTDLnis/Audio, songs are not there.

### Device information

Device: Samsung S9+ (Rooted) SM-G965N
Android Version: 10

### Additional context

I am using the latest master version of yt-dlp.
As the songs were downloading, it would say it was moving it to the desired location. But the songs would just mysteriously never show up there.
(Btw YTDLnis developers you guys are awesome, thank you for implementing the mass re-download. Is there anywhere I can donate?)

**Comment by deniscerri** [comment]
I cant seem to replicate. Maybe you had fresh installed the app and the previously downloaded videos were in a location that the app doesn't have permission 

Because i tried to do redownload and the files are downloaded as expected.
Also i need to remove the old records when hitting redownload, doesnt seem right to just keep them there lol

**Comment by clairecrichton** [comment]
Is there a way i could reset all my settings and keep my download history? Im guessing YTDLnis must have lost permission like you said over the SD card and isnt able to access it even if i try to give it access again

**Comment by deniscerri** [comment]
@clairecrichton u can modify the download location for the items u want to redownload and see if the files end up correctly when the download finishes. 
Btw can you give me a download log of the downloads that finished but there were no files?

**Comment by clairecrichton** [comment]
where are the log files at? (when i said i checked the logs before i meant as the songs were downloading, i probably should have cleared that up, sorry lol)

**Comment by deniscerri** [comment]
Logs are in more tab

**Comment by clairecrichton** [comment]
Downloading:
Title: The Wesley Willis Fiasco
URL: https://www.youtube.com/watch?v=QJSSf3NxIyk
Type: audio
Command: 
 -N "10" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --trim-filenames "180" --no-mtime --audio-quality "0" --extractor-args "youtube:lang=en" -f "ba/b" -x --audio-format "opus" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85885" -S "hasaud,size,acodec:opus,aext:opus" -o "%(uploader).30B - %(title).170B.%(ext)s" --print-to-file "video:%()#j" "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/c70b180020e09aba61a8b67ae8cf8623.info.json" --replace-in-metadata "title" ".+" "The Wesley Willis Fiasco" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "Wesley Willis" --parse-metadata "%(uploader)s:%(artist)s" --embed-metadata --parse-metadata "%(playlist_uploader,artist|)s:^(?P<first_artist>.*?)(?:(?=,\s+)|$)" --parse-metadata "%(album_artist,first_artist|)s:%(album_artist)s" --parse-metadata "description:(?:Released on: )(?P<dscrptn_year>\d{4})" --parse-metadata "%(dscrptn_year,release_year,release_date>%Y,upload_date>%Y)s:(?P<meta_date>\d+)" --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1 -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" "https://www.youtube.com/watch?v=QJSSf3NxIyk" 


[youtube] Extracting URL: https://www.youtube.com/watch?v=QJSSf3NxIyk
[youtube] QJSSf3NxIyk: Downloading webpage
[youtube] QJSSf3NxIyk: Downloading web creator player API JSON
[youtube] QJSSf3NxIyk: Downloading mweb player API JSON
[youtube] QJSSf3NxIyk: Downloading player 62ccfae7
[MetadataParser] Changed title to: The Wesley Willis Fiasco
[MetadataParser] Parsed meta_title from '%(title)s': 'The Wesley Willis Fiasco'
[MetadataParser] Changed uploader to: Wesley Willis
[MetadataParser] Parsed artist from '%(uploader)s': 'Wesley Willis'
[MetadataParser] Parsed first_artist from '%(playlist_uploader,artist|)s': 'Wesley Willis'
[MetadataParser] Parsed album_artist from '%(album_artist,first_artist|)s': 'Wesley Willis'
[MetadataParser] Parsed dscrptn_year from '%(description)s': '1996'
[MetadataParser] Parsed meta_date from '%(dscrptn_year,release_year,release_date>%Y,upload_date>%Y)s': '1996'
[info] QJSSf3NxIyk: Downloading 1 format(s): 251
[info] Writing '%()#j' to: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/c70b180020e09aba61a8b67ae8cf8623.info.json
[info] Downloading video thumbnail 42 ...
[info] Writing video thumbnail 42 to: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85885/Wesley Willis - The Wesley Willis Fiasco.webp
[ThumbnailsConvertor] Converting thumbnail "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85885/Wesley Willis - The Wesley Willis Fiasco.webp" to jpg
Deleting original file /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85885/Wesley Willis - The Wesley Willis Fiasco.webp (pass -k to keep)
[download] Destination: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85885/Wesley Willis - The Wesley Willis Fiasco.webm

[download] 100% of    2.75MiB in 00:00:01 at 2.07MiB/s   
[ExtractAudio] Destination: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85885/Wesley Willis - The Wesley Willis Fiasco.opus
Deleting original file /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85885/Wesley Willis - The Wesley Willis Fiasco.webm (pass -k to keep)
[Metadata] Adding metadata to "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85885/Wesley Willis - The Wesley Willis Fiasco.opus"
[EmbedThumbnail] mutagen: Adding thumbnail to "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85885/Wesley Willis - The Wesley Willis Fiasco.opus"

**Comment by deniscerri** [comment]
@clairecrichton change the download location if u havent. it should work

**Comment by clairecrichton** [comment]
Didn't work, switched audio folder to SD Card/Download/Audio2/ nothing showed up. Here is log:

Downloading:
Title: Lotion
URL: https://www.youtube.com/watch?v=iYHHj5_VSho
Type: audio
Command: 
 -N "10" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --trim-filenames "180" --no-mtime --audio-quality "0" --extractor-args "youtube:lang=en" -f "ba/b" -x --audio-format "opus" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85887" -S "hasaud,size,acodec:opus,aext:opus" -o "%(uploader).30B - %(title).170B.%(ext)s" --print-to-file "video:%()#j" "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/4d0d80c9ddd8148cade04ca4050b0386.info.json" --replace-in-metadata "title" ".+" "Lotion" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "Wesley Willis" --parse-metadata "%(uploader)s:%(artist)s" --embed-metadata --parse-metadata "%(playlist_uploader,artist|)s:^(?P<first_artist>.*?)(?:(?=,\s+)|$)" --parse-metadata "%(album_artist,first_artist|)s:%(album_artist)s" --parse-metadata "description:(?:Released on: )(?P<dscrptn_year>\d{4})" --parse-metadata "%(dscrptn_year,release_year,release_date>%Y,upload_date>%Y)s:(?P<meta_date>\d+)" --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1 -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" "https://www.youtube.com/watch?v=iYHHj5_VSho" 


[youtube] Extracting URL: https://www.youtube.com/watch?v=iYHHj5_VSho
[youtube] iYHHj5_VSho: Downloading webpage
[youtube] iYHHj5_VSho: Downloading web creator player API JSON
[youtube] iYHHj5_VSho: Downloading mweb player API JSON
[youtube] iYHHj5_VSho: Downloading player f8f53e1a
[MetadataParser] Changed title to: Lotion
[MetadataParser] Parsed meta_title from '%(title)s': 'Lotion'
[MetadataParser] Changed uploader to: Wesley Willis
[MetadataParser] Parsed artist from '%(uploader)s': 'Wesley Willis'
[MetadataParser] Parsed first_artist from '%(playlist_uploader,artist|)s': 'Wesley Willis'
[MetadataParser] Parsed album_artist from '%(album_artist,first_artist|)s': 'Wesley Willis'
[MetadataParser] Parsed dscrptn_year from '%(description)s': '1996'
[MetadataParser] Parsed meta_date from '%(dscrptn_year,release_year,release_date>%Y,upload_date>%Y)s': '1996'
[info] iYHHj5_VSho: Downloading 1 format(s): 251
[info] Writing '%()#j' to: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/4d0d80c9ddd8148cade04ca4050b0386.info.json
[info] Downloading video thumbnail 42 ...
[info] Writing video thumbnail 42 to: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85887/Wesley Willis - Lotion.webp
[ThumbnailsConvertor] Converting thumbnail "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85887/Wesley Willis - Lotion.webp" to jpg
Deleting original file /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85887/Wesley Willis - Lotion.webp (pass -k to keep)
[download] Destination: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85887/Wesley Willis - Lotion.webm

[download] 100% of    2.49MiB in 00:00:01 at 1.81MiB/s   
[ExtractAudio] Destination: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85887/Wesley Willis - Lotion.opus
Deleting original file /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85887/Wesley Willis - Lotion.webm (pass -k to keep)
[Metadata] Adding metadata to "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85887/Wesley Willis - Lotion.opus"
[EmbedThumbnail] mutagen: Adding thumbnail to "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/85887/Wesley Willis - Lotion.opus"

**Comment by deniscerri** [comment]
try turning off "Cache downloads first"

**Comment by clairecrichton** [comment]
Uh for some reason that + manually changing the path for each set of downloads seems to work???? Not changing the path per download doesn't though. Doesn't matter, I can redownload my stuff now, thank you for all your help :D
