### ISSUE TITLE
[Bug] Threads not supported

### ISSUE THREAD

**Issue by thradya** [deniscerri/ytdlnis#654]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

Videos in Threads posts seem to be unsupported. Support in yt-dlp was merged in late August if I recall correctly.

### Steps to reproduce

1) In Threads click share, more, ytdlnis, download

### Device information

Samsung S23, Android 14, YTDLNIS 1.8.1.1

### Additional context

Downloading:
Title: 
URL: https://www.threads.net/@takuwoodcraft/post/DDMpeo4ShuT?xmt=AQGzNXuvnfdjWV4WaylyhujEWAjTot9mmDQUr5m6SFBxnA
Type: video
Command: 
 --no-quiet --no-simulate --print "after_move:'%(filepath,_filename)s'" -N "3" --trim-filenames "212" --no-mtime --sponsorblock-remove "music_offtopic" --sponsorblock-mark "all" --embed-chapters -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Download/YTDLnis/Video" -o "%(uploader).30B - %(title).170B.%(ext)s" --print-to-file "video:%()#j" "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/18e6f38f0396dc6d2a4d2b0421afe907.info.json" --parse-metadata "%(uploader,channel,creator|null)l:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://www.threads.net/@takuwoodcraft/post/DDMpeo4ShuT?xmt=AQGzNXuvnfdjWV4WaylyhujEWAjTot9mmDQUr5m6SFBxnA" 

WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://www.threads.net/@takuwoodcraft/post/DDMpeo4ShuT?xmt=AQGzNXuvnfdjWV4WaylyhujEWAjTot9mmDQUr5m6SFBxnA

**Comment by deniscerri** [comment]
It's not like the app makes that error on itself. Ytdlp does. So this is probably a broken extractor issue. Make an issue at yt-dlp

**Comment by thradya** [comment]
Noted. Thanks.
