### ISSUE TITLE
ALSO Download BUG (another case)(outdated?)

### ISSUE THREAD

**Issue by malushok** [deniscerri/ytdlnis#658]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

App does not downloading, BUT it's another problem.(2 actually)
When sys language is Russian, it says ≈ "cannot translate to ru"
When I switched to Eng, I faced ≈ "cannot divide by zero" (python error)
I am using YouTube Music ReVanced Extended (addea's fork)
I am using YTdlnis arm64
I faced issue month ago (1.7.9(?) and later)
I Tried re-downloading
Edit:now it times out

### Steps to reproduce

1. Download Via YM re ex (fake download button)
2. I the download dialogue window, download as any format
3. Wait
4. Here's your error 

### Device information

Infinix Note 30
Android 14 (XOS fork (if it will help))

**Comment by malushok** [comment]
I'm gonna try universal branch

**Comment by malushok** [comment]
Hell no I think it started working?

**Comment by malushok** [comment]
Oh no it times out

**Comment by deniscerri** [comment]
@malushok this is a yt-dlp related issue. Please forward it to them

**Comment by malushok** [comment]
Oke
