### ISSUE TITLE
[Bug] VideoConvertor takes forever

### ISSUE THREAD

**Issue by PincoPallino-lang** [deniscerri/ytdlnis#660]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

VideoConvertor takes forever (7 minutes to convert a 20MB video) at least when converting from mkv to mp4, overheating the device and draining the battery uselessly.

### Expected behavior

VideoConvertor takes a reasonable amount of time and processing power to convert even a small 20MB video.

### Steps to reproduce

1. Begin any video download while having it set to convert the video to mp4
2. Observe

### Device information

Device: Google Pixel 8 Pro
OS: Android 15

### Additional context

Tried with Stable, Master and Nightly versions of yt-dlp. Same result all around.

**Comment by deniscerri** [comment]
please make this issue to yt-dlp developers

**Comment by PincoPallino-lang** [comment]
Got it.

**Comment by PincoPallino-lang** [comment]
Got it.
