### ISSUE TITLE
[Bug] WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U ERROR: [Instagram] C9-x1CjNqxp: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### ISSUE THREAD

**Issue by abdocoode** [deniscerri/ytdlnis#663]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

For some videos on Instagram, when i try to download it said username can't be extracted but for other videos or in most cases it work appropriately 

### Steps to reproduce

1. Press on share button 
 2. Press on the sign of the application to download 

### Device information

Device: realme 6
System: android 11

### Screenshots / Recordings

https://github.com/user-attachments/assets/f13475de-e0a8-48ef-aa53-c33999abd623

**Comment by deniscerri** [comment]
as the error says report it to yt-dlp not here
[https://github.com/yt-dlp/yt-dlp/issues](https://github.com/yt-dlp/yt-dlp/issues)
