### ISSUE TITLE
[Bug] HTTP FORBIDDEN 

### ISSUE THREAD

**Issue by viethunghbk** [deniscerri/ytdlnis#668]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

Downloading:
Title: Crystal Castles - Transgender
URL: https://www.youtube.com/watch?v=FQStbwNCl2Y
Type: audio
Command: 
 -N "3" --trim-filenames "183" --no-mtime --sponsorblock-remove "music_offtopic" --extractor-args "youtube:lang=vi" -f "ba/b" -x -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/22" -S "hasaud,size" -o "%(uploader).30B - %(title).170B.%(ext)s" --print-to-file "video:%()#j" "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/bbeefce1dafd967d002ae63622bf7bd9.info.json" --replace-in-metadata "title" ".+" "Crystal Castles - Transgender" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "LastGangRadio" --parse-metadata "%(uploader)s:%(artist)s" --embed-metadata --parse-metadata "%(playlist_uploader,artist|)s:^(?P<first_artist>.*?)(?:(?=,\s+)|$)" --parse-metadata "%(album_artist,first_artist|)s:%(album_artist)s" --parse-metadata "description:(?:Released on: )(?P<dscrptn_year>\d{4})" --parse-metadata "%(dscrptn_year,release_year,release_date>%Y,upload_date>%Y)s:(?P<meta_date>\d+)" --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1 -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" "https://www.youtube.com/watch?v=FQStbwNCl2Y" 

WARNING: [youtube] Preferring "vi" translated fields. Note that some metadata extraction may fail or be incorrect.
ERROR: unable to download video data: HTTP Error 403: Forbidden

Idk why

### Steps to reproduce

1.download
2.HTTP FORBIDDEN 

### Device information

Iqoo neo 9 android 15

### Screenshots / Recordings

![Uploading Screenshot_20241223_211010.jpg…]()

**Comment by deniscerri** [comment]
pass this issue to yt-dlp repository
[https://github.com/yt-dlp/yt-dlp/issues](https://github.com/yt-dlp/yt-dlp/issues)
