### ISSUE TITLE
Can't download YouTube age-restricted videos

### ISSUE THREAD

**Issue by SempakRangerGG** [deniscerri/ytdlnis#669]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

The app simply refused to download. 

And force close when using yt-dlp --cookies-from-browser 

### Expected behavior

Download

### Steps to reproduce

Share link or copy paste link to Ytdlnis and download. Or try to update video quality 

### Device information

POCO X3 miui 14

### Additional context

ERROR: [youtube] yYVxEnat8OU: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies

ERROR: [youtube] yYVxEnat8OU: Sign in to confirm your age. This video may be inappropriate for some users.

**Comment by SempakRangerGG** [comment]
Nevermind. You can login to YouTube through Ytdlnis. Go to cookies and type youtube.com.

**Comment by BlackConvoy99** [comment]
> Nevermind. You can login to YouTube through Ytdlnis. Go to cookies and type youtube.com. 


Thank you. I've been scratching my head for why I can't download age restricted videos.
