### ISSUE TITLE
Integration to Revanced Extended

### ISSUE THREAD

**Issue by Lorograch1** [deniscerri/ytdlnis#84]
Hi,

First off, thank you for this app. 

I would like to know if you plan to integrate the app to Revanced Extended as well like Revanced. I don't see it in the list of downloaders on yt version 18.13.38. Thanks.

**Comment by soymadip** [comment]
It's not upto this app's dev for that. 

It's upto revanced extended dev. 

I did open a issue to add this app, you can comment and react to that issue. 
https://github.com/inotia00/ReVanced_Extended/issues/352

**Comment by Lorograch1** [comment]
Ahh i see, thank you for the information. I will do the needful!

**Comment by deniscerri** [comment]
The app has been added in the latest inotia00 patches

**Comment by soymadip** [comment]
> The app has been added in the latest inotia00 patches

finally!
