### ISSUE TITLE
Publish to fdroid?

### ISSUE THREAD

**Issue by thibaultmol** [deniscerri/ytdlnis#85]
.

**Comment by deniscerri** [comment]
Made a request a long time ago but haven't gotten a response.

**Comment by XxnittanixX** [comment]
Try itwith musicolet

**Comment by not-programmer98** [comment]
I couldn't find it on fdroid, could you provide a link?

**Comment by deniscerri** [comment]
https://gitlab.com/fdroid/rfp/-/issues/2216

**Comment by deniscerri** [comment]
Its in the works

**Comment by wuttachiemail29gmailcom** [comment]
@wuttachiemail29gmailcom

**Comment by thibaultmol** [comment]
why are you spamming @wuttachiemail29gmailcom ?

**Comment by Korb** [comment]
https://f-droid.org/packages/com.deniscerri.ytdl/ – thank you!

**Comment by zaednasr** [comment]
@Korb it says 404

**Comment by Drhype2580** [comment]
Use droid-ify it comes with izzy on droid and other repo pre included

**Comment by Korb** [comment]
> @Korb it says 404. This might be from izzy's repo and not the main one.

The screenshot above says:

> IzzyOnDroid F-Droid Repo
