### ISSUE TITLE
IzzyOnDroid Issues

### ISSUE THREAD

**Issue by deniscerri** [deniscerri/ytdlnis#90]
Hello @IzzySoft. Im opening this issue to talk about the NonFreeNet antifeature my app has been labelled.
What are the steps i gotta do to remove this label?
Please fill me in. Thanks

**Comment by IzzySoft** [comment]
I've already raised that question [in the F-Droid issue tracker](https://gitlab.com/fdroid/rfp/-/issues/2216#note_1354386796). Maybe we deal with that there (as it will be relevant for F-Droid as well) to complete it? We're already pretty close – and I'd prefer to not run all steps twice :wink:

So in short: if you can confirm there are no such "non-free requests" made by default, I can remove that anti-feature.
