### ISSUE TITLE
[FEATURE REQUEST] Better Tablet UI

### ISSUE THREAD

**Issue by PandoraPandorita** [deniscerri/ytdlnis#92]
**Is your feature request available in yt-dlp? Please describe.**
That isn't relevant to the issue. 

**Describe the solution you'd like**
The app is completely usable in a tablet device, however, there are some improvements and bug fixes that could be done to improve the experience in these devices. 

Some examples is on the lower menu bar, which is fine in tablet, it looks something like this:
![Screenshot_20230416-181608](https://user-images.githubusercontent.com/79670265/232351915-1f4209c6-8969-471a-9e49-a5704abc29b5.png)

This works, however, I think it would looks better the way other apps are doing it, which is by putting it on the side, examples could be...

Tachiyomi:
![Screenshot_20230416-175112](https://user-images.githubusercontent.com/79670265/232352002-f7e7c53d-8b1a-453d-9088-fdd5bc080298.png)

Google Clock:
![Screenshot_20230416-175128](https://user-images.githubusercontent.com/79670265/232352078-b72bc570-cbb7-4d26-bc22-9e65a72e7d9b.png)

Even Microsoft's official Xbox app:
![Screenshot_20230416-175210](https://user-images.githubusercontent.com/79670265/232352046-5c97c59f-243a-457d-8ca9-f0cabedf555e.png)

Another thing that could be improved is the Video grid, which appears on the first image (repeated here):
![Screenshot_20230416-181608](https://user-images.githubusercontent.com/79670265/232351915-1f4209c6-8969-471a-9e49-a5704abc29b5.png)

However, this really doesn't use the potential of a bigger screen an can be quite clunky, a better way to do it could be like Newpipe, which has a higher column and row density:
![Screenshot_20230416-182227](https://user-images.githubusercontent.com/79670265/232352362-fe55cf83-718e-473e-9ea6-509f084f571c.png)

If too difficult or you think it doesn't looks good, a less compact approach could be used, like in the official YouTube app:
![Screenshot_20230416-182404](https://user-images.githubusercontent.com/79670265/232352465-7d8f329b-e420-4e3d-be67-a615e51459f7.png)
(Definitely official, not Revanced) 
Any of those approaches can work, I don't think one is better than the other. 

**Describe alternatives you've considered**
There really isn't any other alternative to this only than to use it as is, however, the experience could be better. 

**Additional context**
Since Android 12L and the launch of Android 13, a lot of Android apps have been adapting their apps to work well on a tablet form factor and not be just the mobile interface stretched, and this app could do the same to work really good on tablets.

**Comment by deniscerri** [comment]
![IMG_20230420_071540_094](https://user-images.githubusercontent.com/64997243/233264920-51d3f681-cd7b-4080-89b0-a56f63a8126a.jpg)
![IMG_20230420_071542_819](https://user-images.githubusercontent.com/64997243/233264924-94ea8dce-3f0f-4c32-939e-08ab4887ffee.jpg)
![IMG_20230420_071545_005](https://user-images.githubusercontent.com/64997243/233264927-f6dffb7a-46ca-444e-a92a-44435e1ed988.jpg)

Stay tuned for the next release

**Comment by deniscerri** [comment]
![image](https://user-images.githubusercontent.com/64997243/233591060-461fb2d4-a0db-4911-aede-60665c93c982.png)

Added a full navigation if you turn the tablet on landscape

**Comment by PandoraPandorita** [comment]
Damn, I didn't expect it to looks so good, nice!

**Comment by PandoraPandorita** [comment]
I hope I'm not getting repetitive with tablet things, but (at least for me) the tablet UI got reverted in the latest release, something like this:

![Screenshot_20230514-201404](https://github.com/deniscerri/ytdlnis/assets/79670265/eb8de15b-4b23-4dfe-93f4-bc3258dbda9e)
This was with 600 dpi, this is with 700, which is interesting at least:
![Screenshot_20230514-201313](https://github.com/deniscerri/ytdlnis/assets/79670265/2caf00ed-2558-42fe-83ac-fdaed0969f12)

Probably something with the scaling or tolerance on when and when not to use that UI?

**Comment by deniscerri** [comment]
Yes you are correct. I was experimenting with the threshhold.
Give me your tablet model so i can reference it. Good thing u mentioned this before the 1.6.2 release

**Comment by PandoraPandorita** [comment]
That's fine, I'm using an Alcatel Joy Tab 2 with custom DPI (600) which is a bit more than the default on the settings (which I checked and it actually had some issues afterwards) so, maybe that helps (?

**Comment by deniscerri** [comment]
@PandoraPandorita if you can, you can drop by in the telegram group and test out if the layout is suitable for you.

**Comment by PandoraPandorita** [comment]
I'm on the discord if that's doable too, I entered really recently

**Comment by deniscerri** [comment]
[1.6.2](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.2)
