### ISSUE TITLE
How long is it between releases?

### ISSUE THREAD

**Issue by TheyEatFood** [deniscerri/ytdlnis#94]
Just wanna now how long it takes between releases!

**Comment by deniscerri** [comment]
Next release will come soon in a few days or a week. Id like to add alot of features at once that's why they are not as often.

**Comment by TheyEatFood** [comment]
Cool! Also can you add a feature to be able to remove the home page. Or make it start in the download page! That would be amazing!

**Comment by deniscerri** [comment]
Then how would you search in the app? Lol

**Comment by TheyEatFood** [comment]
I don't need to :) I mainly use it for my downloads on YT revanced!

**Comment by TheyEatFood** [comment]
Hey hey, I never told you to remove it. Just make a toggle to remove it :) it can be shown by default. But make a toggle!

**Comment by deniscerri** [comment]
Like tab ordering?

**Comment by soymadip** [comment]
> Like tab ordering?

No, like this:- 
https://user-images.githubusercontent.com/84225810/233421409-e69dfdc0-954c-4b72-a61e-1d551c933198.mp4

**Comment by deniscerri** [comment]
I see

**Comment by TheyEatAnything** [comment]
> > Yeah but alot of people do lol. I can't remove a core feature
> 
> I guess he is asking for something like a option to change default tab when opening app.
> Right @TheyEatAnything ?

Yeah! That's what I'm talking about!

**Comment by soymadip** [comment]
Happy to help🤣

**Comment by deniscerri** [comment]
@TheyEatAnything 
![image](https://user-images.githubusercontent.com/64997243/233460611-99b66b51-f4bf-4a2d-9f42-3af481eb262d.png)
Its implemented

**Comment by TheyEatAnything** [comment]
Thanks! :)
